### ISSUE TITLE
启动进程的时候能否标明是什么进程？

### ISSUE THREAD

**Issue by legeng** [easy-swoole/easyswoole#101]
配置8个work , 8个task_work, 启动进程后有19个进程
全部都显示：vendor/bin/easyswoole start 
后来在群里才知道多了个cache 进程
能否支持 启动进程后查看进程显示是master manager cache worker 进程,如：
 vendor/bin/easyswoole master  start
 vendor/bin/easyswoole manager  start

**Comment by kiss291323003** [comment]
你自己linux基础太差，ps tree 了解一下谢谢
