### ISSUE TITLE
自定义路由解析参数存在句号点的话，最末尾句号点后面内容就会被吞掉

### ISSUE THREAD

**Issue by willove** [easy-swoole/easyswoole#102]
我设定的路由规则是 api/open/ip/find/{ip}
实际调用 api/open/ip/find/192.168.2.1 路由解析之后 ip的值只有 192.168.2
如果在后面加上后缀，比如 api/open/ip/find/192.168.2.1.html 这样才能完整的获取到IP值。
使用正则验证也是一样，末尾还是得再加上一个句号点 .

**Comment by kiss291323003** [comment]
按照HTTP RFC规范，当你访问api/open/ip/find/192.168.2.1的时候实际上是在请求api/open/ip/find/这个路径下文件名为192.168.2文件后缀为1的文件（URL,统一资源定位符），而swoole的url解析，采用pathinfo模式，因此，对于我解析而言，实际的path是api/open/ip/find/192.168.2而非api/open/ip/find/192.168.2
