### ISSUE TITLE
使用redisPool的时候，报错！

### ISSUE THREAD

**Issue by lengzhao1005** [easy-swoole/easyswoole#113]
![image](https://user-images.githubusercontent.com/26397176/44902089-a2c07e00-ad3b-11e8-9a31-fa18089b5679.png)
![image](https://user-images.githubusercontent.com/26397176/44902147-c388d380-ad3b-11e8-8981-35f2a50c4e34.png)
SwooleRedis这个类是继承php原生的redis，并不是client，无connected属性
![image](https://user-images.githubusercontent.com/26397176/44902241-0054ca80-ad3c-11e8-97e1-7785a3bc9812.png)

**Comment by windrunner414** [comment]
Swoole\Coroutine\Redis有connected，你最后一张图是年久失修的ide-helper
