### ISSUE TITLE
How to get route param in controller

### ISSUE THREAD

**Issue by mich4s** [easy-swoole/easyswoole#115]
Hello, I need to get route param in controller action. I can't find it on documentation and code. Is there any way to retrieve this data?

**Comment by kiss291323003** [comment]
can you show me you code or example?

**Comment by mich4s** [comment]
`$routeCollector->get('/{id:\d+}', function (Request $request, Response $response) {
                new ItemController('offer', $request, $response);
            });`

And now I need to get this in ItemController action. Im doing now composer package to add this, but if there's official way for this I'd like to use this.

**Comment by woann** [comment]
@mich4s Don't use this framework,It's  rubbish。。

**Comment by woann** [comment]
@windrunner414 Because the people in this QQ group.There are many idiots.

**Comment by weiwei2012holy** [comment]
@woann Both easySwoole and workMan are awesome,they are so innocent,depreciate others will only makes u looks like a fool~~
