### ISSUE TITLE
官网文档框架安装下有一项报错处理

### ISSUE THREAD

**Issue by mao02** [easy-swoole/easyswoole#116]
在一些环境中，特别是使用集成面板安装的 PHP 环境，会出现以下报错……

我使用宝塔面板进行安装，确实出现了上述问题，在面板中把php的禁用函数去掉就可以了，我并没有去细查哪个函数被禁用导致安装失败，但是我不禁用函数的情况下是可以同时使用easyswoole和宝塔面板的，希望作者写到手册中，让更多面板用户可以使用easyswoole

**Comment by gymiles** [comment]
感谢提示，我也用的宝塔，应该是readlink这个函数被禁用的原因。
