### ISSUE TITLE
无法使用 Cache 是什么原因

### ISSUE THREAD

**Issue by cw58665466** [easy-swoole/easyswoole#121]
刚开始可以使用
`Cache::getInstance()->set('token','test');`

调试了多次后就再也不能使用了

swoole.log
会出现如下错误
`
[2018-09-27 16:41:04 $6825.0]	WARNING	swManager_check_exit_status: worker#5 abnormal exit, status=0, signal=11`

开发环境如下：

> swoole version      2.0.7
> php version         7.2.1
> MacBook Pro      10.14

**Comment by kiss291323003** [comment]
sw版本换下吧，如果你没有使用协程api，建议换为1.1.x的swoole，如果有，那么建议使用es3搭配sw4。由于历史原因，sw2存在一些问题，详情可以加esQQ群咨询
