### ISSUE TITLE
【建议】serverStop命令等待时间根据max_wait_time设置，兼容异步安全重启特性

### ISSUE THREAD

**Issue by chaiyanlin** [easy-swoole/easyswoole#125]
## 使用背景

```
'SETTING' => [
            'task_worker_num' => 8, //异步任务进程
            'task_max_request' => 10,
            'max_request' => 5000, //强烈建议设置此配置项
            'worker_num' => 8,
            'reload_async' => true, // 支持异步安全重启特性 https://wiki.swoole.com/wiki/page/775.html
            'max_wait_time' => 30, // Worker进程最大等待时间，默认为30秒
        ],
```

为了保证 `reload`, `stop`, `restart` 场景不会中断处理中的请求，通常会设置`reload_async` & `max_wait_time` 。

## 实际情况

```
php easyswoole stop
#!/usr/bin/env php
stop server fail.try -f again 
```
由于`serverStop`方法中写死了执行等待时间为`5s`所以出现上述的情况，不过在停止服务时这个情况**无伤大雅**，因为过一会worker也会结束，或者达到`max_wait_time`被强制结束。

**但在`restart`的场景下**，`serverStop`只等待5s，导致`serverStart`并没有被执行到。

## 建议

是否可以考虑`serverStop`的等待时间可根据`max_wait_time`配置，如果没有配置，则默认30s。

**Comment by kiss291323003** [comment]
你可以直接pr修改的
