### ISSUE TITLE
建议命名空间规范化

### ISSUE THREAD

**Issue by legeng** [easy-swoole/easyswoole#127]
首先恭喜EasySwoole做的越来越好了，使用的人越来越多了，知名度越来越大了，但是我还是有点建议，规范问题，如框架命名空间有点混乱，不完全是PSR-4 ，看源代码好多地方用 use EasySwoole\EasySwoole\xxxxxx，这个完全可以改成这样 use EasySwoole\xxxxxx，这样看起来框架更加规范化。比如laravel , 命名空间和核心函数名这些命名就非常的规范，可读性强。

**Comment by kiss291323003** [comment]
额、、、其实是这样的。3.x后，Easyswoole\Easyswoole下的东西，是主库，Easyswoole\xxxx下的，是组件。es3全部组件化了。任何组件都可以独立使用
