### ISSUE TITLE
Call to undefined function App\HttpController\Api\err() 

### ISSUE THREAD

**Issue by chuzhaoqian** [easy-swoole/easyswoole#130]
composer.json
`{
    "autoload": {
        "psr-4": {
            "App\\": "App/"
        },
        "files":[
            "App/Tools/function.php"
        ]
    },
    "require": {
        "easyswoole/easyswoole": "3.x-dev",
        "easyswoole/swoole-ide-helper": "^1.03",
        "easyswoole/mysqli": "^1.0",
        "easyswoole/socket": "^1.1"
    }
}`

function.php
`if (!function_exists("err")) {
    /**
     * 抛出异常
     * @param string $smg 消息
     * @param int $code 错误码
     * @throws Exception
     */
    function err(string $smg, int $code=400)
    {
        throw new \Exception($smg, $code);
    }
}`
找不到err方法

**Comment by chuzhaoqian** [comment]
已经执行 composer 更新

**Comment by kiss291323003** [comment]
米有看懂你要表达的

**Comment by evalor** [comment]
可在全局event，框架初始化时，直接require 'path/to/functions.php'

**Comment by chuzhaoqian** [comment]
@evalor 懂了
