### ISSUE TITLE
Mysql协程连接池 不同model 事务问题

### ISSUE THREAD

**Issue by chuzhaoqian** [easy-swoole/easyswoole#131]
不同model  初始化后在一个model中进行事务操作
只会回滚当前model中的数据
这个有没有好的解决方案
1.获取model  table 在一个model中操作
2. 构造函数传递 $db 实现公用db
3. $db 单独放到静态类中 实现单例

**Comment by chuzhaoqian** [comment]
`<?php
/**
 * @author: chuzhaoqian
 */

namespace App\Tools;

use EasySwoole\Component\Pool\PoolManager;
use App\Utility\Pool\MysqlPool;
use EasySwoole\EasySwoole\Config;
use App\Utility\Pool\MysqlObject;
use Swoole\Coroutine;

class MysqlStatic
{
    protected static $pool = [];

    /**
     * 初始
     */
    static function init()
    {
        $cid = Coroutine::getuid();
        if ($cid < 0) {
            throw new Warning('当前不在协程环境中');
        }
        if (!isset(self::$pool[$cid])) {
            self::$pool[$cid] = PoolManager::getInstance()->getPool(MysqlPool::class)
                ->getObj(Config::getInstance()->getConf('mysql.db_1.POOL_TIME_OUT'));
        }
        if (self::$pool[$cid] instanceof MysqlObject) {
            return self::$pool[$cid];
        } else {
            throw new Warning('mysql pool is empty');
        }
    }

    /**
     * 结束
     */
    static function end()
    {
        $cid = Coroutine::getuid();
        if ($cid > 0) {
            if (isset(self::$pool[$cid]) && self::$pool[$cid] instanceof MysqlObject) {
                PoolManager::getInstance()->getPool(MysqlPool::class)
                    ->recycleObj(self::$pool[$cid]);
            }
            unset(self::$pool[$cid]);
        }
    }
}`

**Comment by chuzhaoqian** [comment]
我用的这种方法维护的扩model 事务，但是看着协程ID一直在增加不知道会不会有上线问题会不会崩溃


`<?php

namespace App\Tools;

use EasySwoole\Component\Pool\PoolManager;
use App\Utility\Pool\MysqlPool;
use EasySwoole\EasySwoole\Config;
use App\Utility\Pool\MysqlObject;
use Swoole\Coroutine;

class MysqlStatic
{
    protected static $pool = [];

    /**
     * 初始
     */
    static function init()
    {
        $cid = Coroutine::getuid();
        if ($cid < 0) {
            throw new Warning('当前不在协程环境中');
        }
        if (!isset(self::$pool[$cid])) {
            self::$pool[$cid] = PoolManager::getInstance()->getPool(MysqlPool::class)
                ->getObj(Config::getInstance()->getConf('mysql.db_1.POOL_TIME_OUT'));
        }
        if (self::$pool[$cid] instanceof MysqlObject) {
            return self::$pool[$cid];
        } else {
            throw new Warning('mysql pool is empty');
        }
    }

    /**
     * 结束
     */
    static function end()
    {
        $cid = Coroutine::getuid();
        if ($cid > 0) {
            if (isset(self::$pool[$cid]) && self::$pool[$cid] instanceof MysqlObject) {
                PoolManager::getInstance()->getPool(MysqlPool::class)
                    ->recycleObj(self::$pool[$cid]);
            }
            unset(self::$pool[$cid]);
        }
    }
}`

**Comment by chuzhaoqian** [comment]
或者问题是 model 的析构函数中 做了关闭mysql 链接池的问题 现在把 
连接池的关闭挪到EasySwooleEvent.php 的 afterRequest 方法中
链接获取对象还是在 model 中获取 ，但是现在还用的 MysqlStatic 来维护 感觉这个影响不是很大  当一个维护静态变量的例子吧

**Comment by chuzhaoqian** [comment]
似乎  只是解决了http 的 mysql 连接池的问题
像socket  异步(finish 没看到怎么触发) 定时 这些的结束方式并不一样啊
有没有一个适合全局的结束方法

**Comment by chuzhaoqian** [comment]
Task  Coroutine::getuid()  为-1  不在协程环境  这就纠结了

**Comment by evalor** [comment]
请看demo库中的模型实现，由控制器统一获取链接，并将链接传入模型中，使得所有模型使用同一个连接操作，统一commit或rollback

**Comment by chuzhaoqian** [comment]
好的  新项目选用这个框架 还是有些不太熟悉swoole  现在正在改改习惯  可以接受的  
看着好多人都写了不少代码了  我弄了trait 控制表名来实现了部分自己的代码   
都是眼泪啊
