### ISSUE TITLE
创建异步任何，执行数据搬移出错

### ISSUE THREAD

**Issue by zhupaizhang** [easy-swoole/easyswoole#132]
我使用的是2.0版本，创建了一个同步数据的任务
`TaskManager::async(function () use ($user_id, $yf_shop_base, $erp_shop_base) {
                $shop_id = (int)$yf_shop_base['shop_id'];
                Logger::getInstance()->log('商城同步商品到ERP开始：', 'import_goods_yf_erp');
                $yf_goods_rows = (new GoodsCommon())->getGoodsList($shop_id);
                if($yf_goods_rows) {
                    foreach ($yf_goods_rows as $key => $item) {
//                        Logger::getInstance()->log($key.'==='.json_encode($item), 'import_goods_data');
                        (new \App\Model\Erp\GoodsCommon())->importGoods($item, $erp_shop_base);
                    }
                }
            }, function () {
                Logger::getInstance()->log('商城同步商品到ERP结束：', 'import_goods_yf_erp');
            });`

出现了一下错误：
`PHP Warning:  include(/Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Component/Trigger.php): failed to open stream: Too many open files in /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php on line 444

Warning: include(/Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Component/Trigger.php): failed to open stream: Too many open files in /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Applications/MAMP/htdocs/easyswoole/vendor/composer/../easyswoole/easyswoole/src/Core/Component/Trigger.php' for inclusion (include_path='.:/Applications/MAMP/bin/php/php7.1.22/lib/php') in /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/Applications/MAMP/htdocs/easyswoole/vendor/composer/../easyswoole/easyswoole/src/Core/Component/Trigger.php' for inclusion (include_path='.:/Applications/MAMP/bin/php/php7.1.22/lib/php') in /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught Error: Class 'EasySwoole\Core\Component\Trigger' not found in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php:78
Stack trace:
#0 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): EasySwoole\Core\Core->EasySwoole\Core\{closure}(2, 'include(/Applic...', '/Applications/M...', 444, Array)
#1 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): include()
#2 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Applications/M...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('EasySwoole\\Core...')
#4 /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Swoole/EventHelper.php(86): spl_autoload_call('EasySwoole\\Core...')
#5 /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Component/Invoker.php(71): EasySwoole\Core\Swoole\EventHelper::EasySwoole\Core\Swoole\{closure}(Object(Swoole\Http\Server), 0, 5, Object( in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php on line 78

Fatal error: Uncaught Error: Class 'EasySwoole\Core\Component\Trigger' not found in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php:78
Stack trace:
#0 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): EasySwoole\Core\Core->EasySwoole\Core\{closure}(2, 'include(/Applic...', '/Applications/M...', 444, Array)
#1 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): include()
#2 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Applications/M...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('EasySwoole\\Core...')
#4 /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Swoole/EventHelper.php(86): spl_autoload_call('EasySwoole\\Core...')
#5 /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Component/Invoker.php(71): EasySwoole\Core\Swoole\EventHelper::EasySwoole\Core\Swoole\{closure}(Object(Swoole\Http\Server), 0, 5, Object( in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php on line 78
PHP Fatal error:  Uncaught Error: Class 'EasySwoole\Core\Component\Trigger' not found in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php:78
Stack trace:
#0 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): EasySwoole\Core\Core->EasySwoole\Core\{closure}(2, 'include(/Applic...', '/Applications/M...', 444, Array)
#1 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): include()
#2 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Applications/M...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('EasySwoole\\Core...')
#4 /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php(88): spl_autoload_call('EasySwoole\\Core...')
#5 [internal function]: EasySwoole\Core\Core->EasySwoole\Core\{closure}()
#6 {main}
  thrown in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php on line 78

Fatal error: Uncaught Error: Class 'EasySwoole\Core\Component\Trigger' not found in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php:78
Stack trace:
#0 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): EasySwoole\Core\Core->EasySwoole\Core\{closure}(2, 'include(/Applic...', '/Applications/M...', 444, Array)
#1 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(444): include()
#2 /Applications/MAMP/htdocs/easyswoole/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Applications/M...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('EasySwoole\\Core...')
#4 /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php(88): spl_autoload_call('EasySwoole\\Core...')
#5 [internal function]: EasySwoole\Core\Core->EasySwoole\Core\{closure}()
#6 {main}
  thrown in /Applications/MAMP/htdocs/easyswoole/vendor/easyswoole/easyswoole/src/Core/Core.php on line 78
`

**Comment by kiss291323003** [comment]
这不是框架问题，是你的机器打开的文件句柄数量限制
