### ISSUE TITLE
MysqlPool 无法实例化

### ISSUE THREAD

**Issue by baiachen** [easy-swoole/easyswoole#133]
当我执行 ab -n 1000 -c 100 的时候，PoolManager::getInstance()->getPool(MysqlPool::class)->getObj(Config::getInstance()->getConf('MYSQL.POOL_TIME_OUT'))  为什么会返回一个NULL

**Comment by kiss291323003** [comment]
首先，你要明白，连接池存在的意义，是为了保护数据库，避免达到数据库的最大连接数，其次才是减少每次都连接的时间。那么因此，就不能保证每次请求都拿得到连接。这是一种自我保护策略。你需要在拿连接的时候进行判断。在高并发下。你可以加大每个进程的最大连接数量和等待时间来减少或者是避免连接不够的情况。当然，这并不能百分百避免，而且请实际根据你数据库的承载力来配置
