### ISSUE TITLE
composer require easyswoole/easyswoole：easyswoole/easyswoole 3.0.7 requires ext-swoole ...

### ISSUE THREAD

**Issue by aben1188** [easy-swoole/easyswoole#134]
您好！执行composer require easyswoole/easyswoole，提示出错：

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - easyswoole/easyswoole 3.0.7 requires ext-swoole >=4.2.6 -> the requested PHP extension swoole is missing from your system.
    ......
    - easyswoole/easyswoole 3.0.2 requires ext-swoole >=4.0.3 -> the requested PHP extension swoole is missing from your system.
    - easyswoole/easyswoole 3.0.1-stable requires ext-swoole >=4.0.3 -> the requested PHP extension swoole is missing from your system.
    - Installation request for easyswoole/easyswoole ^3.0 -> satisfiable by easyswoole/easyswoole[3.0.1-stable, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp64\bin\php\php7.1.22\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

请问，上述错误提示中的ext-swoole指的应该就是swoole.so吧？

我是在Windows上通过phpstorm远程开发，远程服务器已经成功安装并启用了swoole，phpstorm上也已经将php解释器指向了远程服务器上的php解释器。一般来讲这种情况下本地应该可以不用再安装pecl扩展，比如同样为pecl扩展的SeasLog，我本地就没有安装，而是直接使用的远程服务器的。不知道swoole是否也能这样？像我这种情况应该怎样处理呢？

谢谢！

**Comment by kiss291323003** [comment]
首先、composer识别的是你本地的php环境而非远程、、、建议虚拟机或者docker。不然就上mac

**Comment by aben1188** [comment]
> 首先、composer识别的是你本地的php环境而非远程、、、建议虚拟机或者docker。不然就上mac

用虚拟机或者mac开发（docker还不会），如果一样使用phpstorm远程开发的话，本地和远程都要同时安装swoole扩展和easyswoole框架吗？如果是的话，那还要随时保持两者环境的一致性，对吧？

**Comment by aben1188** [comment]
> 首先、composer识别的是你本地的php环境而非远程、、、建议虚拟机或者docker。不然就上mac

用虚拟机或者mac开发（docker还不会，目前公司也没使用docker的计划），如果一样使用phpstorm远程开发的话，本地和远程都要同时安装swoole扩展和easyswoole框架，对吧？如果这样的话，那还要随时保持本地和远程环境以及swoole扩展和easyswoole框架两者版本的一致性，对吧？
