### ISSUE TITLE
English docs are down

### ISSUE THREAD

**Issue by aolko** [easy-swoole/easyswoole#135]
Please fix the english docs

**Comment by kiss291323003** [comment]
we have not written the english doc yet , but we are going to write it , if you like ,you could join us and help us translate it into english .

**Comment by aolko** [comment]
i wanted to do a chat, with shared host restrictions in mind

**Comment by kiss291323003** [comment]
so you need is a websocket service ? if so ,you can see the demo at https://github.com/easy-swoole/demo/tree/3.x-chat

**Comment by aolko** [comment]
> so you need is a websocket service ? if so ,you can see the demo at https://github.com/easy-swoole/demo/tree/3.x-chat

that one depends on redis, not my case, mysql at minimum
