### ISSUE TITLE
mysqli组件能否select db？

### ISSUE THREAD

**Issue by nashgao** [easy-swoole/easyswoole#136]
我按照document和demo配置了mysql协程池并且安装了mysqli组件 
但是似乎并不能执行类似select db这样的语句 我试着用mysqli组件中的rawQuery执行throw了prepareQueryfail 所以想请教一下如何实现select db这样的功能？ 
感谢

**Comment by kiss291323003** [comment]
$mysql->getMysqlClient()->query('select db') 这样试过吗

**Comment by nashgao** [comment]
十分感谢!
