### ISSUE TITLE
User sessions in multiple servers

### ISSUE THREAD

**Issue by zilveer** [easy-swoole/easyswoole#151]
Hi everyone,
a question can Easyswoole handle user sessions through multiple servers (front end ) connected to one database server ?

I am thinking of that Laravel can handle it since one can store sessions in the database, is this possible to do the same with Easyswoole ?

If not, is ther any other way to share the user sessions in multiple servers ?

Regards

**Comment by id0612** [comment]
Of course.

**Comment by zilveer** [comment]
@id0612
Thx for quick reply.but I assume that currently it is not possible with the current built in session handler right ?

**Comment by id0612** [comment]
$this->session supports specifying your own session handle. See my screenshot.

**Comment by id0612** [comment]
@zilveer [https://secure.php.net/manual/zh/class.sessionhandlerinterface.php](url)

**Comment by id0612** [comment]
@zilveer  https://secure.php.net/manual/zh/class.sessionhandlerinterface.php

**Comment by id0612** [comment]
@zilveer https://github.com/easy-swoole/doc/blob/master/Manual/2.x/Cn/Other/redisSession.md
