### ISSUE TITLE
swoole4.2.13中TaskManager中的函数都无法使用

### ISSUE THREAD

**Issue by chenjing0521** [easy-swoole/easyswoole#160]
swoole4.2.13中TaskManager中的函数都无法使用，查看easyswoole源代码和swoole官方手册好像并没有提及改变了swoole底层task的源代码，

**Comment by chenjing0521** [comment]
swoole4.2.12是正常的

**Comment by chenjing0521** [comment]
我发现了这个问题是由于 task_enable_coroutine 这个配置项导致的 原生代码是这样，但是框架不知道什么问题去除这个配置项，依然存在这个问题

**Comment by kiss291323003** [comment]
请给复现的例子，我合并无法复现

**Comment by chenjing0521** [comment]
这是代码 在http_server里面
![1](https://user-images.githubusercontent.com/43941983/52535235-cf66d000-2d86-11e9-9b40-10ce4e2d99b4.png)

注意看版本的不同
![2](https://user-images.githubusercontent.com/43941983/52535248-e7d6ea80-2d86-11e9-84db-5b1b6ec1ec1d.png)

![3](https://user-images.githubusercontent.com/43941983/52535254-f91ff700-2d86-11e9-9eea-27572dcce02b.png)

**Comment by chenjing0521** [comment]
这些异步例子和模板都是官方文档的例子，我唯一改变的就是swoole的版本，我的swoole 使用swoole官方文档中的例子代码实现异步task没有问题

**Comment by netstao** [comment]
我也遇到
swoole version                4.2.13
php version                   7.3.1
easy swoole                   3.1.14

**Comment by YeDongaidiiqu** [comment]
我玩了下也是这样，原来有版本的问题啊，

swoole version                4.2.13
php version                   7.2.11
easy swoole                   3.1.14


  $this->response()->setMessage('this is delay action');
        $client = $this->caller()->getClient();
        // 异步推送, 这里直接 use fd也是可以的
        // TaskManager::async 回调参数中的代码是在 task 进程中执行的 默认不含连接池 需要注意可能出现 getPool null的情况
        TaskManager::async(function () use ($client){
            $server = ServerManager::getInstance()->getSwooleServer();
            $i = 0;
            while ($i < 5) {
                sleep(1);
                $server->push($client->getFd(),'push in http at '.time());
                $i++;
            }
        });

无法推送消息给客户端
  @kiss291323003 @chenjing0521 @netstao

**Comment by YeDongaidiiqu** [comment]
这些问题在 swoole version                4.2.12  都不存在

**Comment by chenjing0521** [comment]
我看了源码感觉没什么问题，可能是没找到吧！只有等官方修复了，目前我是降回4.2.12了

**Comment by kiss291323003** [comment]
已经确认是swoolebug,请后续升级即可

**Comment by netstao** [comment]
@kiss291323003  你反馈给swoole 了吗
