### ISSUE TITLE
无须给随机数发生器播种

### ISSUE THREAD

**Issue by xinhaiz** [easy-swoole/easyswoole#163]
当前PHP版本基本上高于5.0，无须给随机数发生器播种，这样容易误导新人，详情可查阅官方手册说明

**Comment by kiss291323003** [comment]
请别过度自信了。
自己跑测试代码：
mt_rand(0, 1);    // 此处调用了 mt_rand 已经在父进程内自动播种
$worker_num = 16;

// fork 进程
for ($i = 0; $i < $worker_num; $i++) {
    $process = new swoole_process('child_async', false, 2);
    $pid = $process->start();
}

function child_async(swoole_process $worker)
{
    mt_srand();  // 此处 必须要重新播种 否则会得到相同的结果
    echo mt_rand(0, 100) . PHP_EOL;
    $worker->exit();
}
