### ISSUE TITLE
websocket 服务器，最大连接数跟worker_num 一样

### ISSUE THREAD

**Issue by YeDongaidiiqu** [easy-swoole/easyswoole#166]
用easyswoole 当websocket 服务器时，
![qq 20190214153250](https://user-images.githubusercontent.com/25131877/52770359-d1be7800-306d-11e9-9829-92263e679ee3.png)
发现客户端的连接数最大为worker_num ,达到8后，连接建立不了。
发现fd是递增的，手册上没有发现怎样关闭连接，
不知道这是bug ,还是我没找到怎么解决
![image](https://user-images.githubusercontent.com/25131877/52770507-442f5800-306e-11e9-90d6-c84dfe76ae28.png)
当直接关闭客户端是，这个好像没用，但是swoole日志里有记载
![image](https://user-images.githubusercontent.com/25131877/52770540-5c06dc00-306e-11e9-885c-3b573205de07.png)

**Comment by YeDongaidiiqu** [comment]
这些问题在 swoole version                4.2.12  都不存在

**Comment by kiss291323003** [comment]
目前是swoole底层问题，请等待swoole升级
