### ISSUE TITLE
这样改会导致自定义process不能投递任务吧？

### ISSUE THREAD

**Issue by xuhaoxian** [easy-swoole/easyswoole#167]
这样改会导致自定义process不能投递任务吧？
我之前试过在crontask process中欧直接 async  会报错的  说task()方法只能在worker中使用，如果把processasync改成这样 可能会导致自定义进程   crontask process不能投递任务

**Comment by kiss291323003** [comment]
请看composer.json require的swoole 版本

**Comment by xuhaoxian** [comment]
你的意思是最新版本的swoole，自定义进程用那个方法可以投递任务给worker是吗

**Comment by MarsWgl** [comment]
升级4.2.13版本之后task传callback进去试试。
![image](https://user-images.githubusercontent.com/8773142/53396474-7a11fc00-39df-11e9-8dd8-e9ee13b032ab.png)
我这样写是可以执行的。
