### ISSUE TITLE
环境配置加载那里可以优化下吗

### ISSUE THREAD

**Issue by jack15083** [easy-swoole/easyswoole#169]
框架现在默认只有两个环境  实际使用中可能不止两套有本地，开发，, 测试，预发，生产，等多套环境配置，我看代码那里写死了，可不可以改成根据启动命令加载比如 php easyswoole start preview 去加载预发环境配置preview.php呢

    public function loadEnv()
    {
        //加载之前，先清空原来的
        if($this->isDev){
            $file  = EASYSWOOLE_ROOT.'/dev.php';
        }else{
            $file  = EASYSWOOLE_ROOT.'/produce.php';
        }
        Config::getInstance()->loadEnv($file);
    }

**Comment by kiss291323003** [comment]
这种的话，实际上已经是个性化需求了。我建议你用自定义命令实现它
