### ISSUE TITLE
easyswoole3.1.16-dev中TaskManager无法投递任务。

### ISSUE THREAD

**Issue by teevil** [easy-swoole/easyswoole#173]

**Comment by teevil** [comment]
这样写，任务无法投递
`TaskManager::async(
            Message::class
        );`
这样写，任务可以投递并运行任务。
`TaskManager::async(
            Message::class,
            function(){}
        );`
Message.php
`<?php
namespace App\HttpController\Api\Task;
use EasySwoole\EasySwoole\Swoole\Task\AbstractAsyncTask;
class Message extends AbstractAsyncTask
{
    protected function run($taskData, $taskId, $fromWorkerId, $flags = null)
    {
        echo "异步任务开始\n";
        return true;
    }
    
    protected function finish($result, $task_id)
    {
        echo "异步任务结束\n";
    }
}`

**Comment by kiss291323003** [comment]
这是swoole底层的一个问题。请升级到4.3.0的swoole
