### ISSUE TITLE
crontab 出现问题

### ISSUE THREAD

**Issue by a5653132** [easy-swoole/easyswoole#174]
![wrong](https://user-images.githubusercontent.com/23566839/53558821-c7c76980-3b83-11e9-8fbf-e443517870d9.png)

run 方法会报一个需要实现的错误 但是类已经是继承的状态了。

**Comment by kiss291323003** [comment]
你这个是ide识别错误问题

**Comment by a5653132** [comment]
大哥 你们为什么不自己测试一下呢 ？ 问题直接就给我关了 ？ 同一个类可以 继承和实现么？

**Comment by willove** [comment]
Interface的方法必须要一对一的写全，IDE提示的很清楚了，那是你的问题。
