### ISSUE TITLE
websocket 下 dispatch 在分发之后 instanceof Controller 出现问题 导致报错 controller pool empty

### ISSUE THREAD

**Issue by Kbody** [easy-swoole/easyswoole#179]
版本信息  
sw:4.2.11
es:3.1.14

分发器
public function decode($raw, $client): ?Caller
    {
        $caller = new Caller;
   public function decode($raw, $client): ?Caller
    {
        $caller = new Caller;
        $caller->setControllerClass("\\App\\WebSocket\\Controller\\Index");
        $caller->setAction('heartbeat');
        return $caller;
    }

注册事件
// 注册WS事件回调
        $conf = new \EasySwoole\Socket\Config();
        $conf->setType($conf::WEB_SOCKET);
        $conf->setParser(new WebSocketParser);
        $dispatch = new Dispatcher($conf);
        // 收到客户端消息时的处理
        $register->set(EventRegister::onMessage, function (\swoole_server $server, \swoole_websocket_frame $frame) use ($dispatch) {
            $dispatch->dispatch($server, $frame->data, $frame);
        });

报错信息
PHP Fatal error:  Uncaught EasySwoole\Socket\Exception\ControllerPoolEmpty: controller pool empty for \App\WebSocket\Controller\Index in /usr/share/nginx/html/chengzi/vendor/easyswoole/socket/src/Dispatcher.php:89
Stack trace:
#0 /usr/share/nginx/html/chengzi/EasySwooleEvent.php(49): EasySwoole\Socket\Dispatcher->dispatch(Object(Swoole\WebSocket\Server), 'PING', Object(Swoole\WebSocket\Frame))
#1 [internal function]: EasySwoole\EasySwoole\EasySwooleEvent::EasySwoole\EasySwoole\{closure}(Object(Swoole\WebSocket\Server), Object(Swoole\WebSocket\Frame))
#2 /usr/share/nginx/html/chengzi/vendor/easyswoole/easyswoole/src/ServerManager.php(99): call_user_func(Object(Closure), Object(Swoole\WebSocket\Server), Object(Swoole\WebSocket\Frame))
#3 {main}
  thrown in /usr/share/nginx/html/chengzi/vendor/easyswoole/socket/src/Dispatcher.php on line 89

Fatal error: Uncaught EasySwoole\Socket\Exception\ControllerPoolEmpty: controller pool empty for \App\WebSocket\Controller\Index in /usr/share/nginx/html/chengzi/vendor/easyswoole/socket/src/Dispatcher.php:89
Stack trace:
#0 /usr/share/nginx/html/chengzi/EasySwooleEvent.php(49): EasySwoole\Socket\Dispatcher->dispatch(Object(Swoole\WebSocket\Server), 'PING', Object(Swoole\WebSocket\Frame))
#1 [internal function]: EasySwoole\EasySwoole\EasySwooleEvent::EasySwoole\EasySwoole\{closure}(Object(Swoole\WebSocket\Server), Object(Swoole\WebSocket\Frame))
#2 /usr/share/nginx/html/chengzi/vendor/easyswoole/easyswoole/src/ServerManager.php(99): call_user_func(Object(Closure), Object(Swoole\WebSocket\Server), Object(Swoole\WebSocket\Frame))
#3 {main}
  thrown in /usr/share/nginx/html/chengzi/vendor/easyswoole/socket/src/Dispatcher.php on line 89

**Comment by kiss291323003** [comment]
composer up一下

**Comment by kiss291323003** [comment]
另外请升级swoole到4.3.0

**Comment by 2125zyrc** [comment]
> 另外请升级swoole到4.3.0

问题依旧存在  就及时修复

**Comment by Kbody** [comment]
请问修复了吗

**Comment by xuhaoxian** [comment]
pool is empty 是因为进程池的连接被消耗光了   只要把timeout设置长一点就可以解决

**Comment by 2125zyrc** [comment]
没有看到配置文件有这个参数，你能说一下吗

许豪贤 <notifications@github.com> 于2019年3月30日周六 下午4:14写道：
