### ISSUE TITLE
任务模板类是否可以添加传递\swoole_server参数（比如用户获取当前任务进程PID）

### ISSUE THREAD

**Issue by GnixSung** [easy-swoole/easyswoole#182]
任务模板类是否可以添加传递\swoole_server参数（比如用户获取当前任务进程PID）

**Comment by kiss291323003** [comment]
请用ServerManager来取得当前进程的swoole_server实例

**Comment by GnixSung** [comment]
ServerManager::getInstance()->getSwooleServer()->worker_pid
