### ISSUE TITLE
Auth.php中会产生找不到User的Notice错误

### ISSUE THREAD

**Issue by kant712** [easy-swoole/easyswoole#185]
版本是3.1.18。错误是：
[2019-03-19 08:54:44][Notice][file:/app/easyswoole/vendor/easyswoole/easyswoole/src/Console/Module/Auth.php][line:29]Undefined index: USER
见图：
![image](https://user-images.githubusercontent.com/26453448/54573200-464a5500-4a26-11e9-93d9-0d9c374a52b5.png)

**Comment by kiss291323003** [comment]
console 配置项在新版本中，更新为以下格式：
'CONSOLE' => [
        'ENABLE' => true,
        'LISTEN_ADDRESS' => '127.0.0.1',
        'HOST' => '127.0.0.1',
        'PORT' => 9500,
        'USER'=>'root',
        'PASSWORD'=>'123456'
    ],
