### ISSUE TITLE
请问 easyswoole/mysqli 如何打印SQL日志

### ISSUE THREAD

**Issue by cw58665466** [easy-swoole/easyswoole#186]
我现在在使用了demo里MysqlPool的方式操作MySql，请问要在每次执行MySql操作自动在Log里记录sql语句，或者如何才能打印出每次执行的SQL语句？谢谢

**Comment by kiss291323003** [comment]
getLastQuery 或者是start trace 。请看文档谢谢

**Comment by Coding-Yuan** [comment]
> getLastQuery 或者是start trace 。请看文档谢谢

文档上没有关于mysql查询后实现自动打日志的实现，getLastQuery()需要自己重复添加代码

**Comment by Coding-Yuan** [comment]
> 我现在在使用了demo里MysqlPool的方式操作MySql，请问要在每次执行MySql操作自动在Log里记录sql语句，或者如何才能打印出每次执行的SQL语句？谢谢

继承mysqli，重写增、删、改、查、rawQuery这五个方法，并加入自己的hook方法。
对于mysql连接池也是这样。
