### ISSUE TITLE
getBody() 验证无效  版本 easy swoole     3.1.19-dev

### ISSUE THREAD

**Issue by libaipeng1314** [easy-swoole/easyswoole#188]
$content = $this->request()->getBody()->__toString();
        $raw_array = json_decode($content, true);
        $validate = new Validate();
        $validate->addColumn('version')->required('版本信息必填！')->lengthMin(1, '版本信息不正确');
        $validate->addColumn('platform')->required('设备名必填！')->lengthMin(2, '设备名不正确');
        if (!$this->validate($validate)) {
            return ['code' => BConst::RESONSE_ERROR_STATUS, 'msg' => $validate->getError()->__toString()];
        }

**Comment by kiss291323003** [comment]
无法理解你说的、、、、
