### ISSUE TITLE
Mysqli组件操作mycat数据库中间件有BUG

### ISSUE THREAD

**Issue by oyxp** [easy-swoole/easyswoole#190]
###  数据库配置：
![image](https://user-images.githubusercontent.com/15265910/56181099-abea2b00-603e-11e9-9dfd-9b2f8bad7edd.png)

### Http user控制器：
![image](https://user-images.githubusercontent.com/15265910/56181142-d3d98e80-603e-11e9-878d-0098efc148c7.png)

### 访问截图：
![image](https://user-images.githubusercontent.com/15265910/56184810-08087b80-604e-11e9-9afa-dcb0240b366f.png)

### 访问结果：
![image](https://user-images.githubusercontent.com/15265910/56184856-3d14ce00-604e-11e9-95e6-8b8ee1a4d4e1.png)

一会能拿到数据，一会不能。但是使用原生的mysqli_query每次都能拿到正确结果。

**Comment by oyxp** [comment]
描述下整个情况：
   我是用mac开发，连的是本地虚拟机。把`while true; do curl -XPOST -d 'username=snailzed' 'http://127.0.0.1:9501/user/login'; done;`  这个shell直接贴到终端运行，数据库连接的是mycat中间件（mycat配置没问题，我用swoft是正常连接操作数据库，没有发现这种问题），执行了user控制器这段代码，发现记录一会能拿到，一会拿不到。

**Comment by oyxp** [comment]
`getDb`这个方法代码：
![image](https://user-images.githubusercontent.com/15265910/56194482-aeac4680-6065-11e9-9bdc-df829dd28e1f.png)

用的是数据库连接池，`MysqlObject.php` `MysqlPool.php`文件内容都是从demo复制过来的
![image](https://user-images.githubusercontent.com/15265910/56194541-cbe11500-6065-11e9-85e2-7b1e5ec9ae5e.png)

**Comment by kiss291323003** [comment]
swoole版本多少。如果没有报错，而是null的话，那么这个不是框架层可以影响的。

**Comment by oyxp** [comment]
➜  ~ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 29 2019 16:09:52
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

#### 没有报错，返回的也是NULL，使用原生的mysqli_connect连接，再用mysqli_query去查询结果是正常的，每次都能拿到结果。这样看来，是这个库 https://github.com/ThingEngineer/PHP-MySQLi-Database-Class 的问题？

**Comment by kiss291323003** [comment]
你试着升级下swoole，然后用defer方法取链接去看看。https://github.com/easy-swoole/demo/tree/3.x-pool
。如果文件依旧，希望开放下mycat公网信息，给个测试账户，和可以复现的代码，我们坐下排除
