### ISSUE TITLE
jeremeamia/superclosure依赖大小写问题

### ISSUE THREAD

**Issue by php360** [easy-swoole/easyswoole#194]
依赖包中jeremeamia/SuperClosure 是大写，composer会提示采用小写的方式加载。
该项目的文档中也是小写。大写的写法将在composer2.0中报错

Deprecation warning: require.jeremeamia/SuperClosure is invalid, it should not contain uppercase characters. Please use jeremeamia/superclosure instead. Make sure you fix this as Composer 2.0 will error.

**Comment by kiss291323003** [comment]
感谢反馈，已经解决了
