### ISSUE TITLE
连接池报错，麻烦尽快修正：swoole_timer_tick() must be callable, array given

### ISSUE THREAD

**Issue by jadechenlei** [easy-swoole/easyswoole#199]
/vendor/easyswoole/component/src/Pool/AbstractPool.php][line:40]Argument 2 passed to Swoole\Timer::swoole_timer_tick() must be callable, array given

**Comment by kiss291323003** [comment]
这个是因为你正在用swoole 4.4.0-alpha版本的，请先降级到4.3.3谢谢
