### ISSUE TITLE
连接池设置最小连接数时一直报错setMinObjectNum

### ISSUE THREAD

**Issue by jadechenlei** [easy-swoole/easyswoole#201]
我的代码: `PoolManager::getInstance()->register(RedisPool::class, Config::getInstance()->getConf('redis.pool_max_num'))->setMinObjectNum(2);`

报错信息: `Fatal error: Uncaught Error: Call to a member function setMinObjectNum() on null in /www/swooleroot/babyMall/EasySwooleEvent.php:33`

**Comment by kiss291323003** [comment]
、、、、自己好好看最新的代码实现谢谢
