### ISSUE TITLE
匿名函数验证能否由回调函数中抛出MSG信息

### ISSUE THREAD

**Issue by jadechenlei** [easy-swoole/easyswoole#202]
> function func(callable $func, $msg = null)
    {
        $this->ruleMap['func'] = [
            'arg' => $func,
            'msg' => $msg
        ];
        return $this;
    }

$msg信息我无法在调用之前就确定, 必须在回调函数中根据情况来回报错误信息

**Comment by kiss291323003** [comment]
我懂你意思了，过几天解决
