### ISSUE TITLE
ServerManager里面能添加一个swoole_redis_server服务类型吗？

### ISSUE THREAD

**Issue by longit123** [easy-swoole/easyswoole#203]
看到swoole文档里面有这个[功能](https://wiki.swoole.com/wiki/page/671.html)

ServerManager里面只能创建三种服务类型(server，http_server和websocket_server)；

描述一下需求：因为业务开发用PHP5.6代码，不可能全部改造成swoole，但有些时候有性能瓶颈，我在想是不是可以考虑使用基于swoole_redis_server的服务，方便业务开发方直接传递数据到server的task进程里面进行处理，而不需要用http或者tcp之类的请求；

只是个建议而已。

**Comment by kiss291323003** [comment]
swoole_redis_server这个在未来，swoole有考虑废弃，因此不考虑实现支持

**Comment by longit123** [comment]
> swoole_redis_server这个在未来，swoole有考虑废弃，因此不考虑实现支持

[问了](https://github.com/swoole/swoole-src/issues/2576)作者，不知道easyswoole框架能不能添加，不能的话，只能自己改easyswoole框架了（只是以后升级不方便。。。）

**Comment by kiss291323003** [comment]
或者你加我QQ  291323003 ,我们沟通下吧，我可以给你做下简单的支持，你自己注册回调即可

**Comment by longit123** [comment]
我已经改好了，在EasySwooleEvent里面注册了onTask函数，只是还要改easyswoole框架ServerManager里面创建swoole服务，加了个 case EASYSWOOLE_REDIS_SERVER:

**Comment by longit123** [comment]
谢谢你啊，easyswoole挺好用的，我这里核心功能就是基于easyswoole，稳定运行了几个月^_^
