### ISSUE TITLE
麻烦问一下，3.1.19版本强制task使用协程

### ISSUE THREAD

**Issue by longit123** [easy-swoole/easyswoole#204]
我现在用的是3.1.18版本，因为项目组很多开发都不了解协程，普及也需要很长时间（不一定接受），而且很多应用，并不都是io密集型，只是单纯的业务跑超时而已（例如订单、财务之类的数据运算），大部分情况下用swoole改造成多进程就行。而且开发人员水平参差不齐，或者开发时间紧急的时候，遗漏连接池回收

比如，某段逻辑下，用了连接池回收，某段逻辑又忘了，造成非必现的情况（当然有defer之类方式的可以规避一些此类问题，但普及后，让其他人单独去开发，很多时候并不能完全保证）

如果3.1.19强制task使用协程，以后3.1.18的一些bug，怎么升级easyswoole？单独切一个版本？个人觉得是不是可以考虑还是使用之前配置驱动是否支持协程（当然协程是一个发展方向，但个人感觉并不适合所有场景）

**Comment by kiss291323003** [comment]
如果你不需要协程，就不要升级，再配置项关闭即可。另外。关于如何避免出现忘记回收等问题，可以参考问题，全部的pool都提供了defer和invoker方法
