### ISSUE TITLE
有计划支持GraphQL吗？

### ISSUE THREAD

**Issue by huanghantao** [easy-swoole/easyswoole#206]
请问一下，有计划支持GraphQL吗？

**Comment by kiss291323003** [comment]
框架支持，但是目前我们没有时间去写库来做支持维护，如果你有兴趣，我可以开个库给你

**Comment by kiss291323003** [comment]
https://github.com/easy-swoole/doc/blob/3.1.x/Manual/3.x/Cn/Other/GraphQL.md

**Comment by huanghantao** [comment]
欧克

**Comment by xuhaoxian** [comment]
直接引入graphQL官方推荐的库 就可以自己跟着文档写了
