### ISSUE TITLE
websocket close

### ISSUE THREAD

**Issue by GoodTimeer** [easy-swoole/easyswoole#207]
在项目使用 websocket 服务遇到一个费解的问题。
客户端意外断开 websocket链接后如：1，网络中断，2，iso推到后台，3，安卓/ios 用户主动杀死进程。 
$server->isEstablished($fd) 和 $server->exist($fd),都检测不到链接被关闭。
导致 $server->push($fd, $push_msg)，的数据丢失。有什么机制能快速检测到 websocket 被关闭，服务端针对被关闭的情况，保存数据呢。

**Comment by kiss291323003** [comment]
1、开启心跳周期检测
2、开启tcp keepalive
3、如果需要百分百可靠，可以自己实现一个回执机制

**Comment by GoodTimeer** [comment]
嗯，1，2，可靠还是差一些。
的确用回执处理了。
