### ISSUE TITLE
协程HttpClient问题

### ISSUE THREAD

**Issue by SimonZhangCN** [easy-swoole/easyswoole#208]
new一个HttpClient客户端出现如下报错
```
Class 'EasySwoole\HttpClient\HttpClient' not found
```
composer.json中的信息如下，http-client是后面后面引入的，并且重新生成了自动载入文件
```
{
    "autoload": {
        "psr-4": {
            "App\\": "App/"
        }
    },
    "require": {
        "easyswoole/easyswoole": "3.x",
        "easyswoole/verifycode": "^3.0",
        "phpmailer/phpmailer": "^6.0",
        "easyswoole/mysqli": "^1.1",
        "phpoffice/phpspreadsheet": "^1.6",
        "easyswoole/http-client": "^1.2"
    },
    "require-dev": {
        "swoole/ide-helper": "~4.3.3"
    }
}
```
在webStorm中代码都能正常跳转到HttpClient类，运行就一直报错。一直找不到原因

**Comment by xiaocaigua** [comment]
composer dump-autoload 试下




------------------ 原始邮件 ------------------
发件人: "simon"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 下午4:47
收件人: "easy-swoole/easyswoole"<easyswoole@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [easy-swoole/easyswoole] 协程HttpClient问题 (#208)




new一个HttpClient客户端出现如下报错
 Class 'EasySwoole\HttpClient\HttpClient' not found  
composer.json中的信息如下，http-client是后面后面引入的，并且重新生成了自动载入文件
 {     "autoload": {         "psr-4": {             "App\\": "App/"         }     },     "require": {         "easyswoole/easyswoole": "3.x",         "easyswoole/verifycode": "^3.0",         "phpmailer/phpmailer": "^6.0",         "easyswoole/mysqli": "^1.1",         "phpoffice/phpspreadsheet": "^1.6",         "easyswoole/http-client": "^1.2"     },     "require-dev": {         "swoole/ide-helper": "~4.3.3"     } }  
在webStorm中代码都能正常跳转到HttpClient类，运行就一直报错。一直找不到原因

**Comment by SimonZhangCN** [comment]
尝试了，无效

**Comment by SimonZhangCN** [comment]
把服务关闭再重启就可以了，产生这个问题的原因应该是vendor目录下面autoload.php在执行php easyswoole reload all后，其实进程是没有更新autoload.php文件的

**Comment by kiss291323003** [comment]
、、、、、、这个本身就是进程常驻的问题啊、、、开发者须知有
