### ISSUE TITLE
定时器crontab会出现task finish 只能在worker进程中使用

### ISSUE THREAD

**Issue by liuquanchang** [easy-swoole/easyswoole#209]
定时器crontab会出现task finish 只能在worker进程中使用，看了是继承QuickTaskInterface,但是QuickTaskInterface没有实现finish!
![image](https://user-images.githubusercontent.com/13381669/59437539-5bb3fd00-8e24-11e9-951d-ae8a8001b710.png)

**Comment by kiss291323003** [comment]
你升级swoole 到4.4.0，然后执行composer up即可
