### ISSUE TITLE
协程设置

### ISSUE THREAD

**Issue by GoodTimeer** [easy-swoole/easyswoole#213]
你好，在项目中用到协程，出现这个：

[DEBUG][WARNING] : [go(): exceed max number of coroutine 3000。
@
想问下，服务启动的时候，哪里设置协程吗

**Comment by kiss291323003** [comment]
在配置项的setting中，设置最大携程数目，对了，还可以升级下sw版本

**Comment by GoodTimeer** [comment]
我是在协程启动时候，动态设置。
\Swoole\Coroutine::set([
      'max_coroutine' => 40960,
    ]);，

想知道是配置文件哪个key 可以设置呢。 也是'max_coroutine ' 吗 
 'SETTING'        => [ 
      'worker_num'            => 8,
      'task_worker_num'       => 5000,
      'reload_async'          => false,
      'task_enable_coroutine' => true,
      'task_max_request'      => 4000,
      'max_wait_time'         => 5,
    ],

**Comment by GoodTimeer** [comment]
> 在配置项的setting中，设置最大携程数目，对了，还可以升级下sw版本

我是在协程启动时候，动态设置。
\Swoole\Coroutine::set([
'max_coroutine' => 40960,
]);，

想知道是配置文件哪个key 可以设置呢。 也是'max_coroutine ' 吗
'SETTING' => [
'worker_num' => 8,
'task_worker_num' => 5000,
'reload_async' => false,
'task_enable_coroutine' => true,
'task_max_request' => 4000,
'max_wait_time' => 5,
],
