### ISSUE TITLE
异步任务，直接投递闭包，没有finish回调。

### ISSUE THREAD

**Issue by smallsung** [easy-swoole/easyswoole#214]
"ext-swoole": "4.3.0",
const EASYSWOOLE_VERSION = '3.1.14';

![image](https://user-images.githubusercontent.com/7710878/60550550-f7b59200-9d5a-11e9-9dac-e37854e7dfef.png)
![image](https://user-images.githubusercontent.com/7710878/60550592-13209d00-9d5b-11e9-8e87-6fb286fa2480.png)

**Comment by kiss291323003** [comment]
swoole请先升级到4.4.0，然后升级easyswoole
