### ISSUE TITLE
根据 dockerfile 拉取服务，报错

### ISSUE THREAD

**Issue by xianqiangzhao** [easy-swoole/easyswoole#217]
根据https://github.com/easy-swoole/easyswoole 中的DockerFile建立docker 镜像报错。
 - easyswoole/easyswoole 3.x-dev requires ext-swoole >=4.3.0 -> the requested PHP extension swoole has the wrong version (4.2.13) installed.

**Comment by xiaocaigua** [comment]
修改docker的swoole版本到4.3.0以上


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zhaoxianqiang <notifications@github.com>
发送时间: 2019年7月8日 14:31
收件人: easy-swoole/easyswoole <easyswoole@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[easy-swoole/easyswoole] 根据 dockerfile 拉取服务，报错 (#217)




根据https://github.com/easy-swoole/easyswoole 中的DockerFile建立docker 镜像报错。
  
easyswoole/easyswoole 3.x-dev requires ext-swoole >=4.3.0 -> the requested PHP extension swoole has the wrong version (4.2.13) installed.

**Comment by xianqiangzhao** [comment]
ok了,谢谢！
