### ISSUE TITLE
关于mysqli组件的一个小建议

### ISSUE THREAD

**Issue by SimonZhangCN** [easy-swoole/easyswoole#219]
实际使用中遇到一个数据导出的需求（投递任务到TaskWorker进程处理），需要从数据表中导出大量数据到Excel表，分页查询数据（会查询很多次），写入到Excel，每次查询完数据后，mysqli类会执行`resetDbStatus()`方法，所以不得不每次查询完再条件一次查询条件。希望能提供一个可配置的方式，让我自己决定是否执行resetDbStatus()方法。

**Comment by kiss291323003** [comment]
你可以用get client。就是直接获取当前的 mysql实例，直接去raw query
