### ISSUE TITLE
协程mysql 执行比较长的语句出错

### ISSUE THREAD

**Issue by xuhaoxian** [easy-swoole/easyswoole#221]
在协程mysql执行一条很长的语句  出错    
报错显示在prepare出现问题   但是$this->coroutineMysqlClient->error没有显示错误
[[超长消息]UPDATE ad_a.pdf](https://github.com/easy-swoole/easyswoole/files/3416003/UPDATE.ad_a.pdf)

**Comment by kiss291323003** [comment]
升级swoole 到4.4.1即可
