### ISSUE TITLE
php 7.3.8 swoole4.4.3 easyswoole3.2.6 异步投递任务报错

### ISSUE THREAD

**Issue by netstao** [easy-swoole/easyswoole#224]
[2019-08-09 17:48:10][DEBUG][ERROR] : [Uncaught TypeError: Argument 2 passed to EasySwoole\EasySwoole\Core::EasySwoole\EasySwoole\{closure}() must be an instance of Swoole\Server\Task, int given in /data/wwwroot/tzhh-api/vendor/easyswoole/easyswoole/src/Core.php:269
Stack trace:
#0 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}(Object(Swoole\Http\Server), 0, 2, Object(App\Task\OssTask))
#1 /data/wwwroot/tzhh-api/vendor/easyswoole/easyswoole/src/ServerManager.php(120): Swoole\Server->start()
#2 /data/wwwroot/tzhh-api/vendor/easyswoole/easyswoole/src/Core.php(132): EasySwoole\EasySwoole\ServerManager->start()
#3 /data/wwwroot/tzhh-api/vendor/easyswoole/easyswoole/src/Command/DefaultCommand/Start.php(106): EasySwoole\EasySwoole\Core->start()
#4 /data/wwwroot/tzhh-api/vendor/easyswoole/easyswoole/src/Command/CommandContainer.php(46): EasySwoole\EasySwoole\Command\DefaultCommand\Start->exec(Array)
#5 /data/wwwroot/tzhh-api/vendor/easyswoole/easyswoole/src/Command/CommandRunner.php(50): EasySwoole\EasySwoole\Command\Com at file:/data/wwwroot/tzhh-api/vendor/easyswoole/easyswoole/src/Core.php line:269]
swoole version                4.4.3
php version                   7.3.8
easy swoole                   3.2.6

**Comment by kiss291323003** [comment]
配置项修改为如下：
```php
 'SETTING' => [
            'worker_num' => 8,
            'task_worker_num' => 8,
            'reload_async' => true,
            'task_enable_coroutine' => true,
            'max_wait_time'=>3
        ]
```

重点在  task_enable_coroutine 这个配置

**Comment by netstao** [comment]
tks 已经在官网找到了
