### ISSUE TITLE
php7.3.8 swoole4.4.3 easyswoole3.2.6 websocket onMessage 事件下报错

### ISSUE THREAD

**Issue by netstao** [easy-swoole/easyswoole#226]
main server                   SWOOLE_WEB_SOCKET
swoole version                4.4.3
php version                   7.3.8
easy swoole                   3.2.6

服务器配置开启了

'SERVER_TYPE'    => EASYSWOOLE_WEB_SOCKET_SERVER, 
 SETTING  => [
          'reload_async' => true,
            'max_wait_time'=>3,
            'daemonize'=>1,
            'task_enable_coroutine' => true,
]

[2019-08-16 17:13:38][DEBUG][ERROR] : [Uncaught TypeError: Argument 1 passed to EasySwoole\EasySwoole\EasySwooleEvent::EasySwoole\EasySwoole\{closure}() must be an instance of EasySwoole\EasySwoole\swoole_server, instance of Swoole\WebSocket\Server given in /data/wwwroot/dev-tzhh-api/EasySwooleEvent.php:64
Stack trace:
#0 [internal function]: EasySwoole\EasySwoole\EasySwooleEvent::EasySwoole\EasySwoole\{closure}(Object(Swoole\WebSocket\Server), Object(Swoole\WebSocket\Frame))
#1 /data/wwwroot/dev-tzhh-api/vendor/easyswoole/easyswoole/src/ServerManager.php(114): call_user_func(Object(Closure), Object(Swoole\WebSocket\Server), Object(Swoole\WebSocket\Frame))
#2 {main}
  thrown at file:/data/wwwroot/dev-tzhh-api/EasySwooleEvent.php line:64]

![image](https://user-images.githubusercontent.com/2988231/63157688-11304600-c04a-11e9-8f2e-5dd44a8ef3b2.png)

**Comment by kiss291323003** [comment]
兄弟、、、你i自己名称空间错了、、、、是\swoole_server，而不是swoole_server

**Comment by netstao** [comment]
@kiss291323003  在你的demo-chat 里面copy的 😢

**Comment by netstao** [comment]
失误
