### ISSUE TITLE
发现部分php文件不被opcache缓存

### ISSUE THREAD

**Issue by skyjust** [easy-swoole/easyswoole#228]
追查发现 在start命令的方法中 public function exec(array $args): ?string
第一句Utility::opCacheClear(); 做了opcode的重置工作，导致之后加载的某些php文件(ServerManager)无法被缓存到opcache中，不知道是否是php的opcache扩展出了问题。但我并没有明白为什么要在start的时候 要做这个重置工作，想请教是否可以屏蔽。
环境是php7.3.x

**Comment by kiss291323003** [comment]
swoole下没必要opcache
