### ISSUE TITLE
mainServerCreate 事件中 这一句代码导致 php easyswoole stop 无法正常stop 必须加 force  但是提示stop server fail.try -f again  不太一致

### ISSUE THREAD

**Issue by netstao** [easy-swoole/easyswoole#230]
Redis::getInstance()->register('OrderQueue',new \EasySwoole\RedisPool\Config());

  $driver = new \EasySwoole\Queue\Driver\Redis('OrderQueue','OrderQueue'); //主要是这一句导致 php easyswoole stop 必须 加force 强制kill   手动加 -9 才能停掉所有进程

OrderQueue::getInstance($driver);

**Comment by kiss291323003** [comment]
升级swoole版本到4.4.4或以上版本即可解决。

**Comment by netstao** [comment]
> 升级swoole版本到4.4.4或以上版本即可解决。

swoole version                4.4.4
php version                   7.3.8
easy swoole                   3.2.6
已经是 4.4.4 @kiss291323003
