### ISSUE TITLE
有考虑 支持 pulsar 消息队列吗？

### ISSUE THREAD

**Issue by netstao** [easy-swoole/easyswoole#231]
pulsar

线性扩展。能够丝滑的扩容到成百上千个节点(Kafka扩容需要占用很多系统资源在节点间拷贝数据，而Plusar完全不用)

高吞吐。已经在Yahoo的生产环境中经受了考验，每秒数百万消息

低延迟。在大规模的消息量下依然能够保持低延迟(< 5ms)

持久化机制。Plusar的持久化机制构建在Apache BookKeeper之上，提供了写与读之前的IO隔离

**Comment by kiss291323003** [comment]
这个请用自定义进程自行实现
