### ISSUE TITLE
运行一段时间报Swoole\Coroutine\Redis::__construct(): constructor can only be called once

### ISSUE THREAD

**Issue by lizz89** [easy-swoole/easyswoole#234]
[Swoole\Coroutine\Redis::__construct(): constructor can only be called once at file:/tmp/Ce6O0MFbaXPKwLArs.php line:10]

**Comment by netstao** [comment]
我也是 环境如下

swoole version 4.4.4
php version 7.3.8
easy swoole 3.2.6

**Comment by netstao** [comment]
@lizz89  升级到4.4.5-alpha 可解决 已测试
