### ISSUE TITLE
建表工具生成的默认值会有问题

### ISSUE THREAD

**Issue by chreun** [easy-swoole/easyswoole#240]
如timestamp 默认值为 now()  会被当成字符串默认包上 ''
int 为 0 会被丢弃

**Comment by evalor** [comment]
已修复该问题，请升级到v1.0.1，当需要默认值为方法时，请向setDefaultValue方法传一个Func对象，详见[DDL v1.0.1]https://github.com/easy-swoole/ddl/releases/tag/1.0.1
