### ISSUE TITLE
项目跟目录下出现 core.xxxx 的文件

### ISSUE THREAD

**Issue by GoodTimeer** [easy-swoole/easyswoole#241]
用 websockt 协程 给群组其他成员推送信息。总有些消息到达不了客户端。

而且项目根目录下出现 core.xxxx 的文件。 / 也有类似文件

想问下大大，什么原因呢。

![image](https://user-images.githubusercontent.com/48427204/65438866-ca0f4f00-de58-11e9-9308-d9dac365dee0.png)

swoole Version => 4.4.3
EasySwoole   3.2.3

**Comment by kiss291323003** [comment]
这是出现coredump了，一般是swoole拓展问题。请更新sw到4.4.6版本

**Comment by GoodTimeer** [comment]
好的，谢谢大佬

**Comment by GoodTimeer** [comment]
但是sw 扩展升级到 4.4.7-alpha，还是会出现呢

**Comment by GoodTimeer** [comment]
尝试了一下gdb，有这些信息。linux编程能力有限，分析不出原因。肯定大佬指点

![image](https://user-images.githubusercontent.com/48427204/65656433-6ea8b100-e052-11e9-83fa-f2e424ab2f3d.png)

**Comment by xuanyanwow** [comment]
麻烦提供一下最小复现问题的代码，

**Comment by GoodTimeer** [comment]
> 麻烦提供一下最小复现问题的代码，

你好，现在头疼的是，不知道哪段代码导致的。
