### ISSUE TITLE
PHP Fatal error:  Declaration of EasySwoole\EasySwoole\Logger::log

### ISSUE THREAD

**Issue by coleflowers** [easy-swoole/easyswoole#243]
`mkdir a`
`cd a`
`composer require easyswoole/easyswoole=3.x`
`php vendor/bin/easyswoole install`
报错：Could not open input file: vendor/bin/easyswoole

`php vendor/bin/easyswoole.php install ` 
显示：install success

`php easyswoole start`
报错：PHP Fatal error:  Declaration of EasySwoole\EasySwoole\Logger::log(string $str, $category = 'default') must be compatible with EasySwoole\Trace\AbstractInterface\LoggerInterface::log` ……

环境：
PHP version => 7.1.23 (cli) 
swoole Version => 4.2.3
OS => Darwin

**Comment by kiss291323003** [comment]
sw版本太低了。es现在要求最低4.4.5起步。然后换下阿里云composer镜像

**Comment by coleflowers** [comment]
谢谢，问题已通过两个方向解决了，低版本的修改了两处代码跑起来了！新加了easyswoole/mysqli提示升阶swoole，升级swoole后没发现这个问题。

建议对版本有要求的模块进行版本检测并给出提示。
