### ISSUE TITLE
可以给自动生成的控制器加全局的前缀吗？

### ISSUE THREAD

**Issue by bibiuc** [easy-swoole/easyswoole#245]
或者说通过ng怎么实现两个程序，前缀不同。
/v1->proxy
/v2->proxy

**Comment by LuffyQAQ** [comment]
> 或者说通过纳克怎么实现两个程序，前缀不同。
> / V1->代理
> / V2->代理

EasySwoole 没有自动生成控制器，请问你说的是哪个地方？
