### ISSUE TITLE
关于RedisPool使用时 常出现pool is empty的异常情况

### ISSUE THREAD

**Issue by darifo** [easy-swoole/easyswoole#246]
程序运行一段时间后，连接池为空

**Comment by LuffyQAQ** [comment]
> 程序运行重新后，连接池为空

？

**Comment by darifo** [comment]
就是正常运行了一段时间后。会出现Redis连接池为空的情况

**Comment by LuffyQAQ** [comment]
> 就是正常运行了削减后。会出现Redis连接池为空的情况

请自己对比着文档看下自己的代码，看下是哪里出现用完连接没有回收的情况

**Comment by darifo** [comment]
> > 就是正常运行了削减后。会出现Redis连接池为空的情况
> 
> 请自己对比着文档看下自己的代码，看下是哪里出现用完连接没有回收的情况

这是我的定义和使用：

class RedisPool extends AbstractPool
{
    /**
     * 创建redis连接池对象
     * @return RedisObject|null
     */
    protected function createObject()
    {
        // TODO: Implement createObject() method.
        if (!extension_loaded('redis')) {
            throw new \BadFunctionCallException('not support: redis');
        }
        $conf = Config::getInstance()->getConf('REDIS');
        $redis = new RedisObject();
        $connected = $redis->connect($conf['host'], $conf['port']);
        if ($connected) {
            if (!empty($conf['auth'])) {
                $redis->auth($conf['auth']);
            }
            //选择数据库,默认为0
            if (!empty($conf['db'])) {
                $redis->select($conf['db']);
            }
            return $redis;
        } else {
            return null;
        }
    }
}

class RedisObject extends Redis implements PoolObjectInterface
{
    public function gc()
    {
        // TODO: Implement gc() method.
        $this->close();
    }

    public function objectRestore()
    {
        // TODO: Implement objectRestore() method.
    }

    public function beforeUse(): bool
    {
        // TODO: Implement beforeUse() method.
        return true;
    }
}

使用：

$redis = RedisPool::defer();

这个方式，不是就不用手动回收吗？

**Comment by kiss291323003** [comment]
首先，pool为空，两种情况，一种是用了忘记回收，一种是并发量高过pool承载量

**Comment by darifo** [comment]
> 首先，pool为空，两种情况，一种是用了忘记回收，一种是并发量高过pool承载量

行，我再查一下具体原因。感谢回复！
