### ISSUE TITLE
easyswoole 3.3.0 和 easyswoole 3.2.6 的websocket组件有什么区别吗

### ISSUE THREAD

**Issue by hejiaqiang1980** [easy-swoole/easyswoole#254]
easyswoole 3.2.6下 直接用官网的关于websocket代码 正常连接 正常发送返回消息
easyswoole 3.3.0下 也是直接用官网的关于websocket代码 正常连接 服务器推送消息时候报错 

socket.js:69 WebSocket connection to 'ws://192.168.142.128:9501/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 0

上面直接是用官网websocket测试工具

开发环境是虚拟机 与主机共享文件夹

刚开始用easyswoole 不想就这样放弃

**Comment by LuffyQAQ** [comment]
> easyswoole 3.2.6下 直接用官网的关于websocket代码 正常连接 正常发送返回消息
> easyswoole 3.3.0下 也是直接用官网的关于websocket代码 正常连接 服务器推送消息时候报错
> 
> socket.js:69 WebSocket connection to 'ws://192.168.142.128:9501/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 0
> 
> 上面直接是用官网websocket测试工具
> 
> 开发环境是虚拟机 与主机共享文件夹
> 
> 刚开始用easyswoole 不想就这样放弃

你好，我们这边在加你反馈之后，3.2.6和3.3.0都测试了一下，没有问题的，请问您这边swoole版本是多少，有可能是swoole版本的问题哦

**Comment by hejiaqiang1980** [comment]
main server                   SWOOLE_WEB_SOCKET
listen address                0.0.0.0
listen port                   9501
ip@ens33                      192.168.142.128
ip@virbr0                     192.168.122.1
worker_num                    8
reload_async                  1
max_wait_time                 3
pid_file                      /www/wwwroot/wechat_script_temp/pid.pid
log_file                      /mnt/hgfs/web/wechat_script/Log/swoole.log
run at user                   root
daemonize                     false
swoole version                4.4.9
php version                   7.2.21
easy swoole                   3.3.0
develop/produce               develop
temp dir                      /www/wwwroot/wechat_script_temp
log dir                       /mnt/hgfs/web/wechat_script/Log

**Comment by LuffyQAQ** [comment]
你先降到4.4.8跑下试试，我们刚才跑的是4.4.8

**Comment by hejiaqiang1980** [comment]
确实是swoole版本问题 4.4.8 下没问题了

不过 3.2.6 在 swoole 4.4.9下是 OK 的

**Comment by LuffyQAQ** [comment]
> 确实是swoole版本问题 4.4.8 下没问题了
> 
> 不过 3.2.6 在 swoole 4.4.9下是 OK 的

嗯嗯，好的，我们这边反馈一下
