### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by YangGuu** [easy-swoole/easyswoole#261]
[2019-11-29 01:31:23 @2180.0]   WARNING swServer_start_check: serv->max_connection must be bigger than 2096, it's reset to 1024
PHP Fatal error:  Swoole\Server::start(): failed to start server. Error: swFactoryProcess_start: swFactoryProcess_manager_start failed in /www/swoole_server/vendor/easyswoole/easyswoole/src/ServerManager.php on line 114

Fatal error: Swoole\Server::start(): failed to start server. Error: swFactoryProcess_start: swFactoryProcess_manager_start failed in /www/swoole_server/vendor/easyswoole/easyswoole/src/ServerManager.php on line 114
PHP Fatal error:  Uncaught Error: Class 'EasySwoole\Trigger\Location' not found in /www/swoole_server/vendor/easyswoole/easyswoole/src/Core.php:194
Stack trace:
#0 /www/swoole_server/vendor/composer/ClassLoader.php(444): EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}(2, 'include(/www/sw...', '/www/swoole_ser...', 444, Array)
#1 /www/swoole_server/vendor/composer/ClassLoader.php(444): include()
#2 /www/swoole_server/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/swoole_ser...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('EasySwoole\\Trig...')
#4 /www/swoole_server/vendor/easyswoole/easyswoole/src/Core.php(207): spl_autoload_call('EasySwoole\\Trig...')
#5 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}()
#6 {main}
  thrown in /www/swoole_server/vendor/easyswoole/easyswoole/src/Core.php on line 194

Fatal error: Uncaught Error: Class 'EasySwoole\Trigger\Location' not found in /www/swoole_server/vendor/easyswoole/easyswoole/src/Core.php:194
Stack trace:
#0 /www/swoole_server/vendor/composer/ClassLoader.php(444): EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}(2, 'include(/www/sw...', '/www/swoole_ser...', 444, Array)
#1 /www/swoole_server/vendor/composer/ClassLoader.php(444): include()
#2 /www/swoole_server/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/swoole_ser...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('EasySwoole\\Trig...')
#4 /www/swoole_server/vendor/easyswoole/easyswoole/src/Core.php(207): spl_autoload_call('EasySwoole\\Trig...')
#5 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}()
#6 {main}
  thrown in /www/swoole_server/vendor/easyswoole/easyswoole/src/Core.php on line 194

**Comment by xwzmsdqbjzyyg** [comment]
这个问题怎么解决的呢

**Comment by karp90000** [comment]
?
