### ISSUE TITLE
orm 安装有问题

### ISSUE THREAD

**Issue by CZHIC** [easy-swoole/easyswoole#269]
当我没有安装mysqli 组件的时候，直接composer require  easyswoole/orm ，会自动安装easyswoole/mysqli(2.1.2) 的组件，但是在使用orm的时候会报错   [Uncaught Error: Class 'EasySwoole\Mysqli\QueryBuilder' not found in.....

于是我删除了orm组件和mysqli组件，先安装mysqli  ，然后在安装orm组件，这样就是正常的。

不知道是我个人的问题还是确实安装的时候会有这个问题，大佬们有空看看。

**Comment by kiss291323003** [comment]
是你的composer.lock冲突了
