### ISSUE TITLE
如何在Task业务代码中获取TaskWorkerId？

### ISSUE THREAD

**Issue by Sunshine40** [easy-swoole/easyswoole#271]
我是指，除了通过Task回调传入参数的形式，预期是类似于这样：
ServerManager::getInstance()->getSwooleServer()->worker_id
在任何业务逻辑直接通过全局的方式获得，而不是一层层传递这个参数。

我知道可以手动在每一个Task回调入口处注入一个Di项，但不知道有没有更“优雅”的用法？不知道我有没有看漏文档，还是设计上本来就没有提供这样一个全局获取TaskWorkerId的方法。

**Comment by kiss291323003** [comment]
你是哪个版本的easyswoole？
