### ISSUE TITLE
Call to a member function send() on null at vendor/easyswoole/redis/src/Redis.php line:2145

### ISSUE THREAD

**Issue by coding-lover** [easy-swoole/easyswoole#275]
http method:
`
public function testPipe()
    {
        $ret = \EasySwoole\RedisPool\Redis::invoker(REDIS_POOL_NAME, function(\EasySwoole\Redis\Redis $redisPool) {

            $redisPool->startPipe();
            for($i = 0; $i < 10; $i++)
            {
                $ret = $redisPool->set($i, $i);
                var_dump($ret);
            }

            return $redisPool->execPipe();
        });

        var_dump($ret);
    }
`

exception:
Call to a member function send() on null
#0 /data/www/kit/swoole/Fun/HttpController/Index.php(1702): EasySwoole\Redis\Redis->execPipe()
#1 [internal function]: Fun\HttpController\Index->Fun\HttpController\{closure}(Object(EasySwoole\Redis\Redis))
#2 /data/www/kit/vendor/easyswoole/pool/src/AbstractPool.php(339): call_user_func(Object(Closure), Object(EasySwoole\Redis\Redis))
#3 /data/www/kit/vendor/easyswoole/redis-pool/src/Redis.php(52): EasySwoole\Pool\AbstractPool->invoke(Object(Closure), NULL)
#4 /data/www/kit/swoole/Fun/HttpController/Index.php(1703): EasySwoole\RedisPool\Redis::invoker('redis', Object(Closure))
#5 /data/www/kit/vendor/easyswoole/http/src/AbstractInterface/AnnotationController.php(168): Fun\HttpController\Index->testPipe()
#6 [internal function]: EasySwoole\Http\AbstractInterface\AnnotationController->EasySwoole\Http\AbstractInterface\{closure}()
#7 /data/www/kit/vendor/easyswoole/http/src/AbstractInterface/Controller.php(113): call_user_func(Object(Closure))
#8 /data/www/kit/vendor/easyswoole/http/src/AbstractInterface/AnnotationController.php(171): EasySwoole\Http\AbstractInterface\Controller->__hook('testPipe', Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response), Object(Closure))
#9 /data/www/kit/vendor/easyswoole/http/src/Dispatcher.php(182): EasySwoole\Http\AbstractInterface\AnnotationController->__hook('testPipe', Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response))
#10 /data/www/kit/vendor/easyswoole/http/src/Dispatcher.php(137): EasySwoole\Http\Dispatcher->controllerHandler(Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response), '/testPipe')
#11 /data/www/kit/vendor/easyswoole/easyswoole/src/Core.php(254): EasySwoole\Http\Dispatcher->dispatch(Object(EasySwoole\Http\Request), Object(EasySwoole\Http\Response))
#12 {main}

**Comment by kiss291323003** [comment]
这是你连接池没有回收导致的。连接池需要回收，或者是池空了的时候需要降级处理

**Comment by coding-lover** [comment]
`public function testPipe()
    {
        $redisObj = \EasySwoole\RedisPool\Redis::getInstance()->get(REDIS_POOL_NAME);
        $redisPool = $redisObj->getObj();

        $redisPool->startPipe();
        for($i = 0; $i < 10; $i++)
        {
            $ret = $redisPool->set($i, $i);
            var_dump($ret);
        }

        $ret = $redisPool->execPipe();

        //回收
        $redisObj->recycleObj($redisPool);

        var_dump($ret);

    }`

httpController 里面的一个方法， 还是出现上面的错误；
大佬，有没有相关的 demo 呀？

**Comment by coding-lover** [comment]
![image](https://user-images.githubusercontent.com/9207532/72681924-377b7580-3b03-11ea-819f-6b6ca62774b6.png)

代码里应该是有BUG吧，在 startPipe 之前一定要 先调用 redis 其实命令，才会调用 connect, 才会实例化client, 否则这个 client 是 null
