### ISSUE TITLE
弱弱的问一句，这个项目还会更新吗。或者说还会基于swoole吗

### ISSUE THREAD

**Issue by tracenull** [easy-swoole/easyswoole#280]

**Comment by LuffyQAQ** [comment]
项目会一直更新的，放心使用

**Comment by tracenull** [comment]
> 项目会一直更新的，放心使用

我看网上说es和swoole团队决裂了，es后面的更新不再用swoole了。我们公司有个项目es的，这样的话，是不是会出大事

**Comment by LuffyQAQ** [comment]
> > 项目会一直更新的，放心使用
> 
> 我看网上说es和swoole团队决裂了，es后面的更新不再用swoole了。我们公司有个项目es的，这样的话，是不是会出大事

请放心使用，作者并没有说不会使用swoole

**Comment by tracenull** [comment]
> > > 项目会一直更新的，放心使用
> > 
> > 
> > 我看网上说es和swoole团队决裂了，es后面的更新不再用swoole了。我们公司有个项目es的，这样的话，是不是会出大事
> 
> 请放心使用，作者并没有说不会使用swoole

嗯嗯 ，这种结果最好。

**Comment by lubingzy** [comment]
用hyperf框架，这是swoole团队做的！
