### ISSUE TITLE
orm update 数据不变动提交时 sql 报错

### ISSUE THREAD

**Issue by ftlh2005** [easy-swoole/easyswoole#283]
提交内容和数据原内容一至就会提示这个错误

错误提示：
`[2020-02-02 15:27:39][DEBUG][ERROR] : [SQLSTATE[42000] [1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE  u_id = ?' at line 1 at file:/www/wwwroot/easadmin.cross.echosite.cn/vendor/easyswoole/orm/src/Db/MysqliClient.php line:60]`

`$param = $this->request()->getRequestParam();
        $model = new UserModel();
        $info  = $model->get(['u_id' => $param['id']]);
        if (empty($info)) {
            $this->writeJson(Status::CODE_BAD_REQUEST, [], '该数据不存在');
            return FALSE;
        }
        $updateData = [
            'u_account' => $param['u_account'],
            'u_name'    => $param['u_name'],
        ];
        if (isset($param['u_password'])) $updateData['u_password'] = md5($param['u_password']);
        
        $rs = $info->update($updateData);
        if ($rs) {
            $this->writeJson(Status::CODE_OK, $rs, "编辑成功");
        } else {
            $this->writeJson(Status::CODE_BAD_REQUEST, [], $model->lastQueryResult()->getLastError());
 }`
`DROP TABLE IF EXISTS `eas_users`;
CREATE TABLE `eas_users` (
  `u_id` int(11) NOT NULL AUTO_INCREMENT,
  `u_password` varchar(32) NOT NULL DEFAULT 'e10adc3949ba59abbe56e057f20f883e' COMMENT '用户密码',
  `u_name` varchar(32) NOT NULL DEFAULT '' COMMENT '用户名',
  `u_account` varchar(32) NOT NULL COMMENT '用户登录名',
  `p_u_id` varchar(10) NOT NULL DEFAULT '' COMMENT '上级u_id',
  `role_id` varchar(255) NOT NULL,
  `u_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '用户状态 -1删除 0禁用 1正常',
  `u_level_line` varchar(100) NOT NULL DEFAULT '0-' COMMENT '用户层级链',
  `last_login_ip` varchar(20) NOT NULL DEFAULT '0' COMMENT '最后登录IP',
  `last_login_time` int(11) NOT NULL DEFAULT '0' COMMENT '最后登录时间',
  `create_time` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `u_auth` varchar(255) NOT NULL,
  PRIMARY KEY (`u_id`) USING BTREE,
  UNIQUE KEY `u_id` (`u_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户表';
`

**Comment by kiss291323003** [comment]
好的，感谢反馈

**Comment by xuanyanwow** [comment]
```php
	$user = UserModel::create();
    	$user->area_id = 2;
    	$user->name = 'test';
    	$id = $user->save();
    	
    	$user = UserModel::create()->get($id);
    	$res = $user->update([
    		'name'=>'test'
    		]);
    	
        $this->response()->write($res !== false ? 'yes' : 'no');
```


测试数据不变动并不会报错，报错可能是别的原因导致，打印完整SQL分析，如果有其他源码问题继续提交
