### ISSUE TITLE
使用easyswoole框架自带redis连接池压测报错

### ISSUE THREAD

**Issue by linlinsiy** [easy-swoole/easyswoole#284]
使用easyswoole框架利用协程tcp客户端建立的redis连接池时，压测时从协程通道里面获取连接失败，获取对象超时。有几个问题：
1.在测试环境和生产环境中，生产环境更容易出问题。目前看来两个环境的区别是redis集群节点生产环境更多
2.我设置了连接池的最小连接数，但是查看连接发现并没有按照最小连接数保留一定数量的establish的连接，而是有许多timewait的连接，并且定时会刷新连接，看了代码应该是AbstractPool的keepMin函数里面做的，不知道这么做的意义是什么，timewait的连接不还是断了的连接吗？
3.压测期间发现建立的连接总数（establish）是集群节点数量的10倍或20倍
4.发现框架中虽然有处理redis集群发挥的moved指令的方法（查询数据在另一个节点），但是并没有被调用过。之前我自己通过swoole提供的redis客户端写了个连接池发现只要有moved的数据，都会进行连接断连重连，请问您是怎么处理这个问题的。
以上，redis问题困扰很久了，望解答，感谢

**Comment by kiss291323003** [comment]
这边我安排人处理

**Comment by kiss291323003** [comment]
另外，超时的话，你应该是优化连接池，或者是用invoker模式

**Comment by tioncico** [comment]
1:并发下出现获取连接失败,这个是正常的,你需要优化连接池数量,这个是对redis最大连接数的一个限制,取不到连接意味着你的连接已经达到了限制  通过加大连接池数量或者调整超时机制,或者改为invoke模式快速释放连接解决
2:为了避免redis连接超时,我们连接池组件增加了对空闲连接的回收机制,当某个连接空闲太长时间,会自动关闭该连接. 
同时,为了使得高并发下能尽快的获取连接,我们有keepmin机制,这样可以保证在突然之间并发下,需要重新连接redis的耗时问题  
你说的没有按照最小连接数,那实际数量是什么呢?这边要注意一点,  实际最小连接数=最小连接数*worker进程数,假设你设置5,进程数为8,实际连接为5乘以8=40 
timewait 在回收机制中产生,只要是主动关闭连接,都会出现timewait,这是内核对连接的回收而产生的状态
3:同样的,实际连接数量=配置连接数量*worker进程数,在集群下,每个节点都需要一个连接维护,所以就成了你说的10-20倍多
4:这个是redis集群的协议知识点,当A节点访问B节点内容时,会出现move的结果返回,这个时候理论上是需要转移的,我们的redis前期版本也是这样处理的
但是,这样会出现一个问题,每次操作不同key,都会有一次额外的连接消耗(查询A一次,再查询B一次),
通过redis的节点分配原理,我们通过hash($key)取模16384(槽数量),获得实际所在槽,并进行了缓存节点->槽对应关系,这样,我只需要本地获得槽位,再根据槽位直接找到对应节点,就可以执行redis命令,操作key,可以节省一次连接时间,详细代码在:
https://github.com/easy-swoole/redis/blob/master/src/CrcHash.php
https://github.com/easy-swoole/redis/blob/master/src/CommandHandel/AbstractCommandHandel.php 第134行

最后感谢你对es  redis的认可,欢迎使用es
