### ISSUE TITLE
ORM 1.4.0在查询同时带有sum()和count()的计算的数据时，将结果toArray后丢失count数据

### ISSUE THREAD

**Issue by yaoyinbear** [easy-swoole/easyswoole#290]
Swoole version: 4.4.15
EasySwoole version: 3.3.4
ORM version: 1.4.0

```
CREATE TABLE `magicbook_statistics` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `openDate` date NOT NULL DEFAULT '1970-01-01',
  `zone` smallint(5) unsigned NOT NULL DEFAULT '0',
  `playerID` bigint(20) unsigned NOT NULL,
  `consumeMoney10001` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的钻石',
  `consumeMoney10010` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的金币',
  PRIMARY KEY (`id`),
  UNIQUE KEY `openDate` (`openDate`,`playerID`),
  KEY `openDate_2` (`openDate`,`zone`)
) ENGINE=InnoDB
```
```
$model = MagicBookStatisticsModel::create();
$total = $model->where('openDate', $queryOpenDate)
            ->where('zone', $zoneArray, 'IN')
            ->field([
                'count(`playerID`) as `playerCount`',
                'sum(`consumeMoney10001`) as consumeMoney10001',
                'sum(`consumeMoney10010`) as consumeMoney10010',
            ])->get();

var_dump($total);
var_dump($total->toArray());

```
dump的结果如下：
object(App\Model\History\MagicBookStatisticsModel)#195 (24) {
  ["tableName":protected]=>
  string(20) "magicbook_statistics"
  ["connectionName":protected]=>
  string(7) "history"
  ["lastQueryResult":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["lastQuery":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["fields":"EasySwoole\ORM\AbstractModel":private]=>
  string(1) "*"
  ["limit":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["withTotalCount":"EasySwoole\ORM\AbstractModel":private]=>
  bool(false)
  ["order":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["where":"EasySwoole\ORM\AbstractModel":private]=>
  array(0) {
  }
  ["join":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["group":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["alias":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["tempConnectionName":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["data":"EasySwoole\ORM\AbstractModel":private]=>
  array(2) {
    ["consumeMoney10001"]=>
    string(3) "420"
    ["consumeMoney10010"]=>
    string(6) "800000"
  }
  ["_joinData":"EasySwoole\ORM\AbstractModel":private]=>
  array(1) {
    ["playerCount"]=>
    int(5)
  }
  ["originData":"EasySwoole\ORM\AbstractModel":private]=>
  array(2) {
    ["consumeMoney10001"]=>
    string(3) "420"
    ["consumeMoney10010"]=>
    string(6) "800000"
  }
  ["onQuery":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["tempTableName":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["client":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["autoTimeStamp":protected]=>
  bool(false)
  ["createTime":protected]=>
  string(11) "create_time"
  ["updateTime":protected]=>
  string(11) "update_time"
  ["with":"EasySwoole\ORM\AbstractModel":private]=>
  NULL
  ["preHandleWith":"EasySwoole\ORM\AbstractModel":private]=>
  bool(false)
}
array(2) {
  ["consumeMoney10001"]=>
  string(3) "420"
  ["consumeMoney10010"]=>
  string(6) "800000"
}

toArray()之后丢失了playerCount这个字段的数据

**Comment by xuanyanwow** [comment]
toArray()默认只返回 表结构 字段，如果要返回其他字段，需要在toArray传参决定

```php
public function toArray($notNul = false, $strict = true): array
```
