### ISSUE TITLE
注解验证器的 min 和max 都失效了

### ISSUE THREAD

**Issue by yaoyinbear** [easy-swoole/easyswoole#291]
Swoole version: 4.4.15
EasySwoole version: 3.3.4

注解验证器里设置的min和max貌似都无效了
`* @Param(name="limit",alias="分页条数",required="",integer="",min="1",max="2000")`

提交limit=1 或者 limit=10000 都能验证通过

**Comment by kiss291323003** [comment]
并没有出现你说的问题
