### ISSUE TITLE
kafka重复消费

### ISSUE THREAD

**Issue by zxyphp** [easy-swoole/easyswoole#292]
kafka消费总是重复消费,看了下源码因为偏移量一直是0

**Comment by Manlinup** [comment]
composer 更新一下kafka包。
设置 消费的偏移量提示为 CONSUME_AFTER_COMMIT_OFFSET  
如果还有问题，加一下 kafka群，827432930，贴一下报错信息

**Comment by Manlinup** [comment]
> kafka消费总是重复消费,看了下源码因为偏移量一直是0
