### ISSUE TITLE
ORM-v1.4，模型事件中，怎么获取$model对象的$data和$originData属性的值

### ISSUE THREAD

**Issue by fuliang10000** [easy-swoole/easyswoole#296]
有这样一个应用场景，在表的增、删、改操作时，需要通过模型事件来写入操作日志，以便追溯每个后台用户做了些什么。
以下举例说明；
①假设role表有id、name、status三个字段；
②insert操作时，需要获取$model对象的$data以便写入日志；
③update操作时，假设要将name='客服'改为name='运营'，需要获取$model对象的$data和$originData属性的值，以便对比并组装修改内容并写入日志；

代码：
protected static function onAfterInsert($model, $res): bool
    {
        var_dump($model);
        return $res;
    }
输出为
修改前：
["originData":"EasySwoole\ORM\AbstractModel":private]=>
  array(5) {
    ["id"]=>
    int(77)
    ["name"]=>
    string(12) "测试行为"
    ["created_at"]=>
    int(1584868548)
    ["updated_at"]=>
    int(1584868548)
    ["status"]=>
    int(1)
  }
修改后：
["data":"EasySwoole\ORM\AbstractModel":private]=>
  array(5) {
    ["id"]=>
    int(77)
    ["name"]=>
    string(18) "测试行为修改"
    ["created_at"]=>
    int(1584868548)
    ["updated_at"]=>
    int(1584928578)
    ["status"]=>
    int(1)
  }

**Comment by xuanyanwow** [comment]
提问前，master分支已增加toRawArray();方法，用于获取原始$this->data数据（不经过修改器）；

可通过该方法打印，也可使用toArray();方法获取数据（经过修改器）

提问后，在beforeUpdate增加$updateData变量，用于获取变动数据。

请先依赖master分支开发，后续打tag发布版本。

```php
    protected static function onBeforeInsert($model)
    {
    	var_dump($model->toRawArray());
        return true;
    }

    protected static function onBeforeUpdate($model, $updateData)
    {
        var_dump($model->toRawArray());
        var_dump($updateData);
        return true;
    }

    protected static function onBeforeDelete($model)
    {
        var_dump($model->toRawArray());
        return true;
    }
```
