### ISSUE TITLE
关于框架的批量更新功能

### ISSUE THREAD

**Issue by flowerwOw0316** [easy-swoole/easyswoole#310]
您好，我是在easyswoole3群的 汤圆酱吃鸡腿。
目前在使用easyswoole框架的时候 遇到一个批量更新的问题。
在通读文档以后发现框架内置的批量更新方法只能够更新值为一样的数据。
例如：[ id =>1 , name =>a , id=>2 ,name=>a ]   这样利用框架的内置方法用where里面的IN能轻松解决这个问题 ,但是如果遇到不一样的 就没这个方法了，请问下除了foreach一条条的循环更新值不一样的数据外 框架有没有其他的方法能快捷解决这个问题。

**Comment by xuanyanwow** [comment]
orm方法中的`saveAll($data, $replace = true, $transaction = true)`  
第二个参数 如果为false，则表示不尝试进行判断 `主键是否存在,在则更新`

但其实内部也依旧是foreach循环更新，自行封装也可以
