### ISSUE TITLE
时间戳的问题

### ISSUE THREAD

**Issue by flowerwOw0316** [easy-swoole/easyswoole#311]
框架的自动时间戳不够人性化呀，写入既然能自动时间戳，读取的时候也可以加一个自动转换的功能，通过一些参数控制是转成时分秒 还是日期，仅仅是建议，其他的一些框架也有这样的功能。

**Comment by xuanyanwow** [comment]
自动时间戳可以配置写入的类型:时间戳、时间字符串、自定义格式，

同时取出时候的格式可以在model文件中定义获取器。

http://www.easyswoole.com/Cn/Components/Orm/getter.html

请仔细阅读官方文档，功能基本上都写明了。
