### ISSUE TITLE
自定义错误处理和自定义日志处理无效，应该还是globalInitialize的问题

### ISSUE THREAD

**Issue by kingrainy** [easy-swoole/easyswoole#312]
在EasySwooleEvent的initialize方法里自定义错误处理和自定义日志处理都不好使了，应该还是globalInitialize的问题，Di注入的内容在注册错误回调时没获取到。
![image](https://user-images.githubusercontent.com/18109691/79734255-fb85c580-8328-11ea-8ebf-e11f28c730c3.png)

**Comment by kiss291323003** [comment]
感谢反馈，正在查看

**Comment by kiss291323003** [comment]
文档已经跟进   细节调整  
https://www.easyswoole.com/Cn/BaseUsage/log.html

**Comment by wofengletian** [comment]
最新版初始化方式变了吗？调整文档是什么意思？
