### ISSUE TITLE
关于性能压测报告差异巨大的疑问

### ISSUE THREAD

**Issue by feng99** [easy-swoole/easyswoole#313]
各位好.
我司新项目打算用基于swoole的框架编写,目的是提高单机qps,节省服务器资源, 简单来说:想省钱.
在阅读了easyswoole的文档和hyperf的文档之后,发现关于压测部分的数据,差异较大.
具体如下:

**easyswoole**
机器配置 8 Core 16G RAM
Server Software:        EasySwoole
Server Hostname:        192.168.0.4
Server Port:            9501

Document Path:          /
Document Length:        21 bytes

Concurrency Level:      100
Time taken for tests:   0.746 seconds
Complete requests:      10000
Failed requests:        0
Write errors:           0
Total transferred:      1690000 bytes
HTML transferred:       210000 bytes
Requests per second:    66935.97 [#/sec] (mean)
Time per request:       1.149 [ms] (mean)
Time per request:       0.015 [ms] (mean, across all concurrent requests)
Transfer rate:          2265.40 [Kbytes/sec] received

**关键信息为:Requests per second:    66935.97 [#/sec] (mean)
秒QPS6万6**

-------------------------------------------
**hyperf**
Aliyun 8 cores 16G ram
 

Running 10s test @ http://127.0.0.1:9501/
  8 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    10.08ms    6.82ms  56.66ms   70.19%
    Req/Sec    13.17k     5.94k   33.06k    84.12%
  1049478 requests in 10.10s, 190.16MB read
Requests/sec: 103921.49
Transfer/sec:     18.83MB

**关键信息为:Requests/sec: 103921.49   
秒QPS 10万**
------------------------------------------
个人理解: 都是基于swoole的框架  直觉上,性能应该差异不大,
虽然压测都是基于hello world   没有实际的数据读取等业务逻辑
但是看到这个差异  心里还是蛮惊讶的

想知道具体的原因是什么?
是压测方式的差异?
还是基于swoole之后,做了什么修改导致的?
可以肯定的是 这两份压测数据都是理论值, 在实际生产环境中,
由于代码质量, 数据库连接数 单机或者集群
或者redis的性能  或者单接口内逻辑太多未做解耦 
等各种原因导致性能肯定没有这么强.

说明,在查阅相关资料总发现两个框架有一些历史渊源,但 我不是来吵架的  不属于任何一个阵营,
完成公司的工作,节省服务器资源  才是我的目标. 

最后感谢框架的作者们,为php的生态提供更高性能的框架.

**Comment by LuffyQAQ** [comment]
首先压测工具不是一样的，压测的结果可能导致不同，其次是如果有条件的话，可以自行压测对比，最后，性能虽然是框架的一部分，但是我感觉稳定才是主要的

**Comment by RunsTp** [comment]
非常感谢你提出的问题，这是一个有很多人关注的典型问题。

很抱歉我可能会用较长的篇幅来说明这个问题，但是可能你阅读完成之后并没有任何用处；不过我依然相信可以给你带来新的选择方式。

首先对照性能测试的核心思想就是控制变量，以下是需要严格控制的内容：

硬件
受压机配置是否相同，即便Cpu Core相同，但是可能型号并不相同，Core带来的性能也不同
施压机配置是否够用，如果施压机本身性能存在瓶颈，那么将会拖累测试结果
网络
网络通道是否良好，带宽是否充足；当然通常我们默认选择内网千兆万兆环境，通常不是阻碍
软件
施压工具是否可靠有效，这里我当然是强烈建议使用广泛被使用的工具，而不是自己随便编写的测试脚本
施压工具配置是否相同，原则上必须保持完全一致
测试
原则上必须统一测试场景，并且保证被测试系统实现也基本一致
输出压力方式以及测试时间是否统一，原则上是必须保持一致
测试完成后，测试期间施压系统和受压系统的性能占用指标也是考量的部分
在你提出的这个例子当中，我们按照上述的内容进行对照可以发现：

硬件
尽管看上去都是 8 Core 16G RAM，但是我们并不清楚其具体的Cpu型号（我们以阿里云为例，同样的8C-16G可能是不同型号的Cpu，尽管我们可以认为在高IO场景性能差距有限，但依旧是存在差异附-阿里云相关介绍
施压机配置我们目前无从得知，考虑到双方作者都是非常资深的开发人员，我相信不会犯这样的错误
网络
就目前结果看上去，很明显都是在内网环境中测试的
软件
目前可以明显确定，使用的施压工具并不相同，但都是被广泛使用的工具，可以认为是可以信任的有效数据
工具并不一致，所以也基本可以认定配置是不同的
测试
可以通过测试报告看出，EasySwoole和Hyperf采取了不同的测试场景和方法，这直接导致完全不同的测试结果
目前也无从得知双方使用的测试场景的压力输出方式，但是明显可以确定的是测试时间是不一致的
由于双方都没有给出测试过程中，被测试系统的系统占用情况，所以也没有办法从这个方向获取到相关性能评估
综上所述： 双方文档中提供的测试结果，并非是统一的测试环境和测试场景，并不能直接对比结果。考虑到性能测试是一个非常注重细节的事情，我强烈建议你自己部署统一的测试环境和设计统一的测试场景；这样最终得出的测试结论才是准确有效的测试结果。

**Comment by feng99** [comment]
好的  感谢回复  
我会在测试机器 分别安装easyswoole和hyperf压测 一遍的.
