### ISSUE TITLE
init方法调整的提交，导致在EasySwooleEvent的initialize方法中注册的LOGGER_HANDLER未生效

### ISSUE THREAD

**Issue by wofengletian** [easy-swoole/easyswoole#314]
init方法调整的提交，导致在EasySwooleEvent的initialize方法中注册的LOGGER_HANDLER未生效
现在把EasySwooleEvent的initialize放在了框架初始化之后，导致框架初始化时获取的SysConst::LOGGER_HANDLER为空。请问换成这样Logger要在哪里初始化，我把logger的初始化放到EasySwooleEvent的initialize方法中有问题吗？

private function registerErrorHandler()
    {
        ini_set("display_errors", "On");
        error_reporting(E_ALL | E_STRICT);

        //初始化配置Logger      ========》》》  这里获取不到LOGGER_HANDLER
        $logger = Di::getInstance()->get(SysConst::LOGGER_HANDLER);
        if(!$logger instanceof LoggerInterface){
            $logger = new DefaultLogger(EASYSWOOLE_LOG_DIR);
        }
        Logger::getInstance($logger);

        //初始化追追踪器
        $trigger = Di::getInstance()->get(SysConst::TRIGGER_HANDLER);
        if(!$trigger instanceof TriggerInterface){
            $trigger = new DefaultTrigger(Logger::getInstance());
        }
        Trigger::getInstance($trigger);

        //在没有配置自定义错误处理器的情况下，转化为trigger处理
        $errorHandler = Di::getInstance()->get(SysConst::ERROR_HANDLER);
        if(!is_callable($errorHandler)){
            $errorHandler = function($errorCode, $description, $file = null, $line = null){
                $l = new Location();
                $l->setFile($file);
                $l->setLine($line);
                Trigger::getInstance()->error($description,$errorCode,$l);
            };
        }
        set_error_handler($errorHandler);

        $func = Di::getInstance()->get(SysConst::SHUTDOWN_FUNCTION);
        if(!is_callable($func)){
            $func = function (){
                $error = error_get_last();
                if(!empty($error)){
                    $l = new Location();
                    $l->setFile($error['file']);
                    $l->setLine($error['line']);
                    Trigger::getInstance()->error($error['message'],$error['type'],$l);
                }
            };
        }
        register_shutdown_function($func);
    }

**Comment by kiss291323003** [comment]
文档有注明，https://www.easyswoole.com/Cn/BaseUsage/log.html

3.3.7版本做了细微变动。请移动到 
在 bootstrap.php bootstrap事件中注入自定义logger处理器:

**Comment by wofengletian** [comment]
> 文档有注明，https://www.easyswoole.com/Cn/BaseUsage/log.html
> 
> 3.3.7版本做了细微变动。请移动到
> 在 bootstrap.php bootstrap事件中注入自定义logger处理器:

这样不太合理吧
const LOGGER_HANDLER = 'LOGGER_HANDLER'; 这个应该就没什么用了
