### ISSUE TITLE
你好,我之前一直使用的beanstalk队列,能否无缝接入到easyswoole中?

### ISSUE THREAD

**Issue by feng99** [easy-swoole/easyswoole#315]
你好,我之前一直使用的beanstalk队列,能否无缝接入到easyswoole中?
如果不能,需要更换成哪一个?
如果能,参考哪个文档?
用习惯了  比较轻量级 ,理解起来也比较简单.

**Comment by kiss291323003** [comment]
可以的。完全可以。
另外，easyswoole的fast cache组件，也有提供beanstalk特性
