### ISSUE TITLE
Orm使用in条件错误

### ISSUE THREAD

**Issue by liserven** [easy-swoole/easyswoole#316]
在使用orm有连贯操作的时候 where条件传入  这样的条件 就报错
UserModel::create()->where(array(
                'id' => array( $upIds, 'IN'),
            ))->all()
报错如下：
Invalid argument supplied for foreach() at file:/www/wwwroot/qmzb/vendor/easyswoole/mysqli/src/QueryBuilder.php line:1163

**Comment by hkj1994** [comment]
![image](https://user-images.githubusercontent.com/41996511/81646063-2f05cc80-945d-11ea-9051-5536dba436db.png)

**Comment by xuanyanwow** [comment]
应该是orm版本较低导致，新版测试正常
