### ISSUE TITLE
RedisCluster 部署，在获取get的时候卡住不动

### ISSUE THREAD

**Issue by caption1** [easy-swoole/easyswoole#318]
redis主要存储图片的base64值。
业务是循环发送群（群，文字等）。图片存储redis读取redis。
    public function hander(){
        try {
            $redis = new \EasySwoole\Redis\RedisCluster(new \EasySwoole\Redis\Config\RedisClusterConfig([
                ['172.16.0.36', 6379],
                ['172.16.0.36', 6380],
                ['172.16.0.36', 6381],
                ['172.16.0.37', 6379],
                ['172.16.0.37', 6380],
                ['172.16.0.37', 6381],
                ['172.16.0.38', 6379],
                ['172.16.0.38', 6380],
                ['172.16.0.38', 6381],
            ], [
                'auth' => '',
                'serialize' => $this->serialize ? \EasySwoole\Redis\Config\RedisConfig::SERIALIZE_JSON : \EasySwoole\Redis\Config\RedisConfig::SERIALIZE_NONE,
                'timeout'=>1
            ]));
        }catch (\Throwable $e) {
            $extra = [
                'code' => $e->getCode(),
                'msg' => $e->getMessage(),
                'line' => $e->getLine(),
                'file' => $e->getFile()
            ];
            echo "Exception:".json_encode($extra)."\n";
            return false;
        } 
        return $redis;
    }

直接在发送的时候获取redis hander，get ，循环的时候有时候卡住了，有时候正常，一般前两个正常，第三个就卡住。

什么情况？设置redis的超时时间了。

**Comment by tioncico** [comment]
提供一下 调用redis->get的代码截图

**Comment by tioncico** [comment]
```php
<?php
/**
 * Created by PhpStorm.
 * User: tioncico
 * Date: 2020-05-11
 * Time: 10:03
 */
include "../vendor/autoload.php";
go(function (){

    $redis = new \EasySwoole\Redis\RedisCluster(new \EasySwoole\Redis\Config\RedisClusterConfig([
        ['127.0.0.1', 9001],
        ['127.0.0.1', 9002],
        ['127.0.0.1', 9003],
        ['127.0.0.1', 9004],
    ], [
        'auth'      => '',
        'serialize' => \EasySwoole\Redis\Config\RedisConfig::SERIALIZE_JSON,
        'timeout'   => 1
    ]));

    for ($i=0;$i<=1000;$i++){
        $redis->set("test{$i}",$i);
    }
    for ($i=0;$i<=1000;$i++){
        $data = $redis->get("test{$i}");
        var_dump($data);
    }

});
```
并没有你说的问题,根据目前的推测,可能是你使用redis不当,请使用redis连接池.

**Comment by caption1** [comment]
>     /**
     * 根据图片地址获取图片base64
     * @param unknown $picUrl
     */
    public function getPicBase64($picUrl,$fromUser='',$toUser=''){
        $picKey = md5($picUrl);
        $redis = new Redis();
        if($redis){
            echo "----get start -- \n";
            $cache = $redis->get($picKey);
            echo "----get done -- \n";
            if(!$cache){
                //获取
                //             $cache = $this->getBase64FromMySql($picKey);
                //             if($cache){
                //                 return $cache;
                //             }
                $base64 = $this->getUrlBase64($picUrl);
                if($base64 && $base64['base_data']){
                    //存储缓存
                    $cache = $this->store($picUrl,$picKey, $base64,$fromUser='',$toUser='');
                }
            }
        }else{
            $base64 = $this->getUrlBase64($picUrl);
            $cache = $base64['base_data'];
        }

        unset($redis);
        return $cache;
    }

**Comment by caption1** [comment]
>     public function get($key){
        try{
            return $this->hander->get($this->prefix.$key);
        }catch (\Throwable $e) {
            $extra = [
                'code' => $e->getCode(),
                'msg' => $e->getMessage(),
                'line' => $e->getLine(),
                'file' => $e->getFile()
            ];
            echo "Exception:".json_encode($extra)."\n";
            return '';
        }
    }

**Comment by caption1** [comment]
这个地方 
 echo "----get start -- \n";
        $cache = $redis->get($picKey);
        echo "----get done -- \n";
有时候经常卡在get start  。$redis就是主题里面的hander

**Comment by tioncico** [comment]
好的,你这个问题我这段时间会查一下,能提供一下最小复现代码吗?

**Comment by caption1** [comment]
我升级了下系统配置，这种情况目前变少了。貌似跟我先前cpu经常90%有点关系。但这种情况建议加个超时处理

**Comment by tioncico** [comment]
默认是有超时配置的,可能没有生效,我有空查查

**Comment by tioncico** [comment]
你好,问题已经查出,在redis获取数据超时时,可能会出现获取到一半数据,导致RedisClient死循环,期望获取剩下的数据,导致出错,已修复https://github.com/easy-swoole/redis/pull/47

**Comment by caption1** [comment]
好的
