### ISSUE TITLE
rediscluster 模式

### ISSUE THREAD

**Issue by caption1** [easy-swoole/easyswoole#323]
会报这个：
Exception:{"code":0,"msg":"MOVED 2597 172.16.0.37:6379","line":863,"file":"\/home\/www\/easyswoole\/vendor\/easyswoole\/redis\/src\/RedisCluster.php"}

代码：
//redis连接池
        $redisPoolConfig = \EasySwoole\RedisPool\Redis::getInstance()->register('redisCluster0',new \EasySwoole\Redis\Config\RedisClusterConfig([
            ['172.16.0.36', 6379],
            ['172.16.0.36', 6380],
            ['172.16.0.36', 6381],
            ['172.16.0.37', 6379],
            ['172.16.0.37', 6380],
            ['172.16.0.37', 6381],
            ['172.16.0.38', 6379],
            ['172.16.0.38', 6380],
            ['172.16.0.38', 6381],
        ], [
            'auth' => 'e',
            'serialize' => \EasySwoole\Redis\Config\RedisConfig::SERIALIZE_NONE ,
            'timeout'=>1
        ]
            ));
        //配置连接池连接数
        $redisPoolConfig->setMinObjectNum(5);
        $redisPoolConfig->setMaxObjectNum(200);
        $redisPoolConfig->setAutoPing(10);

  public function set($key,$val,$expire=0){
        try{
            $prefix = $this->prefix;
            return  $val && \EasySwoole\RedisPool\Redis::invoke('redisCluster'.$this->serialize, function (\EasySwoole\Redis\Redis $redis)use($prefix,$key,$val,$expire) {
                return $redis->set($prefix.$key,$val,$expire);
            });
        }catch (\Throwable $e) {
            $extra = [
                'code' => $e->getCode(),
                'msg' => $e->getMessage(),
                'line' => $e->getLine(),
                'file' => $e->getFile()
            ];
            echo "Exception:".json_encode($extra)."\n";
            return false;
        } 
        
    }
    
    public function get($key){
        try{
            $prefix = $this->prefix;
            return  \EasySwoole\RedisPool\Redis::invoke('redisCluster'.$this->serialize, function (\EasySwoole\Redis\Redis $redis)use($prefix,$key) {
                return $redis->get($prefix.$key);
            });
        }catch (\Throwable $e) {
            $extra = [
                'code' => $e->getCode(),
                'msg' => $e->getMessage(),
                'line' => $e->getLine(),
                'file' => $e->getFile()
            ];
            echo "Exception:".json_encode($extra)."\n";
            return '';
        }
    }  public function set($key,$val,$expire=0){
        try{
            $prefix = $this->prefix;
            return  $val && \EasySwoole\RedisPool\Redis::invoke('redisCluster'.$this->serialize, function (\EasySwoole\Redis\Redis $redis)use($prefix,$key,$val,$expire) {
                return $redis->set($prefix.$key,$val,$expire);
            });
        }catch (\Throwable $e) {
            $extra = [
                'code' => $e->getCode(),
                'msg' => $e->getMessage(),
                'line' => $e->getLine(),
                'file' => $e->getFile()
            ];
            echo "Exception:".json_encode($extra)."\n";
            return false;
        } 
        
    }
    
    public function get($key){
        try{
            $prefix = $this->prefix;
            return  \EasySwoole\RedisPool\Redis::invoke('redisCluster'.$this->serialize, function (\EasySwoole\Redis\Redis $redis)use($prefix,$key) {
                return $redis->get($prefix.$key);
            });
        }catch (\Throwable $e) {
            $extra = [
                'code' => $e->getCode(),
                'msg' => $e->getMessage(),
                'line' => $e->getLine(),
                'file' => $e->getFile()
            ];
            echo "Exception:".json_encode($extra)."\n";
            return '';
        }
    }

**Comment by tioncico** [comment]
经测试,并没有你所说的问题 
个人猜测你在redis运行过程中,有使用集群命令修改槽位绑定.如果你不理解这句话,请忽略
可以尝试升级redis.
测试脚本如下
```php
<?php
include "./vendor/autoload.php";

//redis连接池
$redisPoolConfig = \EasySwoole\RedisPool\Redis::getInstance()->register('redisCluster', new \EasySwoole\Redis\Config\RedisClusterConfig([
    ['127.0.0.1', 9001],
    ['127.0.0.1', 9002],
    ['127.0.0.1', 9003],
    ['127.0.0.1', 9004],
], [
        'serialize' => \EasySwoole\Redis\Config\RedisConfig::SERIALIZE_NONE,
        'timeout'   => 1
    ]
));
//配置连接池连接数
$redisPoolConfig->setMinObjectNum(5);
$redisPoolConfig->setMaxObjectNum(200);
$redisPoolConfig->setAutoPing(10);
go(function () {
    set('a', 1);
    $data = get('a');
    var_dump($data);
});

function set($key, $val, $expire = 0)
{
    try {
        $prefix = '';
        return $val && \EasySwoole\RedisPool\Redis::invoke('redisCluster', function (\EasySwoole\Redis\Redis $redis) use ($prefix, $key, $val, $expire) {
                return $redis->set($prefix . $key, $val, $expire);
            });
    } catch (\Throwable $e) {
        $extra = [
            'code' => $e->getCode(),
            'msg'  => $e->getMessage(),
            'line' => $e->getLine(),
            'file' => $e->getFile()
        ];
        echo "Exception:" . json_encode($extra) . "\n";
        return false;
    }

}

function get($key)
{
    try {
        $prefix = '';
        return \EasySwoole\RedisPool\Redis::invoke('redisCluster', function (\EasySwoole\Redis\Redis $redis) use ($prefix, $key) {
            return $redis->get($prefix . $key);
        });
    } catch (\Throwable $e) {
        $extra = [
            'code' => $e->getCode(),
            'msg'  => $e->getMessage(),
            'line' => $e->getLine(),
            'file' => $e->getFile()
        ];
        echo "Exception:" . json_encode($extra) . "\n";
        return '';
    }
}

```

**Comment by caption1** [comment]
没有修改槽位的，例外我们的redis是5.0
