### ISSUE TITLE
words-match出现不该出现的词

### ISSUE THREAD

**Issue by linsweet** [easy-swoole/easyswoole#324]
public static function mainServerCreate(EventRegister $register)
    {
        // TODO: Implement mainServerCreate() method.
        WordsMatchServer::getInstance()
            ->setMaxMem('1024M') // 每个进程最大内存
            ->setProcessNum(3) // 设置进程数量
            ->setServerName('Easyswoole words-match')// 服务名称
            ->setTempDir(EASYSWOOLE_TEMP_DIR)// temp地址
            ->setWordsMatchPath(EASYSWOOLE_ROOT.'/WordsMatch/')
            ->setDefaultWordBank('comment.txt')// 服务启动时默认导入的词库文件路径
            ->setSeparator(',')// 词和其它信息分隔符
            ->attachToServer(ServerManager::getInstance()->getSwooleServer());

    }

    public static function onRequest(Request $request, Response $response): bool
    {
        // TODO: Implement onRequest() method.
        $res = file_get_contents(EASYSWOOLE_ROOT.'/WordsMatch/comment.txt');
        $arr = explode(PHP_EOL, $res);
        foreach ($arr as $v) {
            if ($v == '的') echo $v;
        }
        // WordsMatchServer::getInstance()->export(EASYSWOOLE_ROOT.'/WordsMatch/comment.txt');
        $res = WordsMatchClient::getInstance()->search('php是世界上最好的语言，其它类型的程序员不认可php的这句话，比如java、golang。');
        var_dump($res);
        return true;
    }

词库地址:
[http://122.51.71.80/comment.txt](url)

**Comment by huizhang001** [comment]
麻烦词库完整的发一下吧。好像地址失效了，还有就是不该出现的词是什么情况，也给截下图吧。

**Comment by linsweet** [comment]
词库地址: [https://raw.githubusercontent.com/AbelZhou/PHP-TrieTree/master/test/dict.txt](url)
运行结果:
array(1) {
  ["01d7aa494b0727f8db77be1d3685de9e"]=>
  array(3) {
    ["word"]=>
    string(3) "的"
    ["other"]=>
    array(0) {
    }
    ["count"]=>
    int(3)
  }
}

我在词库中搜索没搜到  '的', 或者'的,'

**Comment by huizhang001** [comment]
![image](https://user-images.githubusercontent.com/26496638/83356940-e9715b00-a39b-11ea-88f6-6daeec26fb16.png)
兄弟，我刚才搜了一下，这个词库的第10611行，有的这个词。

感谢提issue！但还是希望下次能仔细检查一下。
