### ISSUE TITLE
timer+task导致进程内存泄漏，占用内存持续增长

### ISSUE THREAD

**Issue by 729343861** [easy-swoole/easyswoole#325]
由于昨日发现进程泄漏增长到2G，然后逐一排查发现是循环定时器里投递了异步任务导致的，经最小单元测试，确实如此。

下面是测试代码

`
class Test1 extends AbstractProcess
{

    private $data ;

    protected function run($arg)
    {

        try{

            $timerId = \EasySwoole\Component\Timer::getInstance()->loop(1 * 1000, function () {

                $task = TaskManager::getInstance();
                $rand = mt_rand(1,1000);
                $task->async(function ()use ($rand){

                   $a =  $rand;

                });

            });
        }catch (\Exception $e){

            var_dump($e->getMessage());
        }

    }
}
`

**Comment by kiss291323003** [comment]
有oom报错吗、、、、这块的代码是没问题的。我刚刚测试了。使用的时候内存上涨是正常的。到达一定的时候会被php gc机制回落。

**Comment by 729343861** [comment]
不会报错啊，就是自定义进程的内存会持续上涨，运行几个小时后，自定义进程会达到2G

**Comment by kiss291323003** [comment]
那这就不是内存泄漏了亲。可以自己参考搜索下php gc机制
