### ISSUE TITLE
使用体验问题反馈

### ISSUE THREAD

**Issue by LinkedDestiny** [easy-swoole/easyswoole#326]
* 使用注解校验参数，设置默认值后，底层会把int类型默认值以float类型展示，这里缺少一个类型校验

* 少一个自动生成Model的组件

* Model的字段最好可以提供一个cast模式，指定相关字段在查询出来后的转化，比如时间戳到时间，大整数到int，枚举到枚举值等等

* 注解路由最好是用fastroute索引，而不是仍然使用pathinfo路由

**Comment by tioncico** [comment]
我曹,上次头像没显示,没发现是大佬
自动生成组件已经加入官方仓库了:https://www.easyswoole.com/Cn/Components/codeGeneration.html
其他的还没整

**Comment by kiss291323003** [comment]
都已经好了
