### ISSUE TITLE
css或者js等静态资源的加载

### ISSUE THREAD

**Issue by LaravelChen** [easy-swoole/easyswoole#33]
使用里面的辅助函数url，显示404

**Comment by hanwenbo** [comment]
## 开发的环境
PHP 版本：
easy-swoole版本：

## 问题及现象
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by LaravelChen** [comment]
这个问题解决了！配置问题!
