### ISSUE TITLE
log的需求bug

### ISSUE THREAD

**Issue by 729343861** [easy-swoole/easyswoole#330]
log文件由于是启动加载的，所以长时间会堆积大量的日志，导致文件越来越大，写入会越来越慢。
能不能优化log系统，设置文件大小上限，新起一个log文件

**Comment by kiss291323003** [comment]
日志有log handler。文档有

**Comment by 729343861** [comment]
自定义log 类，之前测试过，只能用于手动写入日志，程序运行日志无法使用。
