### ISSUE TITLE
Redis的unix socket连接应该如何配置

### ISSUE THREAD

**Issue by kkstun** [easy-swoole/easyswoole#336]
Return value of EasySwoole\Redis\Config\RedisConfig::getPort() must be of the type int, string returned

好像不支持unix socket连接吗

**Comment by tioncico** [comment]
你好,redis组件只支持tcp协议连接

**Comment by tioncico** [comment]
https://github.com/easy-swoole/doc-3.3.x/pull/150  你好,新增UnixSocket协议连接支持
