### ISSUE TITLE
使用自定义路由的一些奇怪现象

### ISSUE THREAD

**Issue by jeckleee** [easy-swoole/easyswoole#337]
今天从使用composer安装的3.3.7版本,未做任何修改

自定义路由代码如下:
`class Router extends AbstractRouter
{
	function initialize(RouteCollector $routeCollector)
	{
		$this->setGlobalMode(true);//启用严格的路由匹配模式

		$routeCollector->get('/inde', '/Index/index');
		$routeCollector->get('/index.html', '/Index/index');
                $routeCollector->get('/index', '/Index/index');

		$this->setMethodNotAllowCallBack(function (Request $request,Response $response){
			$response->write('方法不存在');
			return false;//结束此次响应
		});
		$this->setRouterNotFoundCallBack(function (Request $request,Response $response){
			$response->write('路由未定义');
			//return '/';//重定向到index路由
		});
		
	}
}`

访问http://127.0.0.1:9501/inde
显示正常

访问http://127.0.0.1:9501/index.html
显示"路由未定义"

访问http://127.0.0.1:9501/index
显示"路由未定义"

是不是很奇怪??????

同样,我的电脑中还有一个旧版3.2.5,
使用上面的路由,均返回正常结果.

是我哪里没做对吗?期望官方给予解答

**Comment by kiss291323003** [comment]
....新版本支持了一个path infomode   默认开启
