### ISSUE TITLE
DefaultPackageParser导致RPC问题

### ISSUE THREAD

**Issue by fsrm365** [easy-swoole/easyswoole#34]
DefaultPackageParser的encode和decode使用了base_convert，导致RPC的service收到的Package有问题。测试时将base_convert去掉后，RPC正常调用了。
![image](https://user-images.githubusercontent.com/5212478/34080769-2e8c660c-e37e-11e7-9518-d7832210c95c.png)

swoole version       2.0.10
easyswoole version   1.1.1
PHP：
PHP 7.0.18-0ubuntu0.16.10.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.10.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by kiss291323003** [comment]
好的  感谢反馈

**Comment by evalor** [comment]
fix complete
