### ISSUE TITLE
数据导出，经常报错：WARNING   swFactoryProcess_finish(:472): sendto to reactor failed, Error: No buffer space available

### ISSUE THREAD

**Issue by xiaohuihuiye** [easy-swoole/easyswoole#343]
环境：
swoole version                4.3.4
php version                   7.1.18
easy swoole                   3.2.4-dev

官方查找处理方法，设置如下
'buffer_output_size' => 10 * 1024 *1024,

多次导出后还是会报错，个人觉得是缓冲池没有清空导致。不清楚如何清空缓冲池

**Comment by kiss291323003** [comment]
swoole版本该升级了
