### ISSUE TITLE
在调用toArray之前建议处理下查询结果为null的情况

### ISSUE THREAD

**Issue by Doujang** [easy-swoole/easyswoole#344]
![image](https://user-images.githubusercontent.com/20734553/84138513-f3bce480-aa80-11ea-9b73-86128c358a60.png)
![image](https://user-images.githubusercontent.com/20734553/84138521-f7e90200-aa80-11ea-9a53-435feaa598e7.png)

**Comment by Doujang** [comment]
![image](https://user-images.githubusercontent.com/20734553/84139938-5dd68900-aa83-11ea-8466-8c606e0a967e.png)

**Comment by Doujang** [comment]
![image](https://user-images.githubusercontent.com/20734553/84139967-6af37800-aa83-11ea-8ff2-74ba72c504a3.png)

**Comment by kiss291323003** [comment]
调用前请自己判断
