### ISSUE TITLE
对于压力测试的疑问

### ISSUE THREAD

**Issue by slarkes** [easy-swoole/easyswoole#348]
因为我的8核16G服务器ab测试竟然跟首页文档里1核1G服务器的数据差不多.于是仔细对比了一下我的测试结果和文档里的结果.发现好像有点疑问.先不说我服务器的问题.文档里的两组数据好像就有点对不上
一般来说 ab测试结果的数据是可以互相推算的吧? 例如
Requests per second = Complete requests / Time taken for tests
Time per request = Time taken for tests / Complete requests
我自己做的ab测试基本都遵守上面的算法
但是首页文档上的两个结果都是不能相互推算的.
不知道是不是我哪里理解不对...

**Comment by kiss291323003** [comment]
所以你的压测结构是？？？？？？

**Comment by slarkes** [comment]
> 所以你的压测结构是？？？？？？

测试就是按文档上安装的hello world ,也是ab -c 100 -n 10000
我现在比较疑惑的是文档上的测试结果数据并不能相互推算

**Comment by kiss291323003** [comment]
所以你的压测结构呢？？？贴一下可好？你既然怀疑文档造假，不妨贴下你完整的压测结果。

**Comment by slarkes** [comment]
额...我没说文档造假,
文档上测试结果:
![image](https://user-images.githubusercontent.com/6846418/84774038-d4d5c980-b00f-11ea-8026-0d6af16d6eee.png)
完成1w个请求花费了0.746s,按公式换算qps应该是10000/0.746
我只是想知道原因而已.这跟我自己的测试结果已经没有关系了.

**Comment by kiss291323003** [comment]
噢、、那我就不懂了噢，ab执行结果是什么我就复制粘贴什么，如果你发现有错误，可以欢迎贴你的压测结果来指正
