### ISSUE TITLE
date_default_timezone_set('Asia/Shanghai'); 在命令行未生效

### ISSUE THREAD

**Issue by WuYunlong** [easy-swoole/easyswoole#349]
EasySwooleEvent.php

```php
public static function initialize()
    {
        // 默认时区
        date_default_timezone_set('Asia/Shanghai');
    }
```

此时在控制器中使用时区为正常。

```bash
php easyswoole crontab show
```

在此处显示的时区未使用配置内容。 

当前我解决的方法是在 `EASYSWOOLE_ROOT` 新增 `bootstrap.php`

在 `bootstrap.php` 中配置时区

```php
date_default_timezone_set('Asia/Shanghai');
```

此时命令 `php easyswoole crontab show`  显示正常。

请问这样操作是否正确。可否统一在 `EasySwooleEvent.php` 配置即可。

**Comment by kiss291323003** [comment]
可以在boostrap事件添加
