### ISSUE TITLE
worker 进程处理业务之后不释放内存，内存占用不断上涨

### ISSUE THREAD

**Issue by danding-s** [easy-swoole/easyswoole#353]
mainServerCreate 里面没有进行任何操作
业务只有一个就是直接返回json
如下是配置
'SETTING' => [
            'worker_num' => 8,
            'reload_async' => true,
            'max_wait_time' => 3
        ],
        'TASK' => [
            'workerNum' => 4,
            'maxRunningNum' => 128,
            'timeout' => 15
        ]

以下是内存占用
4.875 MB                201 EasySwoole.TaskWorker
4.875 MB                202 EasySwoole.TaskWorker
4.875 MB                203 EasySwoole.TaskWorker
4.875 MB                204 EasySwoole.TaskWorker
9.03906 MB              193 EasySwoole.Worker.0
9.03906 MB              194 EasySwoole.Worker.1
9.03906 MB              195 EasySwoole.Worker.2
9.03906 MB              196 EasySwoole.Worker.3
9.03906 MB              197 EasySwoole.Worker.4
9.03906 MB              198 EasySwoole.Worker.5
9.03906 MB              199 EasySwoole.Worker.6
9.03906 MB              200 EasySwoole.Worker.7
33.5469 MB              187 EasySwoole

版本信息

main server                   SWOOLE_WEB
listen address                0.0.0.0
listen port                   9501
ip@eth0                       192.168.5.19
worker_num                    8
reload_async                  true
max_wait_time                 3
pid_file                      /tmp/pid.pid
log_file                      /mnt/e/www/ks/Log/swoole.log
user                          root
daemonize                     false
swoole version                4.5.2
php version                   7.3.19-1+ubuntu18.04.1+deb.sury.org+1
easy swoole                   3.3.4
develop/produce               develop

**Comment by kiss291323003** [comment]
内存到达一定的时候，会触发php的gc机制
