### ISSUE TITLE
接收vue传参问题

### ISSUE THREAD

**Issue by wanghanwanghan** [easy-swoole/easyswoole#359]
![isu](https://user-images.githubusercontent.com/23326001/86085860-d3f26c80-bad2-11ea-933c-1242ccb9a2c5.jpg)
用vue发送post传参时，如果不先执行$this->request()->getRequestParam()，直接执行$this->json()的话，就会报以上这个错。
如果先执行了$this->request()->getRequestParam()，再执行$this->json()就可以拿到$this->json()中的内容

**Comment by kiss291323003** [comment]
额、、、这看起来是前端的报错

**Comment by wanghanwanghan** [comment]
@kiss291323003 是前端的报错，但是直接前端同样的代码，单独执行getRequestParam的时候，什么都取不到，单独执行$this->json()的时候，就报错。先执行getRequestParam再执行json的时候，前端不报错，getRequestParam里无数据，json里可以拿到所有的数据

**Comment by xuhaoxian** [comment]
> @kiss291323003 是前端的报错，但是前端同样的代码，单独执行getRequestParam的时候，什么都取不到，单独执行$this->json()的时候，就报错。先执行getRequestParam再执行json的时候，前端不报错，getRequestParam里无数据，json里可以拿到所有的数据

这方法不会取body json数据  自己写个方法兼容下很简单的
