### ISSUE TITLE
任意地方调用Request $request/Response $response问题

### ISSUE THREAD

**Issue by 729343861** [easy-swoole/easyswoole#360]
开始自己写了个单例和注册器在EasySwooleEvent->onRequest 入口将请求和响应实例注册起来，然后在非控制器地方使用，常规使用没有啥问题，但是并发请求接口的时候就会出现部分响应为NULL，比如50次并发，有5次是正常响应数据，45次都响应的是NULL，然而改为BOX单例模式测试依旧如此，不知道如何解决。

注册实例
`
    public static function onRequest(Request $request, Response $response): bool
    {
        \App\Utility\Response::getInstance($request,$response);
        Box::instance('response',$response);
   }

`

封装响应类
`<?php

namespace App\Utility;

class Response
{
    static public function responseJson($code , $msg =""  ,$data = []){

            if(!is_string($msg)){
                $data = $msg;
                $msg  = "" ;
            }
            $data = json_encode([
                'code'=>$code,
                'msg'=> $msg?:\App\Consts\ErrorCode::ERROR_CODE_AND_ERORR_MSG[$code],
                'data'=> $data
            ]);
            $response =     Box::instance('response');
            $response->withHeader('Content-type','application/json;charset=utf-8');
            $response->withStatus(200);
            $response->write($data);
            $response->end();

    }
}`

**Comment by kiss291323003** [comment]
协成切换了解一下。这个需求请用上下文管理器。另外、、、你这样做是很不规范的。tp写多了。建议用参数传递
