### ISSUE TITLE
Redis  Hset() 函数跟原生的有区别，会把key 后面的field, value当做value 分别去存储。

### ISSUE THREAD

**Issue by letianll** [easy-swoole/easyswoole#371]
$RedisPool->hSet('offline_message_'.$info['to']['id'], time().mt_rand(1000,9999) ,json_encode($data));
                echo '以下是缓存信息';
                var_dump($RedisPool->hGetAll('offline_message_'.$info['to']['id']));

打印效果如下是一维数组，类似下面：
获取到的是array(30) {
  [0]=>
  string(14) "15947958465766"
  [1]=>
  string(211) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"222","cid":0,"mine":false,"fromid":10014,"timestamp":1594795846000}"
  [2]=>
  string(14) "15947970374964"
  [3]=>
  string(211) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"222","cid":0,"mine":false,"fromid":10014,"timestamp":1594797037000}"
  [4]=>
  string(14) "15947983393042"
  [5]=>
  string(211) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"111","cid":0,"mine":false,"fromid":10014,"timestamp":1594798339000}"
  [6]=>
  string(14) "15947971439453"
  [7]=>
  string(209) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"1","cid":0,"mine":false,"fromid":10014,"timestamp":1594797143000}"
  [8]=>
  string(14) "15947984238134"
  [9]=>
  string(215) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"0..0.0.","cid":0,"mine":false,"fromid":10014,"timestamp":1594798423000}"
  [10]=>
  string(14) "15947971476397"
  [11]=>
  string(211) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"222","cid":0,"mine":false,"fromid":10014,"timestamp":1594797147000}"
  [12]=>
  string(14) "15947984251107"
  [13]=>
  string(212) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"1111","cid":0,"mine":false,"fromid":10014,"timestamp":1594798425000}"
  [14]=>
  string(14) "15947972923698"
  [15]=>
  string(228) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"11111111111111111111","cid":0,"mine":false,"fromid":10014,"timestamp":1594797292000}"
  [16]=>
  string(14) "15947958465991"
  [17]=>
  string(211) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"333","cid":0,"mine":false,"fromid":10014,"timestamp":1594795846000}"
  [18]=>
  string(14) "15947970365223"
  [19]=>
  string(211) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"123","cid":0,"mine":false,"fromid":10014,"timestamp":1594797036000}"
  [20]=>
  string(14) "15947983383875"
  [21]=>
  string(211) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"000","cid":0,"mine":false,"fromid":10014,"timestamp":1594798338000}"
  [22]=>
  string(14) "15947972913422"
  [23]=>
  string(221) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"0000000000000","cid":0,"mine":false,"fromid":10014,"timestamp":1594797291000}"
  [24]=>
  string(14) "15947956253040"
  [25]=>
  string(212) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"2222","cid":0,"mine":false,"fromid":10014,"timestamp":1594795625000}"
  [26]=>
  string(14) "15947956231593"
  [27]=>
  string(212) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"1111","cid":0,"mine":false,"fromid":10014,"timestamp":1594795623000}"
  [28]=>
  string(14) "15947971493620"
  [29]=>
  string(212) "{"username":"\u524d\u7aef\u5de5\u7a0b\u5e08(10014)","avatar":"\/Static\/upload\/5d09c7da7bc97tx20218.jpg","id":10014,"type":"friend","content":"3333","cid":0,"mine":false,"fromid":10014,"timestamp":1594797149000}"
}

**Comment by tioncico** [comment]
```php
<?php
/**
 * Created by PhpStorm.
 * User: tioncico
 * Date: 2020-05-11
 * Time: 10:03
 */
include "../vendor/autoload.php";
use \EasySwoole\Redis\Redis;
use \EasySwoole\Redis\RedisConfig;
go(function () {
    $redis = new Redis(new \EasySwoole\Redis\Config\RedisConfig());
    $redis->hSet('b','a',json_encode(['a'=>123]));
    $redis->hSet('b','b',json_encode(['a'=>123]));
    $redis->hSet('b','c',json_encode(['a'=>123]));
    var_dump($redis->hGetAll('b'));
});

```

测试结果为:
array(3) {
  ["a"]=>
  string(9) "{"a":123}"
  ["b"]=>
  string(9) "{"a":123}"
  ["c"]=>
  string(9) "{"a":123}"
}
