### ISSUE TITLE
tcp easyswoole 设置heartbeat不生效

### ISSUE THREAD

**Issue by HB116** [easy-swoole/easyswoole#374]
因为tcp 的keepalived 不满足我的需求,所以使用了心跳检测

但是发现
tcp easyswoole 设置heartbeat心跳不生效 原生swoole可以 目前好像只能做easyswoole的手动心跳,求解  

个人见解,多次验证    求官方也验证一下

**Comment by kiss291323003** [comment]
你怎么设置的？？？？

**Comment by HB116** [comment]
> 你怎么设置的？？？？

已解决 搞错了   在dev设置就能解决了
