### ISSUE TITLE
redis链接池静置15分钟左右会不正常

### ISSUE THREAD

**Issue by yayashanzei** [easy-swoole/easyswoole#378]
版本 redis-pool 2.1.2 redis 1.3.3
  配置 ：$redisClusterPool = \EasySwoole\RedisPool\Redis::getInstance()->register('redis_cluster_101', new \EasySwoole\Redis\Config\RedisClusterConfig(
            EasyConfig::getInstance()->getConf('redis_cluster_101')[0],
            EasyConfig::getInstance()->getConf('redis_cluster_101')[1]
        ))->setMaxObjectNum(30)->setMinObjectNum(3)->setMaxIdleTime(15)->setGetObjectTimeout(3.0)->setIntervalCheckTime(3.0);

调用：$this->redisc = RedisPool::defer('redis_cluster_102');
$cats = $this->redisc->hGetAll('n:g:gc');

很大概率空，不是没数据的空，好像是链接池空了 setMinObjectNum(3) ，观察redis集群的负载均衡新建连接记录新增是0

旧版 redis-pool 2.0.10 redis 1.1.5 没有这个现象

从增加了ping的版本之后观察到有这个现象

**Comment by kiss291323003** [comment]
好的，我们这边测试看下

**Comment by tioncico** [comment]
你注册的是redis_cluster_101,可是你调用的是redis_cluster_102

**Comment by tioncico** [comment]
其次,你的调用方式并不对,使用的是$this->redisc = RedisPool::defer('redis_cluster_102');
对象属性赋值可能会出现问题

**Comment by yayashanzei** [comment]
我只是举个例子，实际注册的是102，不然不可能刚启动时是正常的

**Comment by yayashanzei** [comment]
> 你注册的是redis_cluster_101,可是你调用的是redis_cluster_102

我只是举个例子，实际使用中注册的是102，不然不会等10几分钟后才出问题

**Comment by tioncico** [comment]
1:不要使用$this->xxx=redis::defer  
2:如果还会出错,提供下报错信息
