### ISSUE TITLE
使用Mysql进程池方式批量添加数据，处理过滤不允许的字段有问题

### ISSUE THREAD

**Issue by TH-zhou** [easy-swoole/easyswoole#379]
批量添加数据，设置成一个表中不存在的字段：tel1
![image](https://user-images.githubusercontent.com/24542900/88266512-ea6e9b00-cd01-11ea-94fe-dd4e30b6833d.png)

model中封装了方法调用底层的 insertAll 方法
![image](https://user-images.githubusercontent.com/24542900/88266637-1ab63980-cd02-11ea-83ca-306ad97db680.png)

在过滤不存在的字段的时候，实现不了，并没有unset掉。如图：红框表示源码，篮框表示改后之后的代码
![image](https://user-images.githubusercontent.com/24542900/88266776-5c46e480-cd02-11ea-8b16-f551b3dcc60e.png)

**Comment by xuanyanwow** [comment]
已提交修复代码

**Comment by xuanyanwow** [comment]
后续更新版本即可
