### ISSUE TITLE
onBeforeInsert与insert方法调用的先后顺序

### ISSUE THREAD

**Issue by renweihua** [easy-swoole/easyswoole#381]
![image](https://user-images.githubusercontent.com/20264690/88474445-13d53400-cf59-11ea-8106-8a5477258aed.png)
beforeInsert事件的调用位置应该放到 insert方法之前才对阿！

**Comment by renweihua** [comment]
我无法在模型的onBeforeInsert方法，设置模型对应的属性值
![image](https://user-images.githubusercontent.com/20264690/88474480-63b3fb00-cf59-11ea-96b4-3f96ee84901a.png)

**Comment by renweihua** [comment]
$rawArray = $this->data;
其实应该放在他之前

**Comment by kiss291323003** [comment]
已经优化，感谢

**Comment by renweihua** [comment]
好的，感谢优化，我看看去
