### ISSUE TITLE
RPC使用protobuf传输数据响应2004或1003

### ISSUE THREAD

**Issue by paperen** [easy-swoole/easyswoole#383]
示例代码参见附件

按本地实际环境修改dev.php中的REDIS与SERVICE_CONF配置

`访问http://{ip}:9501/api/test`

[easyswoole-bug.zip](https://github.com/easy-swoole/easyswoole/files/4989667/easyswoole-bug.zip)

**Comment by kiss291323003** [comment]
已发现问题，是protobuf无法被json encode导致的，正在想办法处理中

**Comment by kiss291323003** [comment]
考虑到跨平台因素。如果需要传输二进制数据，建议对二进制数据做base64_encode、decode处理
