### ISSUE TITLE
kafka组件消息丢失

### ISSUE THREAD

**Issue by Laservdd** [easy-swoole/easyswoole#385]
使用kafka组件为生产者（v1.0），rdkafka扩展为消费者（rdkafka=v3.1.3，librdkafka=v0.11.6）
使用rdkafka的生产者和消费者都没有问题。
使用kafka组件生产消息时，往分区写入了消息，过一会分区的起始偏移量会被修改为写入偏移量
结果表现为起始偏移量大于消费者组提交的偏移量，测试消息积压的时候，重新启动消费者的话会丢失部分消息（提交偏移量~起始偏移量的部分）。

**Comment by huizhang001** [comment]
## 复现过程

#### 环境
es-kafka v1.0.4
rdkafka消费者v3.1.3
librdkafka: 我装的时候报错，所以用的最新版

#### 步骤
先es-kafka 开了5个客户端生产消息，生产消息20万左右

再开rdkafka一个进程开始消费

往复几遍并没有复现过程。

`可以+我qq具体聊下：2788828128`
