### ISSUE TITLE
orm事务操作,操作两张表以上,事务失效,遇到某个表错误了,另外两个表都插入了信息 (现在换成tp的orm 事务就是好的,请尽快的帮忙修复,不喜欢tp,喜欢es)

### ISSUE THREAD

**Issue by nanlongvip** [easy-swoole/easyswoole#387]
$data =[
            "contract_number"=>"0000001",
            "contract_name"=> "项目1",
            "customer_id"=> "1",
            "type"=>"1",
            "start_time"=>"2020-08-02",
            "end_time"=>"2020-08-10",
            "docking_user_id"=>"1",
            "business_and_amount"=>[["business_involved_id"=>2,"amount"=>1500],["business_involved_id"=>6,"amount"=>1500]],
            "income_and_pay_plan"=>[["amount"=>1500,"income_or_pay_time"=>"2020-08-10"],["amount"=>1500,"income_or_pay_time"=>"2020-08-15"]]
        ];
        try {
            //开启事务
            DbManager::getInstance()->startTransaction('aaa');
            $data['create_user_id'] = 1;
            $contract = ContractModel::create()->connection("aaa",false)->data($data,false);
            $action = $contract->save();
            //处理业务和金额$business_and_amount,遍历插入对应的合同id
            foreach ($data["business_and_amount"] as $k=>$item){
                $data["business_and_amount"][$k]['contract_id'] = $contract->id;
            }
            $contract_business_and_amount = ContractBusinessAndAmountModel::create()->connection("aaa",false);
            $action2 = $contract_business_and_amount->saveAll($data["business_and_amount"]);
            //处理财务收付计划$income_and_pay_plan,遍历插入对应的合同id
            foreach ($data["income_and_pay_plan"] as $k=>$item){
                $data["income_and_pay_plan"][$k]['contract_id'] = $contract->id;
                $data["income_and_pay_plan"][$k]['type'] = $data['type'];
            }
            $contract_income_and_pay_plan = ContractIncomeAndPayPlanModel::create()->connection("aaa",false);
            $action3 = $contract_income_and_pay_plan->saveAll($data["income_and_pay_plan"]);
            DbManager::getInstance()->commit("aaa");
            $this->writeJson(200, Status::CODE_OK, $contract->id, "操作成功");
        }catch (\Throwable $e) {
            //回滚事务
            DbManager::getInstance()->rollback("aaa");
            $this->writeJson(400, Status::CODE_OK, '', "操作失败");
        }

**Comment by gaobinzhan** [comment]
`saveAll`方法会自动`commit`，不需要自动提交使用：`saveAll([],true,false)`
