### ISSUE TITLE
response中的header默认是charset是gbk？

### ISSUE THREAD

**Issue by guihouchang** [easy-swoole/easyswoole#388]
`//$this->response()->withHeader('Content-type','application/json;charset=utf-8');

  $this->response()->write("呵呵呵");`
当没有设置字符集的时候输出的是乱码。

**Comment by kiss291323003** [comment]
默认是没有发送'Content-type'的

**Comment by guihouchang** [comment]
能确认的是一件事是当我处于乱码的时候，用网页转码成gbk，乱码就显示正常了
