### ISSUE TITLE
如何向自定义进程传递信息，更新内存配置表信息

### ISSUE THREAD

**Issue by leonshi001** [easy-swoole/easyswoole#389]
我打算向自定义的进程传递一个信号，然后让进程更新一下内存中的配置表信息，想到了两种方法，但都遇到了问题：
1、通过Process::kill（）传递SIGUSR1给自定义进程，但进行收到信息后就reload了，我不想重启进程，只是想更新内存中的配置表信息。
2、通过sendMessage（）向进程的onPipeReadable（）传递信息，但onPipeReadable没有接收到任何信息。代码如下：
`
$server = ServerManager::getInstance()->getSwooleServer(); 

$server->sendMessage("hello task process", 17);
`
我只是想更新内存的配置表信息，不要重启进程。请问我该怎么处理呀？

**Comment by kiss291323003** [comment]
Unix socket
