### ISSUE TITLE
使用 orm 链接池或者 mysqli链接池, 在 invoke 里 用 queryBuilder()->raw 方式执行 call 存储过程, 并发时会报错

### ISSUE THREAD

**Issue by fuzhufang** [easy-swoole/easyswoole#395]
报错的内容是: MySQL client is busy now on state#40, please use recv/fetchAll/nextResult to get all unread data and wait for response then try again#0

而如果把 queryBuilder()->raw 里的 call 语句 改为 这个存储过程了的 SQL 语句, 并发执行是不会报错的.

这条SQL 语句都是一样的 select count(*) from tab1; 

php7.2.24
swoole 版本: 4.4.19
es 版本: 3.3.7

**Comment by gaobinzhan** [comment]
请把`mysql`连接配置为`fetch_mode=true`,控制器代码需如下编写:
```php
$db->rawQuery("call add_account_proc_v1('002c3d76f952f5bf1271be1bf33771d8', '102', 'huawei', 'tmp', '002c3d76f952f5bf1271be1bf33771d8', 1, '2020-08-14 17:29:36')");
var_dump($db->mysqlClient()->fetchAll());
$db->mysqlClient()->nextResult();
```

**Comment by fuzhufang** [comment]
感谢大佬解答, 按您的提示修改, 能正常运行了!
