### ISSUE TITLE
orm修改返回受影响行数

### ISSUE THREAD

**Issue by mirgong** [easy-swoole/easyswoole#396]
修改成功能正常返回受影响函数，但是不修改信息，提交修改请求，lastQueryResult会返回一个null,获取不到受影响行数。原则上应该是受影响函数为0

**Comment by kiss291323003** [comment]
什么意思？？？有没有复现代码

**Comment by mirgong** [comment]
public function update_data(array $where,array $data)
    {
        $staff_info = StaffModel::where($where)->get();
        if(empty($staff_info)) return false;
        $staff_info->staff_name = Utils::iSet($data,'staff_name')?$data['staff_name']:$staff_info['staff_name'];
        $res = $staff_info->update();
        if($res) $update_Result  = $staff_info->lastQueryResult();
        return $update_Result?$update_Result->getAffectedRows():0;
    }
修改的时候，如果staff_name没有的值没有变，返回的lastQueryResult是空。没有受影响行数。

**Comment by kiss291323003** [comment]
因为值没有变，那就没有update的必要啊
