### ISSUE TITLE
rayswoole\core 注册的register_shutdown_function应该移动到EventRegister::onRequest里面

### ISSUE THREAD

**Issue by longx1001** [easy-swoole/easyswoole#397]
目前在registerErrorHandler里面，当出现不可捕获的异常时，会导致客户端无法得到响应（控制台有输出），最终504错误，因此要放到EventRegister::onRequest的闭包函数里面

swoole文档：[https://wiki.swoole.com/#/getting_started/notice?id=%e6%8d%95%e8%8e%b7server%e8%bf%90%e8%a1%8c%e6%9c%9f%e8%87%b4%e5%91%bd%e9%94%99%e8%af%af](https://wiki.swoole.com/#/getting_started/notice?id=%e6%8d%95%e8%8e%b7server%e8%bf%90%e8%a1%8c%e6%9c%9f%e8%87%b4%e5%91%bd%e9%94%99%e8%af%af)

**Comment by kiss291323003** [comment]
可以自行重新注册

**Comment by longx1001** [comment]
> 可以自行重新注册

实测，如果不是在onRequest里面注册没有任何作用

**Comment by kiss291323003** [comment]
你可以自己在onRequest实际注册回调，其次，这样其实是不合理的。这样导致每次请求，都注册了一次。另外，你说的不可捕获异常指的是？？？？es提供的全局异常你用了吗？另外。你们的客户端，一样需要写timeout。这个工作流程，不会变更的。

**Comment by longx1001** [comment]
> 你可以自己在onRequest实际注册回调，其次，这样其实是不合理的。这样导致每次请求，都注册了一次。另外，你说的不可捕获异常指的是？？？？es提供的全局异常你用了吗？另外。你们的客户端，一样需要写timeout。这个工作流程，不会变更的。

这个是在Controller里面调用连接池，连接池返回为空时报错的，core里面默认设置了异常捕捉，我通过var_dump打印实际是捕捉不到的

**Comment by kiss291323003** [comment]
不会捕获不到的。自己好好看文档、

**Comment by longx1001** [comment]
> 不会捕获不到的。自己好好看文档、

我在set_error_handler、register_shutdown_function、SysConst::HTTP_EXCEPTION_HANDLER、core类执行dispatch路由的catch里面、Dispatcher类的controllerHandler方法执行$controllerObject->__hook()的catch里面，Controller类的onException里面埋点打印，都没有打印出来
