### ISSUE TITLE
项目运行过程中会出现数据库连接错误，请问有高手指导下嘛，使用的是默认配置

### ISSUE THREAD

**Issue by lihao4455995** [easy-swoole/easyswoole#408]
[2020-10-10 18:46:30][debug][error] : [Uncaught EasySwoole\ORM\Exception\Exception: SQLSTATE[HY000] [2002]  in /easyswoole/vendor/easyswoole/orm/src/Db/MysqlPool.php:21
Stack trace:
#0 /easyswoole/vendor/easyswoole/pool/src/AbstractPool.php(297): EasySwoole\ORM\Db\MysqlPool->createObject()
#1 /easyswoole/vendor/easyswoole/pool/src/AbstractPool.php(255): EasySwoole\Pool\AbstractPool->initObject()
#2 /easyswoole/vendor/easyswoole/pool/src/AbstractPool.php(229): EasySwoole\Pool\AbstractPool->keepMin(2)
#3 {main}
  thrown at file:/easyswoole/vendor/easyswoole/orm/src/Db/MysqlPool.php line:21]

**Comment by kiss291323003** [comment]
断线问题，文档有。请看文档，谢谢
