### ISSUE TITLE
期望 validate 增加对数组及数组长度的验证！

### ISSUE THREAD

**Issue by codedart2018** [easy-swoole/easyswoole#409]
现实中前端会大量提交数组数据上来。目前验证都使用的自定义func. 希望可以有支持对数组验证是否长度和数组长度方法。这样相对更方便些。谢谢啦！

**Comment by gaobinzhan** [comment]
[https://github.com/easy-swoole/validate/blob/master/test/LengthTest.php](对数组长度)
[https://github.com/easy-swoole/validate/blob/master/test/LengthMinTest.php](对数组最小长度)
[https://github.com/easy-swoole/validate/blob/master/test/LengthMaxTest.php](对数组最大长度)

**Comment by codedart2018** [comment]
> [对数组长度](https://github.com/easy-swoole/validate/blob/master/test/LengthTest.php)
> [对数组最小长度](https://github.com/easy-swoole/validate/blob/master/test/LengthMinTest.php)
> [对数组最大长度](https://github.com/easy-swoole/validate/blob/master/test/LengthMaxTest.php)

补上 isArray吧

**Comment by gaobinzhan** [comment]
> > [对数组长度](https://github.com/easy-swoole/validate/blob/master/test/LengthTest.php)
> > [对数组最小长度](https://github.com/easy-swoole/validate/blob/master/test/LengthMinTest.php)
> > [对数组最大长度](https://github.com/easy-swoole/validate/blob/master/test/LengthMaxTest.php)
> 
> 补上 isArray吧

[](https://github.com/easy-swoole/validate/pull/22)

**Comment by codedart2018** [comment]
可否增加一个 array_key_exists 验证数组下标的方法。
场景
```
      $validator->addColumn('pre_sale')
        ->required('请完成预售数据填写')
        ->isArray('预售参数不正确')
        ->isArrayKeys('pre_sale_type', '预售方式参数不存在');
```
