### ISSUE TITLE
websocket ，push到socket缓冲区，怎么判断socket缓冲区的信息有推送到对端？

### ISSUE THREAD

**Issue by 523013183** [easy-swoole/easyswoole#416]
websocket ，push到socket缓冲区，怎么判断socket缓冲区的信息有推送到对端？
在不使用回执的情况下（因为回执也可能会丢）， 
有什么事件可以监听socket缓冲区的消息成功推送到对端

**Comment by kiss291323003** [comment]
现有的计算机体系，应用层是没有这个能力的知道的。你可以自己实现消息回执机制来确保对端收到。这一点可以参考MQTT协议里面的QOS质量控制，也是基于websocket+队列实现的消息at least once机制，确保对端一定能够收到
