### ISSUE TITLE
getUploadedFile() 获取的文件无法通过Aws S3 Api直接上传到minio存储服务中

### ISSUE THREAD

**Issue by 523013183** [easy-swoole/easyswoole#417]
`
$file = $this->request()->getUploadedFile("file");
//上传
$source =$file->getStream();
        $client = new S3Client([
            'version' => 'latest',
            'region'  => 'xm',
            'endpoint' => 'endpoint',
            'use_path_style_endpoint' => true,
            'credentials' => [
                'key' => accessKey,
                'secret' => secretKey,
            ]
        ]);

$upload->upload();
`

这样传上去的文件不可读。
我试了使用 
$file->moveTo();  //复制到本地
$source = fopen($file2, 'rb'); //在读取
$upload->upload();

这样又是可以上传的。 
是不兼容么？

**Comment by gaobinzhan** [comment]
`$file->getStream()`返回的是`EasySwoole\Http\Message\Stream`对象
