### ISSUE TITLE
关注多图文消息可以发送，关键字回复和默认回复多图文只能发送一条。

### ISSUE THREAD

**Issue by qr527906** [easy-swoole/easyswoole#422]
![image](https://user-images.githubusercontent.com/33110358/99354503-8770c780-28e1-11eb-98d4-abd76d2a7a5f.png)

**Comment by gaobinzhan** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html#5

**Comment by gaobinzhan** [comment]
图文消息个数；当用户发送文本、图片、语音、视频、图文、地理位置这六种消息时，开发者只能回复1条图文消息；其余场景最多可回复8条图文消息
