### ISSUE TITLE
session 无法使用，easyswoole/http  版本1.7.14.  session  为  null

### ISSUE THREAD

**Issue by qr527906** [easy-swoole/easyswoole#424]
![image](https://user-images.githubusercontent.com/33110358/99500844-e0119480-29b5-11eb-9a3c-764615d94d12.png)
1.存储session
![image](https://user-images.githubusercontent.com/33110358/99500927-fe779000-29b5-11eb-8483-de499868c62d.png)
2.取值
![image](https://user-images.githubusercontent.com/33110358/99501022-249d3000-29b6-11eb-86c1-1b52258ec373.png)
![image](https://user-images.githubusercontent.com/33110358/99501053-2ff05b80-29b6-11eb-8b58-2cb196950197.png)

**Comment by gaobinzhan** [comment]
建议你直接使用`session`组件，减少不必要的心智负担。
https://www.easyswoole.com/Cn/HttpServer/session.html

**Comment by qr527906** [comment]
> 你建议使用直接`session`组件，减少不必要的心智负担。
> https://www.easyswoole.com/Cn/HttpServer/session.html
更换了 session 还是一样的没有任何效果。  依然是null

**Comment by gaobinzhan** [comment]
发下你的代码和`easyswoole`版本

**Comment by qr527906** [comment]
> 发下你的代码和`easyswoole`版本
    if(time()<strtotime('2020-11-18 17:28:00'))
       {
           Session::getInstance()->set('aa','quan1234');
       }

        $a = Session::getInstance()->get('aa');

        println($a,'get aa');

**Comment by gaobinzhan** [comment]
> > 发下你的代码和`easyswoole`版本
> > if(time()<strtotime('2020-11-18 17:28:00'))
> > {
> > Session::getInstance()->set('aa','quan1234');
> > }
> 
> ```
>     $a = Session::getInstance()->get('aa');
> 
>     println($a,'get aa');
> ```

你加群发截图吧！我这根本不知道你在哪里调用的。

**Comment by qr527906** [comment]
> > > 发下你的代码和`easyswoole`版本
> > > if(time()<strtotime('2020-11-18 17:28:00'))
> > > {
> > > Session::getInstance()->set('aa','quan1234');
> > > }
> > 
> > 
> > ```
> >     $a = Session::getInstance()->get('aa');
> > 
> >     println($a,'get aa');
> > ```
> 
> 你加群发截图吧！我这根本不知道你在哪里调用的。

加了，请通过下   275050541

**Comment by kiss291323003** [comment]
session没有问题，你自己使用问题
