### ISSUE TITLE
生成带参数的二维码,二维码有效时间无效。

### ISSUE THREAD

**Issue by zmzkkk** [easy-swoole/easyswoole#425]
> $weChat = \App\Lib\Weixin::getInstance()->getWeChat();
    $qrCodeRequest = new QrCodeRequest();
    $qrCodeRequest->setExpireSeconds(3600);
    $qrCodeRequest->setActionName($qrCodeRequest::QR_SCENE);
    $scene = [
      "scene" => [
        "scene_id"  => $this->member['u_id'],
        "scene_str" => "shop_login"
      ]
    ];
    $qrCodeRequest->setActionInfo($scene);
    $qrCode = $weChat->officialAccount()->qrCode();
    $tick = $qrCode->getTick($qrCodeRequest);
    $res = $qrCode::tickToImageUrl($tick);
    $this->writeJson(Status::CODE_OK, $res , "success");

发现二维码很快就过期， 应该是默认的30秒

**Comment by gaobinzhan** [comment]
https://github.com/easy-swoole/wechat/pull/87
