### ISSUE TITLE
https://github.com/easy-swoole/wechat/pull/87

### ISSUE THREAD

**Issue by zmzkkk** [easy-swoole/easyswoole#427]
https://github.com/easy-swoole/wechat/pull/87

_Originally posted by @gaobinzhan in https://github.com/easy-swoole/easyswoole/issues/425#issuecomment-733436511_

**Comment by zmzkkk** [comment]
不行呀， 在117 行 就返回了 

`        if (!is_null($this->getActionInfo())) {
            return parent::toArray(['action_name', 'action_info']);
        }`

**Comment by zmzkkk** [comment]
上面  117 行 已经返回

>         if (!is_null($this->getActionInfo())) {
            return parent::toArray(['action_name', 'action_info']);
        }

**Comment by kiss291323003** [comment]
已经fix了
