### ISSUE TITLE
ORM字段预定义属性操作数据报错

### ISSUE THREAD

**Issue by pingstrong** [easy-swoole/easyswoole#428]
**模型设置**
protected $casts = [
        'key_value'     => 'json',
    ];
**数据库orm操作**
$key = 'web';
$val = ['address' => 'xxx', 'author' => 'pingo'];
Setting::create(['key_name' => $key, 'key_value' => $val])->save();

**返回结果：**

[debug][notice]:[Array to string conversion at file:/www/easyswoole/vendor/easyswoole/orm/src/Utility/PreProcess.php line:78

**Comment by pingstrong** [comment]
**表结构**
CREATE TABLE `common_setting` (
 `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `key_name` varchar(100) NOT NULL COMMENT '名称',
 `key_value` mediumtext NOT NULL COMMENT '内容',
 `created_at` int(11) NOT NULL,
 `updated_at` int(11) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COMMENT='公共配置表

**Comment by gaobinzhan** [comment]
https://github.com/easy-swoole/orm/pull/188

**Comment by pingstrong** [comment]
测试没问题了，可以把它更新到composer
