### ISSUE TITLE
php easyswoole start   启动失败

### ISSUE THREAD

**Issue by jiyutr** [easy-swoole/easyswoole#432]

**Comment by jiyutr** [comment]
找到了解决方案
php vendor/easyswoole/easyswoole/bin/easyswoole install    改用  php vendor/bin/easyswoole install
php easyswoole start  改用  php easyswoole  server  start

但是上面的提示不知道什么原因

**Comment by gaobinzhan** [comment]
https://github.com/easy-swoole/doc/blob/master/Cn/QuickStart/install.md
https://github.com/easy-swoole/doc/blob/master/Cn/Update/main.md
