### ISSUE TITLE
Crontab 提示类不存在

### ISSUE THREAD

**Issue by jiyutr** [easy-swoole/easyswoole#437]
public static function mainServerCreate(EventRegister $register)
    {
        /**
         * **************** Crontab任务计划 **********************
         */
        // 开始一个定时任务计划
        Crontab::getInstance()->addTask(TaskOne::class);
        // 开始一个定时任务计划
        Crontab::getInstance()->addTask(TaskTwo::class);
    }
执行   php easyswoole server restart -d
提示[debug][error]:[Class EasySwoole\EasySwoole\TaskOne does not exist at file:/home/wwwroot/easy2/vendor/easyswoole/easyswoole/src/Crontab/Crontab.php line:41]

[debug][error]:[Class EasySwoole\EasySwoole\TaskTwo does not exist at file:/home/wwwroot/easy2/vendor/easyswoole/easyswoole/src/Crontab/Crontab.php line:41]

这两个类放在了App文件下了

**Comment by gaobinzhan** [comment]
`use`
