### ISSUE TITLE
官方文档内容部分丢失了

### ISSUE THREAD

**Issue by jkaltopp** [easy-swoole/easyswoole#441]
比如依赖注入，没找到页面

**Comment by XueSiLf** [comment]
框架提供通过注解属性注入依赖的方式，详细请看 https://www.easyswoole.com/HttpServer/Annotation/property.html。
另外框架有提供在初始化时全局注入一些全局事件，详细请看 https://www.easyswoole.com/FrameDesign/event.html

**Comment by SuperLLT** [comment]
建议官方文档使用类似于laravel的官方文档，新版本出来之后不去修改之前的版本，而是新建一个版本的文档

**Comment by XueSiLf** [comment]
OK，这边考虑下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;MrTao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 上午10:17
收件人:&nbsp;&quot;easy-swoole/easyswoole&quot;<easyswoole@noreply.github.com&gt;;
抄送:&nbsp;&quot;huanghui&quot;<1592328848@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [easy-swoole/easyswoole] 官方文档内容部分丢失了 (#441)

**Comment by jkaltopp** [comment]
很喜欢这个框架，希望能一直维护下去。文档也可以按照版本去区分。

**Comment by kkstun** [comment]
> 很喜欢这个框架，希望能一直维护下去。文档也可以按照版本去区分。

附议

**Comment by XueSiLf** [comment]
这边会考虑的
