### ISSUE TITLE
3.x安装包错

### ISSUE THREAD

**Issue by Funny-dot** [easy-swoole/easyswoole#460]
第一个
dev.php 26行       LoggerInterface::LOG_LEVEL_DEBUG 静态属性不存在
第二个
[2021-02-25 13:44:02][console][error]:[EasySwoole\Task\Worker bind /www/wwwroot/
192.168.99.100/easyswoole/Temp/EasySwoole.TaskWorker.0.sock fail case Operation
not permitted at file:/www/wwwroot/192.168.99.100/easyswoole/vendor/easyswoole/c
omponent/src/Process/Socket/AbstractUnixProcess.php line:32]
[2021-02-25 13:44:02][console][error]:[EasySwoole\Task\Worker bind /www/wwwroot/
192.168.99.100/easyswoole/Temp/EasySwoole.TaskWorker.1.sock fail case Operation
not permitted at file:/www/wwwroot/192.168.99.100/easyswoole/vendor/easyswoole/c
omponent/src/Process/Socket/AbstractUnixProcess.php line:32]
[2021-02-25 13:44:02][console][error]:[EasySwoole\Task\Worker bind /www/wwwroot/
192.168.99.100/easyswoole/Temp/EasySwoole.TaskWorker.2.sock fail case Operation
not permitted at file:/www/wwwroot/192.168.99.100/easyswoole/vendor/easyswoole/c
omponent/src/Process/Socket/AbstractUnixProcess.php line:32]
[2021-02-25 13:44:02][console][error]:[EasySwoole\Task\Worker bind /www/wwwroot/
192.168.99.100/easyswoole/Temp/EasySwoole.TaskWorker.3.sock fail case Operation
not permitted at file:/www/wwwroot/192.168.99.100/easyswoole/vendor/easyswoole/c
omponent/src/Process/Socket/AbstractUnixProcess.php line:32]
PHP Fatal error:  Uncaught EasySwoole\Component\Process\Exception: EasySwoole\Br
idge\BridgeProcess bind /www/wwwroot/192.168.99.100/easyswoole/Temp/bridge.sock
fail case Operation not permitted in /www/wwwroot/192.168.99.100/easyswoole/vend
or/easyswoole/component/src/Process/Socket/AbstractUnixProcess.php:32
Stack trace:

**Comment by gaobinzhan** [comment]
第一个错是因为你的`composer`镜像有问题.
第二个错是因为没有权限.具体解决方案文档上有.
