### ISSUE TITLE
php easyswoole server start

### ISSUE THREAD

**Issue by szxiaokang** [easy-swoole/easyswoole#461]
**按照文档:**
启动框架
中途没有报错的话，执行：

# 启动框架
php easyswoole server start
此时可以访问 http://localhost:9501 就看到框架的欢迎页面，表示框架已经安装成功

**实际:**
yun@kube-slave1:/data/www/dev/easyswoole-3.x$ php easyswoole server start
  ______                          _____                              _
 |  ____|                        / ____|                            | |
 | |__      __ _   ___   _   _  | (___   __      __   ___     ___   | |   ___
 |  __|    / _` | / __| | | | |  \___ \  \ \ /\ / /  / _ \   / _ \  | |  / _ \
 | |____  | (_| | \__ \ | |_| |  ____) |  \ V  V /  | (_) | | (_) | | | |  __/
 |______|  \__,_| |___/  \__, | |_____/    \_/\_/    \___/   \___/  |_|  \___|
                          __/ |
                         |___/
Operation:
  php easyswoole start [arg1] [arg2]
Intro:
  to start current easyswoole server 
Arg:
  daemonize                    run in daemonize
  produce                      load produce.php

文档能否写的仔细点, 如此这般, 怎么敢用于生产环境

**Comment by kiss291323003** [comment]
文档是3.4.x的easyswoole。你这个是3.3.x版本的。很明显你的composer镜像过老或者是swoole版本太老导致拉取了低版本的easyswoole。请注意校对升级。或者到github看老版本的文档。谢谢

**Comment by szxiaokang** [comment]
我是按照你们的文档来操作的: https://www.easyswoole.com/QuickStart/install.html
我的php和swoole环境:
php7.4.15
swoole 4.6.3

**Comment by kiss291323003** [comment]
那请检查下你的composer镜像。最近阿里云的composer镜像经常抽风。建议换梯子+官方镜像

**Comment by szxiaokang** [comment]
好的, 3q
建议把可能的问题和解决的办法写在文档里, 因为一个团队如果学习一种框架, 应该是要到官网去看, 而不是前面踩坑的人把所有的坑都能记得和告诉后面的新人, 不然这个框架的学习成本就变高了

**Comment by kiss291323003** [comment]
额、、、、composer镜像抽风这个属于不可抗力因素。。。。

**Comment by szxiaokang** [comment]
他抽风是他的事情, 你把文档写清楚是你的事情
