### ISSUE TITLE
Could not open input file: vendor/easyswoole/easyswoole/bin/easyswoole

### ISSUE THREAD

**Issue by WangQuanTang** [easy-swoole/easyswoole#462]
*  php version：7.4.11
*  linux：unbuntu18.04
* framework：laravel8.12

I execute the command to install：
```
composer require easyswoole/easyswoole=3.x
```
It's Ok!And notice me:
```
Package manifest generated successfully.
79 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
But when I execute:
```
php vendor/easyswoole/easyswoole/bin/easyswoole install
```
then:
```
Could not open input file: vendor/easyswoole/easyswoole/bin/easyswoole
```
So I would like to ask the correct method of installation or how to solve this exception. Thank you!

**Comment by gaobinzhan** [comment]
Easywoole is a separate framework.Please see the document for the installation method.Document link as https://www.easyswoole.com/QuickStart/install.html
