### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by scauxiaoxu** [easy-swoole/easyswoole#465]
![image](https://user-images.githubusercontent.com/9588681/110094351-b0f12880-7dd6-11eb-8cc4-56e7296d4230.png)
文档中的 php vendor/bin/easyswoole install 安装不成功 

因为 vendor/bin/easyswoole中虽然设置了#!/usr/bin/env sh 但是由于前面声明了php解释器调用 在我电脑上不会按照sh 执行 (centos 7.6)  

改成使用 vendor/bin/easyswoole install 同时修改安装php脚本接口 

#464

**Comment by scauxiaoxu** [comment]
好像不是那个原因 是我虚拟机的问题 不过还是不能启动 

 thrown in /vagrant_data/test/php/easyswoole/vendor/easyswoole/component/src/Process/Socket/AbstractUnixProcess.php on line 32
[2021-03-05 18:04:16][debug][error]:[Uncaught EasySwoole\Component\Process\Exception: EasySwoole\Bridge\BridgeProcess bind /vagrant_data/test/php/easyswoole/Temp/bridge.sock fail case Operation not permitted in /vagrant_data/test/php/easyswoole/vendor/easyswoole/component/src/Process/Socket/AbstractUnixProcess.php:32

一直在报这个错 按照 php vendor/easyswoole/easyswoole/bin/easyswoole 启动

**Comment by gaobinzhan** [comment]
报错截图

**Comment by scauxiaoxu** [comment]
![image](https://user-images.githubusercontent.com/9588681/110127934-2d006600-7e01-11eb-8479-0da4a37d4e14.png)

第一次在虚拟机上安装没有成功 刚刚换了一台电脑安装成功了 

![image](https://user-images.githubusercontent.com/9588681/110128291-97b1a180-7e01-11eb-9df1-d60bb93e6829.png)

在虚拟机上/vendor 生成的这个文件不是这样子的

**Comment by scauxiaoxu** [comment]
看了下composer文档 应该是虚拟机下composer的问题
