### ISSUE TITLE
框架如何动态切换数据库

### ISSUE THREAD

**Issue by alive1944** [easy-swoole/easyswoole#469]
因为业务，要分库，有一张前置表通过，前置表来决定后续连接哪个数据库，然后每个数据库结构都是一样的，这种在框架里怎么处理，还是说现在框架无法支持这种？
easyswoole版本：3.3.7

**Comment by gaobinzhan** [comment]
https://www.easyswoole.com/Components/Orm/readWriteSeparation.html
https://www.easyswoole.com/Components/Orm/definitionModel.html
