### ISSUE TITLE
ORM 模型关联bug

### ISSUE THREAD

**Issue by SemiThin** [easy-swoole/easyswoole#478]
bug描述：
模型关联，使用获取器，非主键或者外键的时候是没问题的，这里的关联外键刚好使用了获取器，然后就出现bug了

user模型的数据获取不到了

```
$posts = PostsModel::create()->with(['user'])->limit(2)->all();
$posts = toArray($posts);
print_r($posts);
```

```
Array
(
    [0] => Array
        (
            [id] => 1
            [title] => 你们男生大部分喜欢什么样的女生？
            [content] => 这是内容
            [cover] =>
            [circle_id] => 5
            [user_id] => 1
            [type] => 1
            [spot] =>
            [likes] => 0
            [status] => 1
            [browse] => 3
            [create_time] => 1618825381
            [update_time] => 1618890406
        )

    [1] => Array
        (
            [id] => 2
            [title] => 情侣之间第一次睡在一起有什么感受？
            [content] =>这是内容
            [cover] =>
            [circle_id] => 90
            [user_id] => 278
            [type] => 1
            [spot] =>
            [likes] => 0
            [status] => 1
            [browse] => 0
            [create_time] => 1618825441
            [update_time] => 1618825441
        )

)

```

user 模型
```
namespace App\Model;
class UsersModel extends BaseModel
{
    protected $autoTimeStamp = true;
    protected $tableName = 'users';


    protected function getIdAttr($value)
    {
        return md5($value);
    }
}
```

posts模型

```
namespace App\Model;

class PostsModel extends BaseModel
{
    protected $tableName = 'posts';
    protected $autoTimeStamp = true;



    public function user()
    {
        return $this->hasOne(UsersModel::class, null, 'user_id', 'id');
    }
}
```

这是去掉Users模型获取器的结果集

```
Array
(
    [0] => Array
        (
            [id] => 1
            [title] => 你们男生大部分喜欢什么样的女生？
            [content] => 这是内容
            [cover] =>
            [circle_id] => 5
            [user_id] => 1
            [type] => 1
            [spot] =>
            [likes] => 0
            [status] => 1
            [browse] => 3
            [create_time] => 1618825381
            [update_time] => 1618890406
            [user] => Array
                (
                    [id] => 1
                    [mid] => 10369521
                    [mobile] => Z20wTjJ6a2xzQ3Y2bVRVdmhXd2tpZz09
                    [im_account] => 2021033010938
                    [name] => 吊车尾的
                    [avatar] => custom/avatar/1.png
                    [motto] => 个性不签名
                    [region_id] => 2
                    [industry_id] => 111
                    [cat_id] => Array
                        (
                            [0] => 1
                            [1] => 2
                            [2] => 3
                        )

                    [company] => 笑果文化有限公司
                    [position] => 导演
                    [school] => 清华大学
                    [major] =>
                    [sex] => 1
                    [birthday] => 1617778881
                    [status] => 1
                    [type] => 2
                    [create_time] => 1618393940
                    [update_time] => 1618987237
                )

        )

    [1] => Array
        (
            [id] => 2
            [title] => 情侣之间第一次睡在一起有什么感受？
            [content] =>这是内容
            [cover] =>
            [circle_id] => 90
            [user_id] => 278
            [type] => 1
            [spot] =>
            [likes] => 0
            [status] => 1
            [browse] => 0
            [create_time] => 1618825441
            [update_time] => 1618825441
            [user] => Array
                (
                    [id] => 278
                    [mid] => 10369856
                    [mobile] => Z20wTjJ6a2xzQ3NNT3RqaWcvVmsrdz09
                    [im_account] => 2021033137176
                    [name] => 熊瑞季
                    [avatar] => custom/avatar/278.png
                    [motto] =>
                    [region_id] => 2277
                    [industry_id] => 57
                    [cat_id] => Array
                        (
                        )

                    [company] => 深圳市意比思科技有限公司
                    [position] => 需求分析工程师
                    [school] =>
                    [major] =>
                    [sex] => 1
                    [birthday] => 0
                    [status] => 1
                    [type] => 2
                    [create_time] => 1618393940
                    [update_time] => 1618393940
                )

        )

)
```

**Comment by SemiThin** [comment]
这是去掉Users模型获取器的结果集

Array
(
    [0] => Array
        (
            [id] => 1
            [title] => 你们男生大部分喜欢什么样的女生？
            [content] => 这是内容
            [cover] =>
            [circle_id] => 5
            [user_id] => 1
            [type] => 1
            [spot] =>
            [likes] => 0
            [status] => 1
            [browse] => 3
            [create_time] => 1618825381
            [update_time] => 1618890406
            [user] => Array
                (
                    [id] => 1
                    [mid] => 10369521
                    [mobile] => Z20wTjJ6a2xzQ3Y2bVRVdmhXd2tpZz09
                    [im_account] => 2021033010938
                    [name] => 名字
                    [avatar] => https://bktimages.mtwo.cn/custom/avatar/1.png
                    [motto] => 个性不签名
                    [region_id] => 2
                    [industry_id] => 111
                    [cat_id] => Array
                        (
                            [0] => 1
                            [1] => 2
                            [2] => 3
                        )

                    [company] => 笑果文化有限公司
                    [position] => 导演
                    [school] => 清华大学
                    [major] =>
                    [sex] => 1
                    [birthday] => 1617778881
                    [status] => 1
                    [type] => 2
                    [create_time] => 1618393940
                    [update_time] => 1618987237
                )

        )

    [1] => Array
        (
            [id] => 2
            [title] => 情侣之间第一次睡在一起有什么感受？
            [content] =>这是内容
            [cover] =>
            [circle_id] => 90
            [user_id] => 278
            [type] => 1
            [spot] =>
            [likes] => 0
            [status] => 1
            [browse] => 0
            [create_time] => 1618825441
            [update_time] => 1618825441
            [user] => Array
                (
                    [id] => 278
                    [mid] => 10369856
                    [mobile] => Z20wTjJ6a2xzQ3NNT3RqaWcvVmsrdz09
                    [im_account] => 2021033137176
                    [name] => 熊瑞季
                    [avatar] => https://bktimages.mtwo.cn/custom/avatar/278.png
                    [motto] =>
                    [region_id] => 2277
                    [industry_id] => 57
                    [cat_id] => Array
                        (
                        )

                    [company] => 深圳市意比思科技有限公司
                    [position] => 需求分析工程师
                    [school] =>
                    [major] =>
                    [sex] => 1
                    [birthday] => 0
                    [status] => 1
                    [type] => 2
                    [create_time] => 1618393940
                    [update_time] => 1618393940
                )

        )

)

**Comment by kiss291323003** [comment]
sql解构和样本数据方便给下吗

**Comment by SemiThin** [comment]
> sql解构和样本数据方便给下吗

CREATE TABLE `posts` (
  `id` int NOT NULL,
  `title` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `cover` varchar(50) COLLATE utf8mb4_general_ci DEFAULT '',
  `circle_id` int NOT NULL,
  `user_id` int NOT NULL,
  `type` tinyint NOT NULL DEFAULT '1',
  `spot` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `likes` int NOT NULL DEFAULT '0',
  `status` int NOT NULL DEFAULT '1',
  `browse` int NOT NULL DEFAULT '0',
  `create_time` int NOT NULL,
  `update_time` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `posts` (`id`, `title`, `content`, `cover`, `circle_id`, `user_id`, `type`, `spot`, `likes`, `status`, `browse`, `create_time`, `update_time`) VALUES
(1, '你们男生大部分喜欢什么样的女生？', '这是内容', 'FsM1TeBlA-Nt286xtm1PXAgqs3CE', 5, 1, 1, '', 0, 1, 6, 1618825381, 1619077683),
(2, '情侣之间第一次睡在一起有什么感受？', '这是内容', 'FsM1TeBlA-Nt286xtm1PXAgqs3CE', 90, 2, 1, '', 0, 1, 1, 1618825441, 1619071070);

ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `posts`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;



CREATE TABLE `users` (
  `id` int NOT NULL,
  `mid` int NOT NULL,
  `mobile` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `im_account` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `name` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `avatar` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `motto` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '这个人很懒，什么都没有留下!',
  `region_id` smallint NOT NULL DEFAULT '0',
  `industry_id` smallint NOT NULL DEFAULT '0',
  `cat_id` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '[]',
  `company` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `position` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `school` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `major` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `sex` tinyint NOT NULL DEFAULT '10',
  `birthday` int NOT NULL DEFAULT '0',
  `status` tinyint NOT NULL DEFAULT '1',
  `type` tinyint NOT NULL DEFAULT '1',
  `create_time` int NOT NULL,
  `update_time` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` (`id`, `mid`, `mobile`, `im_account`, `name`, `avatar`, `motto`, `region_id`, `industry_id`, `cat_id`, `company`, `position`, `school`, `major`, `sex`, `birthday`, `status`, `type`, `create_time`, `update_time`) VALUES
(1, 10369521, 'Z20wTjJ6a2xzQ3Y2bVRVdmhXd2tpZz09', '2021033010938', '聂育菁', 'custom/avatar/1.png', '这个人很懒，什么都没有留下!', 2277, 45, '[]', '深圳南海商学院有限公司', '销售顾问', '', '', 0, 0, 1, 2, 1618393940, 1618393940),
(2, 19910134, 'Z20wTjJ6a2xzQ3MzSzVScXcvbDRWUT09', '2021033082405', '江菁琳', 'custom/avatar/2.png', '这个人很懒，什么都没有留下!', 2277, 49, '[]', '深圳市康慈体检有限公司', '销售经理', '', '', 0, 0, 1, 2, 1618393940, 1618393940);


ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `mid` (`mid`),
  ADD UNIQUE KEY `mobile` (`mobile`),
  ADD UNIQUE KEY `im_account` (`im_account`);


ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

**Comment by watsonhaw5566** [comment]
> bug描述：
> 模型关联，使用获取器，非主键或者外键的时候是没问题的，这里的关联外键刚好使用了获取器，然后就出现bug了
> 
> user模型的数据获取不到了
> 
> ```
> $posts = PostsModel::create()->with(['user'])->limit(2)->all();
> $posts = toArray($posts);
> print_r($posts);
> ```
> 
> ```
> Array
> (
>     [0] => Array
>         (
>             [id] => 1
>             [title] => 你们男生大部分喜欢什么样的女生？
>             [content] => 这是内容
>             [cover] =>
>             [circle_id] => 5
>             [user_id] => 1
>             [type] => 1
>             [spot] =>
>             [likes] => 0
>             [status] => 1
>             [browse] => 3
>             [create_time] => 1618825381
>             [update_time] => 1618890406
>         )
> 
>     [1] => Array
>         (
>             [id] => 2
>             [title] => 情侣之间第一次睡在一起有什么感受？
>             [content] =>这是内容
>             [cover] =>
>             [circle_id] => 90
>             [user_id] => 278
>             [type] => 1
>             [spot] =>
>             [likes] => 0
>             [status] => 1
>             [browse] => 0
>             [create_time] => 1618825441
>             [update_time] => 1618825441
>         )
> 
> )
> ```
> 
> user 模型
> 
> ```
> namespace App\Model;
> class UsersModel extends BaseModel
> {
>     protected $autoTimeStamp = true;
>     protected $tableName = 'users';
> 
> 
>     protected function getIdAttr($value)
>     {
>         return md5($value);
>     }
> }
> ```
> 
> posts模型
> 
> ```
> namespace App\Model;
> 
> class PostsModel extends BaseModel
> {
>     protected $tableName = 'posts';
>     protected $autoTimeStamp = true;
> 
> 
> 
>     public function user()
>     {
>         return $this->hasOne(UsersModel::class, null, 'user_id', 'id');
>     }
> }
> ```
> 
> 这是去掉Users模型获取器的结果集
> 
> ```
> Array
> (
>     [0] => Array
>         (
>             [id] => 1
>             [title] => 你们男生大部分喜欢什么样的女生？
>             [content] => 这是内容
>             [cover] =>
>             [circle_id] => 5
>             [user_id] => 1
>             [type] => 1
>             [spot] =>
>             [likes] => 0
>             [status] => 1
>             [browse] => 3
>             [create_time] => 1618825381
>             [update_time] => 1618890406
>             [user] => Array
>                 (
>                     [id] => 1
>                     [mid] => 10369521
>                     [mobile] => Z20wTjJ6a2xzQ3Y2bVRVdmhXd2tpZz09
>                     [im_account] => 2021033010938
>                     [name] => 吊车尾的
>                     [avatar] => custom/avatar/1.png
>                     [motto] => 个性不签名
>                     [region_id] => 2
>                     [industry_id] => 111
>                     [cat_id] => Array
>                         (
>                             [0] => 1
>                             [1] => 2
>                             [2] => 3
>                         )
> 
>                     [company] => 笑果文化有限公司
>                     [position] => 导演
>                     [school] => 清华大学
>                     [major] =>
>                     [sex] => 1
>                     [birthday] => 1617778881
>                     [status] => 1
>                     [type] => 2
>                     [create_time] => 1618393940
>                     [update_time] => 1618987237
>                 )
> 
>         )
> 
>     [1] => Array
>         (
>             [id] => 2
>             [title] => 情侣之间第一次睡在一起有什么感受？
>             [content] =>这是内容
>             [cover] =>
>             [circle_id] => 90
>             [user_id] => 278
>             [type] => 1
>             [spot] =>
>             [likes] => 0
>             [status] => 1
>             [browse] => 0
>             [create_time] => 1618825441
>             [update_time] => 1618825441
>             [user] => Array
>                 (
>                     [id] => 278
>                     [mid] => 10369856
>                     [mobile] => Z20wTjJ6a2xzQ3NNT3RqaWcvVmsrdz09
>                     [im_account] => 2021033137176
>                     [name] => 熊瑞季
>                     [avatar] => custom/avatar/278.png
>                     [motto] =>
>                     [region_id] => 2277
>                     [industry_id] => 57
>                     [cat_id] => Array
>                         (
>                         )
> 
>                     [company] => 深圳市意比思科技有限公司
>                     [position] => 需求分析工程师
>                     [school] =>
>                     [major] =>
>                     [sex] => 1
>                     [birthday] => 0
>                     [status] => 1
>                     [type] => 2
>                     [create_time] => 1618393940
>                     [update_time] => 1618393940
>                 )
> 
>         )
> 
> )
> ```

在外键上使用获取器是做了什么操作吗？

**Comment by XueSiLf** [comment]
> > sql解构和样本数据方便给下吗
> 
> CREATE TABLE `posts` (
> `id` int NOT NULL,
> `title` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
> `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
> `cover` varchar(50) COLLATE utf8mb4_general_ci DEFAULT '',
> `circle_id` int NOT NULL,
> `user_id` int NOT NULL,
> `type` tinyint NOT NULL DEFAULT '1',
> `spot` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
> `likes` int NOT NULL DEFAULT '0',
> `status` int NOT NULL DEFAULT '1',
> `browse` int NOT NULL DEFAULT '0',
> `create_time` int NOT NULL,
> `update_time` int NOT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
> 
> INSERT INTO `posts` (`id`, `title`, `content`, `cover`, `circle_id`, `user_id`, `type`, `spot`, `likes`, `status`, `browse`, `create_time`, `update_time`) VALUES
> (1, '你们男生大部分喜欢什么样的女生？', '这是内容', 'FsM1TeBlA-Nt286xtm1PXAgqs3CE', 5, 1, 1, '', 0, 1, 6, 1618825381, 1619077683),
> (2, '情侣之间第一次睡在一起有什么感受？', '这是内容', 'FsM1TeBlA-Nt286xtm1PXAgqs3CE', 90, 2, 1, '', 0, 1, 1, 1618825441, 1619071070);
> 
> ALTER TABLE `posts`
> ADD PRIMARY KEY (`id`);
> 
> ALTER TABLE `posts`
> MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
> 
> CREATE TABLE `users` (
> `id` int NOT NULL,
> `mid` int NOT NULL,
> `mobile` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
> `im_account` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
> `name` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
> `avatar` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
> `motto` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '这个人很懒，什么都没有留下!',
> `region_id` smallint NOT NULL DEFAULT '0',
> `industry_id` smallint NOT NULL DEFAULT '0',
> `cat_id` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '[]',
> `company` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
> `position` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
> `school` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
> `major` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
> `sex` tinyint NOT NULL DEFAULT '10',
> `birthday` int NOT NULL DEFAULT '0',
> `status` tinyint NOT NULL DEFAULT '1',
> `type` tinyint NOT NULL DEFAULT '1',
> `create_time` int NOT NULL,
> `update_time` int NOT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
> 
> INSERT INTO `users` (`id`, `mid`, `mobile`, `im_account`, `name`, `avatar`, `motto`, `region_id`, `industry_id`, `cat_id`, `company`, `position`, `school`, `major`, `sex`, `birthday`, `status`, `type`, `create_time`, `update_time`) VALUES
> (1, 10369521, 'Z20wTjJ6a2xzQ3Y2bVRVdmhXd2tpZz09', '2021033010938', '聂育菁', 'custom/avatar/1.png', '这个人很懒，什么都没有留下!', 2277, 45, '[]', '深圳南海商学院有限公司', '销售顾问', '', '', 0, 0, 1, 2, 1618393940, 1618393940),
> (2, 19910134, 'Z20wTjJ6a2xzQ3MzSzVScXcvbDRWUT09', '2021033082405', '江菁琳', 'custom/avatar/2.png', '这个人很懒，什么都没有留下!', 2277, 49, '[]', '深圳市康慈体检有限公司', '销售经理', '', '', 0, 0, 1, 2, 1618393940, 1618393940);
> 
> ALTER TABLE `users`
> ADD PRIMARY KEY (`id`),
> ADD UNIQUE KEY `mid` (`mid`),
> ADD UNIQUE KEY `mobile` (`mobile`),
> ADD UNIQUE KEY `im_account` (`im_account`);
> 
> ALTER TABLE `users`
> MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

这个是因为你使用了getIdAttr 获取器，本质上在使用关联查询得时候是不允许对这个主键使用获取器的。解决方法：先获取关联数据再对数据的 foreach 逐个处理id。
