### ISSUE TITLE
服务命令无效

### ISSUE THREAD

**Issue by qq690712575** [easy-swoole/easyswoole#481]
输入 php easyswoole server start -d
当我的服务已经在后台运行了一段时间后 
输入停止命令和强制停止 和其他的管理命令都提示下图
![QQ图片20210515095705](https://user-images.githubusercontent.com/17699491/118344950-eb5c0c00-b563-11eb-8f94-55bfbdf25f02.png)
connect server fail

**Comment by gaobinzhan** [comment]
说明你的`bridge`没有了.也就是`bridge`所监听的`unix socket`
