### ISSUE TITLE
安装lys/easy-swoole-rabbitmq后，注册了进程，后台查看内存使用情况（php easyswoole process show -d）,rabbitmq这个进程显示的内存消耗为0

### ISSUE THREAD

**Issue by codewgh** [easy-swoole/easyswoole#485]
php7.4.19
swoole 版本: 4.4.23
es 版本: 3.4.5

composer require lys/easy-swoole-rabbitmq（具体安装的明细过程请看https://packagist.org/packages/lys/easy-swoole-rabbitmq#v3.1）

class EasySwooleEvent implements Event
{

    public static function initialize()
    {
        // TODO: Implement initialize() method.
        date_default_timezone_set('Asia/Shanghai');
    }

    public static function mainServerCreate(EventRegister $register)
    {
         $driver = new RabbitMqQueueDriver('127.0.0.1', 5672, 'rabbitmq_test888', 'rabbitmq_test888',"/");
        MqQueue::getInstance($driver);
        $processConfig= new \EasySwoole\Component\Process\Config();
        $processConfig->setProcessGroup('Test');//设置进程组
        $processConfig->setArg(['a'=>123]);//传参
        $processConfig->setRedirectStdinStdout(false);//是否重定向标准io
        $processConfig->setPipeType($processConfig::PIPE_TYPE_SOCK_DGRAM);//设置管道类型
        $processConfig->setEnableCoroutine(true);//是否自动开启协程
        $processConfig->setMaxExitWaitTime(3);//最大退出等待时间
        $processConfig->setProcessName('MqQueueProcessComposer');
        //\EasySwoole\EasySwoole\ServerManager::getInstance()->addProcess(new MqQueueProcess($processConfig));
        \EasySwoole\Component\Process\Manager::getInstance()->addProcess(new MqQueueProcess($processConfig));
    }

    public static function onRequest(Request $request, Response $response): bool
    {
        // TODO: Implement onRequest() method.
        return true;
    }

    public static function afterRequest(Request $request, Response $response): void
    {
        // TODO: Implement afterAction() method.
    }
}

**Comment by tioncico** [comment]
https://github.com/1107012776/easy-swoole-rabbitmq/pull/4

**Comment by codewgh** [comment]
查看该进程的内存使用情况还是为0

**Comment by tioncico** [comment]
等5秒之后,协程切换出来就会有数据了,或者你在你自己实现的自定义进程前面增加个co::sleep(1),那等1秒就可以

**Comment by codewgh** [comment]
好的，懂了，谢谢
