### ISSUE TITLE
协成单例和Orm使用会报警告

### ISSUE THREAD

**Issue by ttoolc** [easy-swoole/easyswoole#491]
如果在model层继承了AbstractModel使用协成单例，协成CoroutineSingleTon下面的destroy方法会导致警告，可能是因为static，报错内容：
Declaration of EasySwoole\Component\CoroutineSingleTon::destroy(?int $cid = NULL) should be compatible with EasySwoole\ORM\AbstractModel::destroy($where = NULL, $allow = false)

**Comment by kiss291323003** [comment]
orm不能使用单例。涉及协程连接和上下文关系。另外你这个的报错是因为函数覆盖了，方法不对

**Comment by ttoolc** [comment]
可是我也只是实例化model层查询的时候用了下单例，这样用单例不是就不用一直new了

**Comment by ttoolc** [comment]
![image](https://user-images.githubusercontent.com/33118443/127609109-d1eee858-0f7f-4054-aaec-81b91e0c2020.png)
