### ISSUE TITLE
orm join 出来的SQL  缺少on

### ISSUE THREAD

**Issue by zhoufei666** [easy-swoole/easyswoole#493]
1.使用ORM 联表查询
2.在joinCondition 里面 and 其它条件，生成的sql 中，缺少 联表 的字符“on”
3.如果手动在joinCondition 里面 拼接 字符 “”on“”，生成的SQL就正确了
附上我的代码信息：
![image](https://user-images.githubusercontent.com/20034765/126753040-765f4c20-19ba-4707-97da-8d5af6b2e0ca.png)
![image](https://user-images.githubusercontent.com/20034765/126753094-6e34fc3f-058d-48d7-b6ec-c663f37b146b.png)
格式化的SQL
![image](https://user-images.githubusercontent.com/20034765/126753151-68045be9-6ee5-4ef1-9bd3-5ecdbe26704c.png)

我个人认为，即便是joinCondition后跟其它条件，也应该自动生成带on的SQL
不知是设计如此 还是隐形bug

**Comment by XueSiLf** [comment]
好的，感谢反馈，这边稍后处理下

**Comment by XueSiLf** [comment]
请提供一下相关表结构。

**Comment by kiss291323003** [comment]
亲，有表结构吗

**Comment by XueSiLf** [comment]
该bug已经处理，且发布新版本了。https://github.com/easy-swoole/mysqli/releases/tag/2.2.9
