### ISSUE TITLE
【建议】官方docker镜像没有PHP bcmath 扩展

### ISSUE THREAD

**Issue by SemiThin** [easy-swoole/easyswoole#496]
EasySwoole Pay
需要 bcmath 扩展

搞区块链也需要 bcmath 

能不能在docker镜像加上此扩展

![7 E `MFXFGFDI8)$IH9IJ$O](https://user-images.githubusercontent.com/12593507/129311835-dbf43e00-594d-419d-8497-d44bb753a0ea.png)

**Comment by SemiThin** [comment]
@kiss291323003

**Comment by XueSiLf** [comment]
好的，稍后我们加上

**Comment by XueSiLf** [comment]
已发布 
```bash
docker pull easyswoolexuesi2021/easyswoole

docker run -ti -p 9501:9501 easyswoolexuesi2021/easyswoole
```
