### ISSUE TITLE
 [FATAL ERROR]: all coroutines (count: 1) are asleep - deadlock!

### ISSUE THREAD

**Issue by AhmedAsser** [easy-swoole/easyswoole#497]
This Error occurs from time to time: 
```
#0  Swoole\Coroutine\MySQL->connect() called at [vendor/easyswoole/mysqli/src/Client.php:110]
#1  EasySwoole\Mysqli\Client->connect() called at [vendor/easyswoole/orm/src/Db/MysqlPool.php:18]
#2  EasySwoole\ORM\Db\MysqlPool->createObject() called at [vendor/easyswoole/pool/src/AbstractPool.php:304]
#3  EasySwoole\Pool\AbstractPool->initObject() called at [vendor/easyswoole/pool/src/AbstractPool.php:262]
#4  EasySwoole\Pool\AbstractPool->keepMin() called at [vendor/easyswoole/orm/src/Db/MysqlPool.php:62]
#5  EasySwoole\ORM\Db\MysqlPool->keepMin() called at [vendor/easyswoole/pool/src/AbstractPool.php:236]

```

Swoole Version => 4.7.1
easyswoole => 3.4.6
easyswoole/orm => 1.4.33

**Comment by kiss291323003** [comment]
that is swoole debug info ，not realy bug，just ignore it

**Comment by startloy** [comment]
> that is swoole debug info ，not realy bug，just ignore it

No , This will cause the redis or MySQL connect to fail

 [Coroutine-310]
--------------------------------------------------------------------
#0  Redis->get() called at [/data/code/vendor/hyperf/redis/src/RedisConnection.php:76]
#1  Hyperf\Redis\RedisConnection->__call() called at [/data/code/vendor/hyperf/redis/src/Redis.php:49]
#2  Hyperf\Redis\Redis->__call() called at [/data/code/app/Kernel/Redis.php:190]
#3  App\Kernel\Redis::get() called at [/data/code/app/Service/Models/Gamer.php:1421]
#4  App\Service\Models\Gamer->getHappyCardConf() called at [/data/code/app/Service/Traits/Common.php:561]
#5  App\Service\Logic->userIdentityCheck()
#6  call_user_func_array() called at [/data/code/runtime/container/proxy/App_Controller_GamerController.proxy.php:66]
#7  App\Controller\GamerController->runAction() called at [/data/code/app/Event/OnTask.php:301]
#8  App\Event\OnTask->onStart() called at [/data/code/app/Handler/TaskCallback.php:46]
ddz-slave-1    |
ddz-slave-1    |
===================================================================
 [FATAL ERROR]: all coroutines (count: 3) are asleep - deadlock!
===================================================================
