### ISSUE TITLE
多表join left  easyswoole 少字段

### ISSUE THREAD

**Issue by 2021-cm** [easy-swoole/easyswoole#499]
![5QS2MT1}{JWH2N5WL14({5M](https://user-images.githubusercontent.com/34293473/131102062-b6ca72b2-291a-4bc0-b732-0aa01b6e6feb.jpg)
![Uploading YKJ3$UQM`QNF`$TTCA{OIPH.jpg…]()
    function getList($where = [],$field = null,$page = 1,$limit = 10)
    {
        return DbManager::getInstance()->invoke(function ($client) use ($where,$field,$page,$limit){
            $model = self::invoke($client)->limit($limit*($page -1),$limit)->withTotalCount();
            $list = $model->join('member_add_info',' member_add_info.member_id = member.id','left')->join('department','department.id = member_add_info.department_id','left')->field($field)->all($where);
            $total = $model->lastQueryResult()->getTotalCount();
            return ['list'=>$list,'total'=>$total];
        });
    }

**Comment by XueSiLf** [comment]
你需要对all()方法得到的结果进行toArray(false,false)操作
