### ISSUE TITLE
框架的core文件返回 Class 'EasySwoole\Trigger\Location' not found

### ISSUE THREAD

**Issue by xwzmsdqbjzyyg** [easy-swoole/easyswoole#501]
框架运行一段时间后返回的错误信息,请问是哪里除了问题?
`
Fatal error: Uncaught Error: Class 'EasySwoole\Trigger\Location' not found in /home/dev-es.com/vendor/easyswoole/easyswoole/src/Core.php:198
Stack trace:

#0 /home/dev-es.com/vendor/composer/ClassLoader.php(444): EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}()
#1 /home/dev-es.com/vendor/composer/ClassLoader.php(444): include()
#2 /home/dev-es.com/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/dev-es.com/vendor/easyswoole/easyswoole/src/Core.php(211): spl_autoload_call()
#5 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}()
#6 {main}
  thrown in /home/dev-es.com/vendor/easyswoole/easyswoole/src/Core.php on line 198 
`

**Comment by xwzmsdqbjzyyg** [comment]
core文件出错附近的代码块是这样的
` 
   //在没有配置自定义错误处理器的情况下，转化为trigger处理

        $errorHandler = Di::getInstance()->get(SysConst::ERROR_HANDLER);
        if (!is_callable($errorHandler)) {
            $errorHandler = function ($errorCode, $description, $file = null, $line = null) {
                $l = new Location();    //第198行
                $l->setFile($file);
                $l->setLine($line);
                Trigger::getInstance()->error($description, $errorCode, $l);
            };
        }`

**Comment by Stitch-June** [comment]
你丢失文件了吧

**Comment by xwzmsdqbjzyyg** [comment]
> 你丢失文件了吧

没丢  还有个报错是是因为启动文件过多 . 我写了一个每200毫秒执行一次的定时器方法,里面有一个go函数,我把go函数去掉就恢复正常了,请问这是什么问题...

**Comment by Stitch-June** [comment]
你不贴代码 我也不知道。。。
