### ISSUE TITLE
Time获取日 开始时间戳 和 结束时间戳 要少一天

### ISSUE THREAD

**Issue by dalangll** [easy-swoole/easyswoole#511]
**当参数为日期格式返回时间戳少一天**

```
use EasySwoole\Utility\Time;
$start = Time::startTimestamp('2021-10-05');
$end = Time::endTimestamp('2021-10-05');

$st_date = date("y-m-d H:i:s",$start);
$en_date = date("y-m-d H:i:s",$end);

return $this->writeJson(200,'success',[$start,$end,$st_date,$en_date]);
```
![image](https://user-images.githubusercontent.com/31510856/138849422-4e40e6c3-ee50-4a76-b23e-176a5c2319f0.png)

**Comment by shoushouxiongying** [comment]
怀疑你的时间区没设置

**Comment by dalangll** [comment]
EasySwooleEvent文件 有设置 date_default_timezone_set('Asia/Shanghai');的



在 2021-11-15 16:37:11，"shoushouxiongying" ***@***.***> 写道：

怀疑你的时间区没设置

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XueSiLf** [comment]
是不是你数据库服务端时区的问题。

**Comment by dalangll** [comment]
已修复
