### ISSUE TITLE
EasySwoole\Component\Process\Manager的table hash字段有问题

### ISSUE THREAD

**Issue by djwjiawei** [easy-swoole/easyswoole#515]
spl_object_hash($process)返回的是一个字符串，但是Manager中的table hash字段设的是int型

导致table中的hash存储的是错的， 根据Manager::getInstance()->getProcessByPid() 就获取不到对应的process对象了

 php easyswoole process show -d 的截图信息，hash字段是不对的
![image](https://user-images.githubusercontent.com/19905508/143383456-39e0382e-d866-4530-8e33-2297354d6a6b.png)

**Comment by XueSiLf** [comment]
好的，这边稍后就处理。感谢反馈。

**Comment by XueSiLf** [comment]
这个问题已经修复了，在3.4.6版本。请提供下你的版本。
