### ISSUE TITLE
文档内容错误

### ISSUE THREAD

**Issue by HeiPiKD** [easy-swoole/easyswoole#518]
”事务
<img width="654" alt="螢幕截圖 2021-11-29 下午6 41 40" src="https://user-images.githubusercontent.com/42072329/143853627-80f863b3-1dc7-4874-81fd-8567fa93c7c7.png">
“

**Comment by XueSiLf** [comment]
好的，马上处理。感谢反馈。

**Comment by XueSiLf** [comment]
请问您说的具体问题在哪？

**Comment by XueSiLf** [comment]
已修正
