### ISSUE TITLE
php8下面easyswoole运行报错，详情见正文。

### ISSUE THREAD

**Issue by xiangdong2** [easy-swoole/easyswoole#519]
"require": {
        "php": ">=7.2",
        "ext-swoole": ">=4.0.3",
        "easyswoole/easyswoole": ">=3.3.4",

#php -d swoole.use_shortname=On easyswoole start dev
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /data/www/l.lexxx.com/vendor/easyswoole/spl/src/SplBean.php on line 111
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /data/www/l.lexxx.com/vendor/easyswoole/spl/src/SplBean.php on line 254
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /data/www/l.lexxx.com/vendor/easyswoole/spl/src/SplBean.php on line 272
PHP Fatal error:  Declaration of EasySwoole\Spl\SplArray::asort(): EasySwoole\Spl\SplArray must be compatible with ArrayObject::asort(int $flags = SORT_REGULAR) in /data/www/l.lexxx.com/vendor/easyswoole/spl/src/SplArray.php on line 137

[root@nexus-repo-10-10-0-109:/data/www/l.lexxx.com]
#php -v
PHP 8.0.2 (cli) (built: Mar  5 2021 03:28:07) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

**Comment by XueSiLf** [comment]
好的，感谢反馈，这边马上处理。

**Comment by XueSiLf** [comment]
请升级你的easyswoole版本到3.3.7
```bash
composer require easyswoole/easyswoole=3.3.7
```
，或者尝试升级easyswoole/spl组件
```bash
composer require easyswoole/spl
```
。
