### ISSUE TITLE
使用较高版本的composer安装，框架会启动失败

### ISSUE THREAD

**Issue by hejianfei9527** [easy-swoole/easyswoole#522]
版本信息:
composer version 2.2.4
php version 7.4.27
swoole version 4.4.23
easyswoole version 3.4.6

错误信息:
PHP Fatal error:  Namespace declaration statement has to be the very first statement or after any declare call in the script in  /vendor/bin/easyswoole on line 13

**Comment by XueSiLf** [comment]
好的，感谢反馈。你可以把 /vendor/bin/ 目录下面的 easyswoole  文件的第一行 ```!# /usr/bin/env php``` 这行删除就可以了。我们会在不久后发布新版本修复这个问题。

**Comment by XueSiLf** [comment]
您好，方便的话，请加我qq：1592328848，easyswoole需要您的帮助

**Comment by XueSiLf** [comment]
您好，方便的话，请加我qq：1592328848，easyswoole需要您的帮助
