### ISSUE TITLE
Websocket使用了onClose事件后如何区分是否为ws连接？

### ISSUE THREAD

**Issue by kyour-cn** [easy-swoole/easyswoole#530]
在Http和Websocket共存的项目，使用了onClose事件监听。
当有http请求结束也会触发onClose，请问我该如何区分该断开的连接是什么类型呢？

**Comment by kyour-cn** [comment]
if ($ws instanceof \Swoole\Http\Server) {
                //去除http请求
                return;
            }

**Comment by YiwanGi** [comment]
> ```
>         if ($ws instanceof \Swoole\Http\Server) {
>             //去除http请求
>             return;
>         }
> ```
![QN68PA}XP1}Z1J KVH RLHR](https://user-images.githubusercontent.com/69124377/165909739-4d383721-3430-4d55-af8f-849cfac393d5.png)
