### ISSUE TITLE
按照文档里面配置全局变量 出现错误

### ISSUE THREAD

**Issue by LOVE2CMOL** [easy-swoole/easyswoole#532]
http://www.easyswoole.com/HttpServer/global.html
环境是WSL2

直接Copy文档的代码

请求接口报错

````
Call to undefined function EasySwoole\Spl\defer()
#0 /mnt/d/mygit/BlueSkyProject/server/easyswoole/vendor/easyswoole/spl/src/SplContextArray.php(83): EasySwoole\Spl\SplContextArray->cid()
#1 /mnt/d/mygit/BlueSkyProject/server/easyswoole/EasySwooleEvent.php(35): EasySwoole\Spl\SplContextArray->loadArray()
#2 [internal function]: EasySwoole\EasySwoole\EasySwooleEvent::EasySwoole\EasySwoole\{closure}()
#3 /mnt/d/mygit/BlueSkyProject/server/easyswoole/vendor/easyswoole/easyswoole/src/Core.php(262): call_user_func()
#4 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}()
#5 {main}
````

····
main server                   SWOOLE_WEB
listen address                0.0.0.0
listen port                   9501
worker_num                    8
reload_async                  true
max_wait_time                 30
pid_file                      /tmp/pid.pid
log_file                      /tmp/EasySwooleLog/swoole.log
user                          love2cmol
swoole version                4.8.8
php version                   8.1.3
easyswoole version            3.5.1
run mode                      dev
temp dir                      /tmp
log dir                       /tmp/EasySwooleLog
····

![image](https://user-images.githubusercontent.com/28857775/159109191-07fdb3d2-9c02-4642-9a19-a38772179ef7.png)
![image](https://user-images.githubusercontent.com/28857775/159112171-ee214702-bd91-4f8e-a646-b901f0bfd23e.png)
![image](https://user-images.githubusercontent.com/28857775/159109206-01374585-02b0-41ed-b86e-ce862f666744.png)
![image](https://user-images.githubusercontent.com/28857775/159109324-1754d252-4009-403d-9378-3a011bdf6061.png)
![image](https://user-images.githubusercontent.com/28857775/159109348-4f1cb5c9-6d92-4741-b4c0-9a7e82536cda.png)

**Comment by LOVE2CMOL** [comment]
![image](https://user-images.githubusercontent.com/28857775/159113618-833dd085-0bdc-4d88-b731-7cbb7f575fec.png)
这玩意改成这样
![image](https://user-images.githubusercontent.com/28857775/159113598-6135dfe7-0a0e-49a7-8b7c-1de7d78bb8c5.png)
就可以跑了

但我不知道会不会出问题 🤣🤣🤣🤣🤣  下

刚刚接触swoole  准备拿来做微服务 还有一坨shi山准备迁移过来😂😂

**Comment by Stitch-June** [comment]
打开你`swoole`的短命名

**Comment by LOVE2CMOL** [comment]
> 

万分感谢 弄好了
