### ISSUE TITLE
crontab info is abnormal.

### ISSUE THREAD

**Issue by LOVE2CMOL** [easy-swoole/easyswoole#533]
配置文件关联下这个问题，环境是WSL2
[#532 ](https://github.com/easy-swoole/easyswoole/issues/532#issue-1174185403)

server/easyswoole/Fix/SplContextArray.php 这个是我为了修复[#532](https://github.com/easy-swoole/easyswoole/issues/532#issue-1174185403)的报错拖出来改了下代码，[#532](https://github.com/easy-swoole/easyswoole/issues/532#issuecomment-1072968210)里面有具体代码，但是改回原来文件依旧报错

![image](https://user-images.githubusercontent.com/28857775/159136330-d156ea36-cbf1-4658-bc78-b3e894eb8f50.png)

**Comment by jansen-s** [comment]
我也遇到crontab info is abnormal.的问题

**Comment by LOVE2CMOL** [comment]
> 我也遇到crontab info is abnormal.的问题

有解决方法吗 有的话踢我一脚🤣🤣🤣🤣

**Comment by XueSiLf** [comment]
fixed #543

**Comment by XueSiLf** [comment]
已经修复了，很抱歉，是文档戏弄错了的问题（只需要把 \EasySwoole\Crontab\Crontab 类 替换为 \EasySwoole\EasySwoole\Crontab\Crontab 类即可）。最新文档详见：https://www.easyswoole.com/BaseUsage/crontab.html

**Comment by LOVE2CMOL** [comment]
验证可行
