### ISSUE TITLE
crontab文档可能存在错误 请确认下

### ISSUE THREAD

**Issue by LOVE2CMOL** [easy-swoole/easyswoole#546]
https://www.easyswoole.com/BaseUsage/crontab.html
完整使用示例代码
在 EasySwoole 中使用
第2点

最后一行 
$crontab->attachToServer(ServerManager::getInstance()->getSwooleServer());

如果添加这一行 
任务到时间后会重复运行 
但是用指令执行正常
![image](https://user-images.githubusercontent.com/28857775/171996455-417c79ed-9114-4b05-8fa3-793c3aa26688.png)

代码直接取示例的代码即可验证

#533 之前按照这个任务改了 \EasySwoole\Crontab\Crontab 类 替换为 \EasySwoole\EasySwoole\Crontab\Crontab 类 这个问题才显现出来

**Comment by XueSiLf** [comment]
感谢反馈，文档已经修复。

**Comment by LOVE2CMOL** [comment]
> 感谢反馈，文档已经修复。

具体修改了什么地方？
 这边在确认的时候没有看见改动 也看了下[doc那边的提交](https://github.com/easy-swoole/doc/commit/3b026bf8a2253dd3402ffd8ae0d03a0500f9c24e) 只看到了11天前改动了<注册 Crontab>部分 《完整使用示例代码》部分并没有更改

**Comment by XueSiLf** [comment]
文档删除了这行 $crontab->attachToServer(ServerManager::getInstance()->getSwooleServer());

**Comment by XueSiLf** [comment]
因为框架底层已经自动加了，所以使用的时候我们不需要加这行

**Comment by XueSiLf** [comment]
> > 感谢反馈，文档已经修复。
> 
> 具体修改了什么地方？ 这边在确认的时候没有看见改动 也看了下[doc那边的提交](https://github.com/easy-swoole/doc/commit/3b026bf8a2253dd3402ffd8ae0d03a0500f9c24e) 只看到了11天前改动了<注册 Crontab>部分 《完整使用示例代码》部分并没有更改

 是删除了 文档没更新

**Comment by XueSiLf** [comment]
> > 感谢反馈，文档已经修复。
> 
> 具体修改了什么地方？ 这边在确认的时候没有看见改动 也看了下[doc那边的提交](https://github.com/easy-swoole/doc/commit/3b026bf8a2253dd3402ffd8ae0d03a0500f9c24e) 只看到了11天前改动了<注册 Crontab>部分 《完整使用示例代码》部分并没有更改

我更新下

**Comment by LOVE2CMOL** [comment]
> 已重新提交 [easy-swoole/doc#195](https://github.com/easy-swoole/doc/pull/195)

已经确认 感谢
