### ISSUE TITLE
http 服务无响应

### ISSUE THREAD

**Issue by coding-lover** [easy-swoole/easyswoole#548]
1、检查日志没发现报错
2、查看了 netstat 发现了下面情况
[root@ai ~]# netstat -n | grep 9501 | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a,S[a]}'
CLOSE_WAIT 20199
ESTABLISHED 576
3、不知道是什么原因造成 http 服务无法响应的，然后重启下 easyswoole, 就正常了

有没遇到类似情况？

**Comment by coding-lover** [comment]
您好，您发的邮件我已收到，谢谢。

**Comment by coding-lover** [comment]
启动 easyswoole ， 过几天后， 就会偶尔出现这种情况

**Comment by XueSiLf** [comment]
> 启动 easyswoole ， 过几天后， 就会偶尔出现这种情况

可以提供下您的php版本和使用的swoole版本吗？可以加我们的官方群 https://www.easyswoole.com/Preface/contact.html 然后然后 加我私聊 我帮您看看

**Comment by coding-lover** [comment]
大佬，你的qq昵称是哪个？

**Comment by XueSiLf** [comment]
XueSi



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月10日(周五) 下午5:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [easy-swoole/easyswoole] http 服务无响应 (Issue #548)




 
大佬，你的qq昵称是哪个？

**Comment by XueSiLf** [comment]
EasySwoole-XueSi

**Comment by laumin** [comment]
@XueSiLf 你好，我也碰到这个问题，是什么原因能有查出来吗，能否分享下，谢谢

**Comment by coding-lover** [comment]
您好，您发的邮件我已收到，谢谢。

**Comment by XueSiLf** [comment]
> @XueSiLf 你好，我也碰到这个问题，是什么原因能有查出来吗，能否分享下，谢谢

好的 我帮你看看

**Comment by XueSiLf** [comment]
> 1、检查日志没发现报错 2、查看了 netstat 发现了下面情况 [root@ai ~]# netstat -n | grep 9501 | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a,S[a]}' CLOSE_WAIT 20199 ESTABLISHED 576 3、不知道是什么原因造成 http 服务无法响应的，然后重启下 easyswoole, 就正常了
> 
> 有没遇到类似情况？

你好 请问您是不是配置max_request参数 这个参数请去掉配置
