### ISSUE TITLE
文档链接404

### ISSUE THREAD

**Issue by c608345** [easy-swoole/easyswoole#551]
https://www.easyswoole.com/HttpServer/Annotation/property.html  下一个条目  CircuitBreaker 注解

HTTP服务 -> 注解处理 ->   CircuitBreaker 注解  404
https://www.easyswoole.com/HttpServer/Annotation/HttpServer/Annotation/circuitBreaker.md

**Comment by XueSiLf** [comment]
好的，这边马上补充下。

**Comment by lovejc1314** [comment]
已修正。https://github.com/easy-swoole/doc/pull/196
