### ISSUE TITLE
关于支持 php8.1& swoole 4.8

### ISSUE THREAD

**Issue by WangNingkai** [easy-swoole/easyswoole#556]
![image](https://user-images.githubusercontent.com/23030927/180899656-58ca28bc-4240-4fc4-a09c-6be28837cd2d.png)
使用如上环境、会出现报错，通过修改port=0可以解决此问题，备注：用的 swoole-cli

**Comment by XueSiLf** [comment]
好的，感谢反馈。稍后修复。

**Comment by XueSiLf** [comment]
https://github.com/easy-swoole/crontab/pull/4 已在解决路上

**Comment by kiss291323003** [comment]
已经解决

**Comment by WangNingkai** [comment]
> 已经解决

好像unixclent都会存在这个问题呢，包括异步任务
