### ISSUE TITLE
全新安装的es 3.5.1版本 启动报错：Swoole\Coroutine\Socket::setOption(): setsockopt(27) failed, Error: Invalid argument[22]

### ISSUE THREAD

**Issue by landso** [easy-swoole/easyswoole#566]
全新安装3.5.1版本，安装时自动生成了Index.php 和 Router.php, 启动报错如下，传入Socket::setOption()的参数一并打印如下：

> main server                   SWOOLE_WEB
listen address                0.0.0.0
listen port                   9501
worker_num                    8
reload_async                  true
max_wait_time                 3
pid_file                      /home/andy/swoole_test/Temp/pid.pid
log_file                      /home/andy/swoole_test/Log/swoole.log
user                          root
swoole version                4.8.12
php version                   7.4.3
easyswoole version            3.5.1
run mode                      dev
temp dir                      /home/andy/swoole_test/Temp
log dir                       /home/andy/swoole_test/Log
[2023-02-02 03:31:19][trigger][warning]:[Swoole\Coroutine\Socket::setOption(): setsockopt(27) failed, Error: Invalid argument[22] at file:/home/andy/swoole_test/vendor/easyswoole/component/src/Process/Socket
/AbstractUnixProcess.php line:31]
SOL_SOCKET: 1
SO_LINGER: 13
$this->getConfig()->getLinger(): array (
  'l_linger' => 0,
  'l_onoff' => 0,
)

**Comment by mrotaku-yb** [comment]
mark一下, 同问, 配置如下:
main server                   SWOOLE_WEB_SOCKET
listen address                0.0.0.0
listen port                   9502
worker_num                    4
reload_async                  true
task_enable_coroutine         true
max_wait_time                 3
pid_file                      /www/wwwroot/esaySwoole/Temp/pid.pid
log_file                      /www/wwwroot/esaySwoole/Log/swoole.log
user                          www
swoole version                5.0.1
php version                   8.1.13
easyswoole version            3.5.1
run mode                      dev
temp dir                      /www/wwwroot/esaySwoole/Temp
log dir                       /www/wwwroot/esaySwoole/Log
[2023-09-19 18:22:13][trigger][warning]:[Swoole\Coroutine\Socket::setOption(): setsockopt(27) failed, Error: Invalid argument[22] at file:/www/wwwroot/esaySwoole/vendor/easyswoole/component/src/Process/Soc
ket/AbstractUnixProcess.php line:30]

**Comment by XueSiLf** [comment]
你好，这个是因为你使用 Windows Sub Linux V1 （WSL1）子系统导致的，请使用 WSL2。
