### ISSUE TITLE
swoole 5.x 无法安装最新版本

### ISSUE THREAD

**Issue by rockys-code** [easy-swoole/easyswoole#569]
由于 `easyswoole/component ` 依赖 `ext-swoole ^4.4.2`,  导致`swoole 5.x`  只能使用支持 `easyswoole/component 1.0.0` 的 `3.2.6` 版本,无法升级.

不知道这是因为 `easyswoole/component` 不支持 `swoole 5.x`, 还是它的版本依赖有问题.

**Comment by chengdutax** [comment]
是的,确实无法安装最新版

**Comment by shengdoushi** [comment]
同部, 官方有升级更新计划吗?

**Comment by XueSiLf** [comment]
> 由于 `easyswoole/component ` 依赖 `ext-swoole ^4.4.2`, 导致`swoole 5.x` 只能使用支持 `easyswoole/component 1.0.0` 的 `3.2.6` 版本,无法升级.
> 
> 不知道这是因为 `easyswoole/component` 不支持 `swoole 5.x`, 还是它的版本依赖有问题.

你好，官方现在已经修复了。

**Comment by XueSiLf** [comment]
> 同部, 官方有升级更新计划吗?

你好，官方现在已经修复了。

**Comment by XueSiLf** [comment]
easyswoole/component 2.0 已兼容 swoole 5.x 版本。
