### ISSUE TITLE
使用ORM当数据库为doris时报错

### ISSUE THREAD

**Issue by dongyule** [easy-swoole/easyswoole#574]
$data = DwsProductVideoSaleModel::create()
            ->where('product_id', '1729384061098168377')
            ->order('video_qty', 'DESC')
            ->limit(10)
            ->all();
        print_r($data);

        报错如下：
        SQLSTATE[08S01] [1047] Unsupported command(COM_STMT_PREPARE) [show full columns from dws_product_video_sale_all]

**Comment by XueSiLf** [comment]
你好，我们的orm可能不支持这个doris数据库

**Comment by XueSiLf** [comment]
> ```
>     $data = DwsProductVideoSaleModel::create()
>         ->where('product_id', '1729384061098168377')
>         ->order('video_qty', 'DESC')
>         ->limit(10)
>         ->all();
>     print_r($data);
> 
>     报错如下：
>     SQLSTATE[08S01] [1047] Unsupported command(COM_STMT_PREPARE) [show full columns from dws_product_video_sale_all]
> ```

你好，doris数据库需要使用pdo_mysql扩展+swoole的hook，并且关闭编译预处理配置，请先自己处理。后续我们再考虑要不要出一个组件支持这个。
