### ISSUE TITLE
orm等最新版部分组件依赖错误

### ISSUE THREAD

**Issue by kihoor** [easy-swoole/easyswoole#578]
composer require easyswoole/orm 
最新版[1.5.4]依赖
[easyswoole/mysqli](https://packagist.org/packages/easyswoole/mysqli): ^2.0
[easyswoole/pool](https://packagist.org/packages/easyswoole/pool): ^1.0

2.x-dev依赖
[easyswoole/mysqli](https://packagist.org/packages/easyswoole/mysqli): ^3.0
[easyswoole/pool](https://packagist.org/packages/easyswoole/pool): ^1.1

但是其他组件比如redis，大多数都依赖[easyswoole/pool]: ^2.0
还有[easyswoole/spl][easyswoole/template]同样有类似的情况，相互依赖混乱，各个组件有的依赖旧版有的依赖新版，这导致新应用安装要掐着子版本来安装，过于麻烦。
希望能统一更新一下依赖关系

**Comment by XueSiLf** [comment]
> composer require easyswoole/orm 最新版[1.5.4]依赖 [easyswoole/mysqli](https://packagist.org/packages/easyswoole/mysqli): ^2.0 [easyswoole/pool](https://packagist.org/packages/easyswoole/pool): ^1.0
> 
> 2.x-dev依赖 [easyswoole/mysqli](https://packagist.org/packages/easyswoole/mysqli): ^3.0 [easyswoole/pool](https://packagist.org/packages/easyswoole/pool): ^1.1
> 
> 但是其他组件比如redis，大多数都依赖[easyswoole/pool]: ^2.0 还有[easyswoole/spl][easyswoole/template]同样有类似的情况，相互依赖混乱，各个组件有的依赖旧版有的依赖新版，这导致新应用安装要掐着子版本来安装，过于麻烦。 希望能统一更新一下依赖关系

你提供一下你的easyswoole版本 php版本 我会给到你安装哪个组件比较合适

**Comment by dcdebug** [comment]
需要注意版本呀，官方的文档用的是最新的版本3.5x 
你在安装的时候，如果不指定版本，应该是最新的版本；
查看版本的方法直接在composer.json中看就行了。

**Comment by XueSiLf** [comment]
> composer require easyswoole/orm 最新版[1.5.4]依赖 [easyswoole/mysqli](https://packagist.org/packages/easyswoole/mysqli): ^2.0 [easyswoole/pool](https://packagist.org/packages/easyswoole/pool): ^1.0
> 
> 2.x-dev依赖 [easyswoole/mysqli](https://packagist.org/packages/easyswoole/mysqli): ^3.0 [easyswoole/pool](https://packagist.org/packages/easyswoole/pool): ^1.1
> 
> 但是其他组件比如redis，大多数都依赖[easyswoole/pool]: ^2.0 还有[easyswoole/spl][easyswoole/template]同样有类似的情况，相互依赖混乱，各个组件有的依赖旧版有的依赖新版，这导致新应用安装要掐着子版本来安装，过于麻烦。 希望能统一更新一下依赖关系

你现在可以直接尝试使用这个骨架：
```bash
composer create-project easy-swoole-php/easyswoole-skeleton:~3.5.x project_name
```
