### ISSUE TITLE
支付组件 微信转账部分有bug

### ISSUE THREAD

**Issue by wuxiandashu** [easy-swoole/easyswoole#585]
vendor\easyswoole\pay\src\WeChat\Utility.php
第129行调用toArray方法还是传2个参数
实际接受只有一个参数，
 /**
     * 转为数组时过滤空值
     * @param array|null $columns
     * @param null $filter
     * @return array
     */
    public function toArray(int|callable $filter = null): array
    {
        return parent::toArray($filter);
    }

**Comment by XueSiLf** [comment]
已修复。
