### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Interface "EasySwoole\Bridge\CommandInterface" not found in /var/www/project/vendor/easyswoole/easyswoole/src/Bridge/AbstractCommand.php:14

### ISSUE THREAD

**Issue by yang131261** [easy-swoole/easyswoole#586]
使用docker 运行easyswoole 

`
docker run --name easyswoole  --network host  --dns 8.8.8.8   -v E:/workspace/project:/var/www/project -p 9501:9501 -it   --privileged -u root  --entrypoint /bin/sh  easyswoolexuesi2021/easyswoole:php8.1.22-alpine3.16-swoole4.8.13
`

`cd /var/www/project
composer require easyswoole/easyswoole
php vendor/bin/easyswoole.php install

cd /var/www/project
php easyswoole.php server start
`
安装官方步骤来的，安装运行easyswoole 提示 PHP Fatal error:  Uncaught Error: Interface "EasySwoole\Bridge\CommandInterface" not found in /var/www/project/vendor/easyswoole/easyswoole/src/Bridge/AbstractCommand.php:14， 请教一下可能是什么原因

**Comment by XueSiLf** [comment]
可能是你windows系统安装了360等安全软件把文件```EasySwoole\Bridge\CommandInterface```误认为是病毒删掉了。

**Comment by yang131261** [comment]
邮件已收到，谢谢

**Comment by XueSiLf** [comment]
> 邮件已收到，谢谢

你可以尝试把安全软件退出试试。
