### ISSUE TITLE
Scalable Datascraper

### ISSUE THREAD

**Issue by goddanao** [easy-swoole/easyswoole#71]
Hello,
i'm trying to understand how easyswoole can help me upgrading my distributed datascraper achitecture which i built on top of zeromq (majordomo pattern + optional titanic queue persistence on redis), msgpack for network packet compression and mongodb for schema-less storage.

With zeromq i can setup a main majordomo broker that maintain a list of available workers identified by names and distributed across multiple machines, creating a pool of each worker type. Using a  vent-sink pattern i push the tasks that need to be performed and these are distributed across the workers as they become available (these are single thread workers, so while working they don't respond to heartbeat and from the broker point of view they become unavailable, and return available after the task is done and the heartbeat is restored). 
The tasks distribution is not following the round robin approach, since the workers internal zmq queue is limited to 1 task and the broker recieve a "task done" aknowledge , so the fastest workers got more tasks todo.

What i love of this approach is that is resilent and consistent, broker down ? no problem, it restart (as it is supervisor monitored) and process the "eventually" persisted titanic queue.
Need more processing power? No problem, spin-up a new node with 100 workers and they immediatly starts working.

What i hate is the memory consumption, each worker requires between 15 to 30 mb, and also the relevant quantity of php code distributed on each worker (the majordomo pattern, titanic and majordomo worker code is written in php, same as the redis queue and few other stuff).

I'd like to hear your opinion about the benefits rewriting this kind of architecture using easyswoole/swoole. Some examples will be very appreciated.

Beg my pardon for my bad english, hope can help me better understand.
thank you!

**Comment by kiss291323003** [comment]
are you chinese or ? you may join the QQ group 633921431

**Comment by goddanao** [comment]
Nope ... I'm italian, anyway i'll try to join the group, 
thankyou.

**Comment by tioncico** [comment]
Why is your name like Chinese name

**Comment by goddanao** [comment]
... Really? Ahaha interesting i'd never know that my alias sounds like a chinese name.
Hope it's a beautiful name in your country!
My real name is Andrea anyway, i'm from Tuscany, a little city between Florence and Prato.

**Comment by goddanao** [comment]
Tried to ask for help in QQ group 633921431, but the language barrier is too high for me.
Thankyou anyway

**Comment by tioncico** [comment]
oh,Your name in Chinese means "God's big brain"
It's very interesting.
