### ISSUE TITLE
启动脚本Bug：php server start --d

### ISSUE THREAD

**Issue by getchu** [easy-swoole/easyswoole#74]
依次执行：
php server start --d
php server stop
php server reload --d

第三条的命令直接报错，找不到 pid 文件，建议：无用是否启用守护进程，都要保存 pid 

另外，
1. 调试场景下，在系统内存不足时，无法启动worker/tasker进程，而manager进程倒是增加了几个；
2. xshell 执行 php server start 即不使用守护进程模式，(午饭后)过段时间后，xshell 断开了ssh连接，重新连接进服务器，ps aux|grep swoole 进程还在，只是无法用 php server stop 杀死，只能用 kill 命令。

建议优化 stop 部分的脚本，尤其是在没有 --d 时：
ps aux|grep swoole |grep -v |cut -c 9-15 | xargs kill -9

ps -ef|grep swoole|grep -v grep|awk  '{print "kill -9 " $2}' | balabalabalalbalabala

**Comment by kiss291323003** [comment]
加QQ 群吧633921431
