### ISSUE TITLE
Undefined property: Swoole\Coroutine\Redis::$connected

### ISSUE THREAD

**Issue by alpheus55** [easy-swoole/easyswoole#75]
Error at file[../vendor/easyswoole/easyswoole/src/Core/Swoole/Coroutine/Client/Redis.php] line[58] message:[Undefined property: Swoole\Coroutine\Redis::$connected]
想问下这是什么问题

**Comment by mabu233** [comment]
代码放出来看看？

**Comment by alpheus55** [comment]
就是例子中RedisPool的代码。

**Comment by kiss291323003** [comment]
协程redis需要你编译拓展的时候，有hireRedis
