### ISSUE TITLE
The easyswoole-wrapped coroutine HTTP client does not provide a set method

### ISSUE THREAD

**Issue by woann** [easy-swoole/easyswoole#77]
Easyswoole packaged coroutine HTTP client, I found no set method, such as $ client-> set (['timeout' => 1]); so now directly using easyswoole http client, want to set the timeout, etc. configuration only Can I add a set to the frame source easyswoole/src/Core/Swoole/Coroutine/Client/Http.php?

**Comment by kiss291323003** [comment]
thanks,i will fix it
