### ISSUE TITLE
是否Http Request和Response对象仅能在Controller中操作？

### ISSUE THREAD

**Issue by Shandawei** [easy-swoole/easyswoole#94]
是否Http Request和Response对象仅能在Controller中操作？
是否只能通过Controller中调用对应的方法获取？
`$this->request();$this->response();`

**Comment by evalor** [comment]
感谢关注，非协程环境下可以单例模式存放Request和Response对象，使得这两个对象可以在其他位置使用，稍后附上样例代码

**Comment by evalor** [comment]
https://github.com/easy-swoole/demo/blob/master/Application/Utility/Box.php

参照上述代码 实现一个存放对象的容器 并在控制器构造方法中将Request和Response放入容器

```php
function __construct(string $actionName, Request $request, Response $response)
    {
        Box::instance('request',$request);
        Box::instance('response',$response);
        parent::__construct($actionName, $request, $response);
    }
```

在其他任意位置取出使用

```php
$request = Box::instance('request');
```

**Comment by cxyangs** [comment]
请问一下在协程环境下通过单例存放Request对象，在afterRequest后对单例资源进行回收，这种方式实现有问题吗，我现在用的es3,通过这种方式来存放的request对象，目前还没发现问题，但是不知道是否会有隐藏的bug出现

**Comment by evalor** [comment]
@cxyangs 协程请勿单例，可以参考Swoole官网例子实现一个协程上下文管理器，以协程ID隔离请求

**Comment by 729343861** [comment]
开始自己写了个单例和注册器在EasySwooleEvent->onRequest 入口将请求和响应实例注册起来，然后在非控制器地方使用，常规使用没有啥问题，但是并发请求接口的时候就会出现部分响应为NULL，比如50次并发，有5次是正常响应数据，45次都响应的是NULL，然而改为BOX单例模式测试依旧如此，不知道如何解决。
