### ISSUE TITLE
TCPSERVER默认没有监听onReceive，onPacket函数

### ISSUE THREAD

**Issue by giantwu** [easy-swoole/easyswoole#98]
在脚本启动时，根据配置文件要实例化server类型，当配置为tcpserver时，没有监听OnReceive，onPacket方法。在EventHelper中已经有这些方法的定义，但没有找到在什么地方调用。

**Comment by kiss291323003** [comment]
你看一下easySwoole的demo，tcp的时候，你给主进程的注册器，注册onReceive回调即可

**Comment by giantwu** [comment]
OK，Demo是看到有，但是没有想清楚为什么不是在框架里面就通过type自动注册了呢，而是在用户在需要时自己在修改，这样如果下次升级框架时也不太方便

**Comment by kiss291323003** [comment]
、、、、、你为什么要框架去注册了呢，全局事件的onMainServer create你可以注册自己的回调，如果我替你注册了，那也不是你要的业务回调吖，框架怎么能只能你们的onReceive回调是要什么呢
